### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by synth3tk** [the-blue-alliance/the-blue-alliance#1040]
As discussed here: https://groups.google.com/forum/m/#!msg/thebluealliance-developers/745-dZA1DQU/i7gSDs2koQcJ

**Comment by fangeugene** [comment]
Cloudflare?

**Comment by gregmarra** [comment]
I've configured a cloudflare account and updated thebluealliance.com's nameservers to point at it by following the instructions at https://support.cloudflare.com/hc/en-us/articles/200170486-How-do-I-use-CloudFlare-s-SSL-for-Google-AppEngine- .

We should check back to see if https://www.thebluealliance.com works once that propogates.

**Comment by gregmarra** [comment]
We're in "flexible" mode, which notes:

```NOTE: Flexible SSL is not recommended if you have any sensitive information on your website.  This option should only be used as a last resort if you are not able to setup SSL on your own web server. This option is far less secure than the Full SSL option indicated below.```

**Comment by gregmarra** [comment]
May need to do more steps from http://blorn.com/post/20185054195/ssl-for-your-domain-on-google-app-engine

**Comment by gregmarra** [comment]
https://www.thebluealliance.com/ loads

**Comment by gregmarra** [comment]
Let's leave this open and monitor things to make sure they all work as expected.

Non HTTPS now redirects automatically. We should make sure the mobile apps work.

**Comment by synth3tk** [comment]
App on my Android tablet seems to be working so far. Even went through
initial setup.

**Comment by fangeugene** [comment]
The Android app doesn't point to the vanity URL.

**Comment by gregmarra** [comment]
Do we have a task to switch it over?

**Comment by synth3tk** [comment]
@phil-lopreiato Did the Android app ever get switched over?

**Comment by phil-lopreiato** [comment]
Yes, it uses https://tba.com
https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/datafeed/retrofit/APIv2.java#L30

**Comment by legoktm** [comment]
Yay! I've submitted https://github.com/EFForg/https-everywhere/pull/3917.

**Comment by synth3tk** [comment]
Interesting. Gameday doesn't stay https.

**Comment by legoktm** [comment]
Hrm...
```
km@km-tp ~> curl -I "https://www.thebluealliance.com/gameday"
HTTP/1.1 302 Moved Temporarily
...
Location: http://www.thebluealliance.com/gameday
```
Should that be filed as a separate ticket?

**Comment by synth3tk** [comment]
I'd say yes.

**Comment by legoktm** [comment]
Alright, now at #1343.
