### ISSUE TITLE
Searching for Championship Doesn't Show Championship Event

### ISSUE THREAD

**Issue by neyre** [the-blue-alliance/the-blue-alliance#1062]
If I search for 'championship', the championship event doesn't show up because none of the division names contain the world 'championship'. This is rather confusing. I would expect all of the divisions to show up in search results.

It could also be nice if there was a centralized page for the championship. Maybe it could show a bracket containing all 32 alliances or rankings of all teams at the event or something.

![image](https://cloud.githubusercontent.com/assets/1348810/3446568/5f5040ea-0143-11e4-89c5-2abd4042b3a7.png)

**Comment by bdaroz** [comment]
Closing as fixed - we have a custom homepage for champs
