### ISSUE TITLE
Implement webhooks-style API

### ISSUE THREAD

**Issue by brennonbrimhall** [the-blue-alliance/the-blue-alliance#1068]
One of the common uses I see for the API is checking to see if a team has won another match, etc.  This could lead to polling and more bandwidth usage than is desirable.

How hard would it be to implement a mechanism like [GitHub's Webhooks](https://developer.github.com/webhooks/), where users subscribe to receive updates at some URL in the form of a POST request with a data payload in the body?

**Comment by phil-lopreiato** [comment]
Webhooks are up and running. See the docs: http://www.thebluealliance.com/apidocs/webhooks
