### ISSUE TITLE
Add elim bracket to API

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1085]

**Comment by fangeugene** [comment]
I think we should just have the client calculate the bracket locally. Especially since 2015 was different.

**Comment by smarthimandrew** [comment]
The issue is that it is difficult to find the fourth team in an alliance if
they don't play in a match

**Comment by fangeugene** [comment]
That's what the alliances endpoint is for.

**Comment by smarthimandrew** [comment]
I stand corrected. Is that a new addition to the API? I don't remember that
existing when I asked for the creation of this issue

**Comment by phil-lopreiato** [comment]
It was added in #1039

**Comment by bdaroz** [comment]
This is generally derivable from APIv3 now with the `Elimination_Alliance` model and the match data.
