### ISSUE TITLE
Deprecate APIv1

### ISSUE THREAD

**Issue by brandondean** [the-blue-alliance/the-blue-alliance#1087]
At what point do we set a date for pulling the plug on APIv1, and start announcing its coming doom?

Looking at the previous 2 requests available in the logs  (`event/details`) they had a response time of 3000ms and 4000ms - accounting for 33 RPCs each. 

With 16,554 requests in the past 30 days at some point it's going to break and be too expensive to maintain it. We should start the process of pushing it off the cliff ourselves.

**Comment by gregmarra** [comment]
Happy 2015!

**Comment by fangeugene** [comment]
:tada:
