### ISSUE TITLE
DatafeedFms urls return an error

### ISSUE THREAD

**Issue by mc10** [the-blue-alliance/the-blue-alliance#1103]
Specifically, https://my.usfirst.org/frc/scoring/index.lasso?page=eventlist and https://my.usfirst.org/frc/scoring/index.lasso?page=teamlist are broken, causing builds to fail.

**Comment by gregmarra** [comment]
This also prevents bootstrapping a test instance with team data.

**Comment by gregmarra** [comment]
FRC API will be the future here.
