### ISSUE TITLE
Make sure elim brackets, advancement notifications, etc work for 2015 game

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1108]
Playoff advancement is weird. Thanks, FIRST.

Edit: Also, playoff order is different.

Edit 2: 2015 district points -- is it WLT?

**Comment by phil-lopreiato** [comment]
See Manual section 5.4.3 for a description of the new playoff system. Total points scored for SF, QF, head to head best of 3 for the finals.

Here's the new play order:
```
Quarter Finals
■ ■ Round 1: QF1 (A4 vs. A5), QF2 (A3 vs. A6), QF3 (A2 vs. A7),
QF4 (A1 vs. A8)
■ ■ Round 2: QF5 (A4 vs. A6), QF6 (A3 vs. A5), QF7 (A2 vs. A8),
QF8 (A1 vs. A7),
Semi Finals
■ ■ Round 1: SF1 (Q2 vs. Q3), SF2 (Q1 vs. Q4),
■ ■ Round 2: SF3 (Q2 vs. Q4), SF4 (Q1 vs. Q3)
■ ■ Round 3: SF5 (Q3 vs. Q4), SF6 (Q1 vs. Q2)
Finals
■ ■ F-1, F-2, F-3*
```

**Comment by phil-lopreiato** [comment]
And here's some updates on district points: http://www.usfirst.org/roboticsprograms/frc/blog-changes-to-district-points-2015

**Comment by first3234** [comment]
I think for this year that the playoff part should show the total scores between the matches but not just that for the alliance's

**Comment by fangeugene** [comment]
This game...

![capture](https://cloud.githubusercontent.com/assets/1421884/6324722/15c1c3c6-bb0c-11e4-8e68-d10b46da2afb.PNG)

![capture2](https://cloud.githubusercontent.com/assets/1421884/6324723/15ca59dc-bb0c-11e4-862e-7d08f5ccac32.PNG)

**Comment by fangeugene** [comment]
Fixed in https://github.com/the-blue-alliance/the-blue-alliance/commit/bfe8ae14e401ab67b601878500180aa4c59be9d0 through https://github.com/the-blue-alliance/the-blue-alliance/commit/4b5d790dd31a3e71d5047ea8f3d5b05488ee3126

**Comment by fangeugene** [comment]
Will deal with district points in https://github.com/the-blue-alliance/the-blue-alliance/issues/1125
