### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by mc10** [the-blue-alliance/the-blue-alliance#1112]
The site currently fails to load at all for me.

**Comment by fangeugene** [comment]
It was down for me earlier, then was up, and now it's down again.
Someone reported it being down on the Facebook page as well. 

http://www.downforeveryoneorjustme.com/http://www.thebluealliance.com/ shows that it is up and using the appspot URL works for me. Maybe something weird with the DNS and routing?

**Comment by brycematsuda** [comment]
Seems to be okay now on my end.

**Comment by mc10** [comment]
Yeah looks okay now for me too, though loading speed is on the slow side.
