### ISSUE TITLE
Allow more than one website per event, team

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1114]
Allow more than one website for an event or team, specifically so we can support social media accounts.

**Comment by synth3tk** [comment]
Social media accounts are now a media item. I can't think of other valid use cases for this, as even events rarely (if ever) have multiple sites. @fangeugene?

**Comment by fangeugene** [comment]
Agreed. Social media is a thing, and I don't think multiple sites is worth worrying about.

**Comment by dracco1993** [comment]
Agreed.  I think this would make things more confusing.

**Comment by fangeugene** [comment]
What an underwhelming issue #1114.
