### ISSUE TITLE
Update trusted api for 2015 game

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1115]
W/L/T is currently required, but has no meaning in the 2015 game, etc.

**Comment by first3234** [comment]
you could put it on but  say it does not count to the  final ranking and still have the averges

**Comment by gregmarra** [comment]
@fangeugene is this resolved?

**Comment by fangeugene** [comment]
No it is not.

**Comment by phil-lopreiato** [comment]
This will probably happen in conjunction with #1190
