### ISSUE TITLE
Display win-loss-tie overall records for team in history page.

### ISSUE THREAD

**Issue by KenyonPrater** [the-blue-alliance/the-blue-alliance#1116]
Currently, when viewing a team's page for a specific year, eg http://www.thebluealliance.com/team/1/2014, you can get a brief overview of the team's performance over that year by glancing at the top of the Event Results tab:
_Overall, team 1 was 10-17-0 in 2014._

It would be nice to be able to see this same feature on the team's history page, eg http://www.thebluealliance.com/team/1/history, adding all past years records together for the total score. For example,

_Overall, team ___ is 42-42-42 since [either 2002 or the first year of competition]"_

**Comment by fangeugene** [comment]
This year's game actually makes this less relevant, now that there is precedent for W-L-T not meaning anything for a season.

**Comment by lyncas** [comment]
i think the history page works fine.  W-L-T per season might be nice but not necessary.     if anything we just need to make sure awards are properly linked up to the history page.   Offseason winners still have not been linked to the awards page for most offseason events.

**Comment by bdaroz** [comment]
This is now live on TBA, closing.
