### ISSUE TITLE
Can't request single match from event ending in a number

### ISSUE THREAD

**Issue by bvisness** [the-blue-alliance/the-blue-alliance#1118]
I can't do a single match request for an event whose key ends in a number. For example, this query gives an error:

www.thebluealliance.com/api/v2/match/2014mnmi2_qm1

But this does not:

www.thebluealliance.com/api/v2/match/2014mnmi_qm1

Both of these matches are accessible through the main site, but not through the API. I have also tested this with events 2014cafc and 2014cafc2.

**Comment by fangeugene** [comment]
Fixed in https://github.com/the-blue-alliance/the-blue-alliance/commit/865f3620b6f745bd9844981b73003dd80b4ebaf9
