### ISSUE TITLE
Update District Points for 2015

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1125]
New point system here: http://www.usfirst.org/sites/default/files/uploadedFiles/Robotics_Programs/FRC/Game_and_Season__Info/2015/FRC_District_Standard_Points_Ranking_System_2015%20Summary.pdf

There's some fun math for calculating the qualification scores

**Comment by phil-lopreiato** [comment]
When we update the math, it would be nice to tweak the calculation structure to allow for easier sending of DISTRICT_POINTS_UPDATED notifications.

Maybe a cronjob that calls [DistrictPointsCalcDo](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/controllers/cron_controller.py#L427) every hour or something for live events. That way, we can check and see if the event has any more matches within the next hour (this can allow for a mid-day update during lunch breaks, say). If not, then we can send the points updated notifications.

**Comment by fangeugene** [comment]
This won't happen for another week. ):

**Comment by phil-lopreiato** [comment]
Done in 73a6dbc78e3a50692052e35bc435af34518043cf
