### ISSUE TITLE
API: Add week number to event model

### ISSUE THREAD

**Issue by ichiefboz** [the-blue-alliance/the-blue-alliance#1127]
Could the week number be added to the event model on the API? So that, for example, at the endpoint `/events/2015mnmi`, you would get:

    {
      "key": "2015mnmi",
      "website": "http://www.mnfirst.org",
      "official": true,
      "end_date": "2015-04-04",
      "name": "Minnesota 10000 Lakes Regional",
      "short_name": "Minnesota 10000 Lakes",
      "facebook_eid": null,
      "event_district_string": null,
      "venue_address": "Williams Arena/The Sports Pavilion Univ of MN\n1925 University Avenue SE\nMinneapolis, MN 55455\nUSA",
      "event_district": 0,
      "location": "Minneapolis, MN, USA",
      "event_code": "mnmi",
      "year": 2015,
      "week_number": 6,
      "webcast": [],
      "alliances": [],
      "event_type_string": "Regional",
      "start_date": "2015-04-01",
      "event_type": 0
    }

For events in the regular season, `week_number` would be that event's week number; for championship it would return something bigger like `100` and pre-season stuff would return `0`.

**Comment by fangeugene** [comment]
Yes, this is planned.

**Comment by phil-lopreiato** [comment]
We would need to restructure some of the week calculations, though. We'd have to make [EventHelper.groupByWeek](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/helpers/event_helper.py#L40) be able to calculate the week for a single event (and it should probably get into the model, as well).

**Comment by fangeugene** [comment]
Yeah, this is more involved than it appears at the surface. No timeline on when it will be implemented.

**Comment by fangeugene** [comment]
Done in https://github.com/the-blue-alliance/the-blue-alliance/commit/8e8c34efacb7b30fedef65ea364c1439b9c0bc45
