### ISSUE TITLE
Team Rankings 2015

### ISSUE THREAD

**Issue by brrian27** [the-blue-alliance/the-blue-alliance#1136]
Could we add rankings into the team description for each regional, similar to previous years?

Currently reads: "Team XXX had an average qual score of XX and an average playoff score of XX won the following awards"

Desired: "Team XXX was rank XX had an average qual score of XX and an average playoff score of XX won the following awards"

**Comment by fangeugene** [comment]
Good idea. Will fix.

**Comment by fangeugene** [comment]
All fixed! It was not showing up due to a small bug, not because we removed the feature. :smile:
