### ISSUE TITLE
Glyphicons in Firefox

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1137]
Firefox doesn't like "Cross Origin Requests" so it blocks loading the glyphicon scripts. 

See
https://stackoverflow.com/questions/24232827/bootstrap3-1-1-glyphicons-not-working-in-firefox
https://stackoverflow.com/questions/21680700/local-bootstrap-3-1-glyphicons-not-loading-in-firefox

Fix appears to be to keep a copy of the ttf files on the same domain (so include them in the project) and access the from there

![screenshot from 2015-03-04 13 44 49](https://cloud.githubusercontent.com/assets/2754863/6490497/c673f616-c274-11e4-820d-83424a31b69a.png)

**Comment by fangeugene** [comment]
But then we don't get to take advantage of CDNs );

**Comment by phil-lopreiato** [comment]
Wait, I think it's my https everywhere messing with things. Can we set the cdns to use https?

**Comment by fangeugene** [comment]
If it works, go for it.

**Comment by phil-lopreiato** [comment]
I'll play around with it

**Comment by phil-lopreiato** [comment]
Duplicate of #911, and I don't see an easy way to fix this. I'll just change the rules on my end
