### ISSUE TITLE
API Endpoint for All Team's Awards

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1154]
Like what's being discussed here: https://github.com/Team254/cheesy-arena/pull/8

Plan: Have endpoint `/api/v2/team/<number>/history`

Return value: array of events, which contain awards won at that event
```
[
{'eventKey': '2014cur', 'eventName': 'Curie Division', 'awards': ['Winner', 'Chairman's Award', 'Best Corndogs']},
...
]
```

Any issues with this?

**Comment by fangeugene** [comment]
The list of awards should be Award models, as defined here: http://www.thebluealliance.com/apidocs

Those already contain event_key, so maybe the additional event breakdown is unnecessary? More work for the consumer, but that's all Cheesy Arena and the TBA app need.

**Comment by phil-lopreiato** [comment]
Good point. I did also want to return all the event keys/names the team has completed at, so we can build the team history page from this data, as well.
