### ISSUE TITLE
District Points Off

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1160]
Compare http://www.thebluealliance.com/events/ne and http://frc-districtrankings.usfirst.org/NE
- 5687 has two extra points from marea (TBA shows 51, should be 49)
- 236 should be ranked number 10 (they show as 15, are missing points from cthar)
- 195 is missing a ton of points from cthar (should have 73 and be ranked 15)

Are you sure the calcs have run for Week 5 events?

**Comment by fangeugene** [comment]
Oh I think this has to do with how the inverse error function gets computed.

http://www.usfirst.org/sites/default/files/uploadedFiles/Robotics_Programs/FRC/Game_and_Season__Info/2015/FRC_District_Standard_Points_Ranking_System_2015%20Summary.pdf

**Comment by fangeugene** [comment]
Most of this is fixed. The only errors should now come from teams that played in outside districts.

**Comment by fangeugene** [comment]
Should be fixed now.
