### ISSUE TITLE
Awards Errors

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1161]
The name of the winner of the Woodie Flowers award in the 2006 Israel Regional (http://www.thebluealliance.com/event/2006is) is Adi Idan and he’s from 1574, as 1547 (as listed) didn’t participate in the Regional.

The name of the winner of the Woodie Flowers award in the 2012 Israel Regional (http://www.thebluealliance.com/event/2012is) is Haim Dribin (not Derivin as listed).

**Comment by nitays** [comment]
still not fixed...

**Comment by fangeugene** [comment]
Fixed now.
