### ISSUE TITLE
2005 PNW duplication

### ISSUE THREAD

**Issue by legoktm** [the-blue-alliance/the-blue-alliance#1165]
* http://www.thebluealliance.com/event/2005wa
* http://www.thebluealliance.com/event/2005or

It appears that 2005or is the correct code: https://my.usfirst.org/myarea/index.lasso?page=teamlist&event_type=FRC&sort_teams=number&year=2005&event=or

**Comment by fangeugene** [comment]
We need a tool to merge the associated matches/awards/eventteams.

Similarly, there is also a duplicate Great Lakes Regional in 2005.

**Comment by fangeugene** [comment]
Fixed with the following script:

```
from models.match import Match
from helpers.match_manipulator import MatchManipulator
from google.appengine.ext import ndb


matches = Match.query(Match.event==ndb.Key('Event', '2005glr')).fetch()

for match in matches:
    match.event = ndb.Key('Event', '2005gl')
    match.key = ndb.Key('Match', match.renderKeyName(match.event_key_name, match.comp_level, match.set_number, match.match_number))

MatchManipulator.createOrUpdate(matches)
```

**Comment by legoktm** [comment]
I assume you had a similar/different script for PNW? :)

**Comment by fangeugene** [comment]
Yeah with changed event codes.
