### ISSUE TITLE
Finals Matches for MWR

### ISSUE THREAD

**Issue by popnbrown** [the-blue-alliance/the-blue-alliance#1169]
Final Matches 2 and Final Matches 3 for 2015 Midwest Regional are actually Semi-Final matches from the Wisconsin Regional.

http://www.thebluealliance.com/match/2015ilch_f1m2
http://www.thebluealliance.com/match/2015ilch_f1m3

I don't think we actually have videos for these matches up anywhere.

**Comment by fangeugene** [comment]
The Finals 3 video looks correct. I have fixed Finals 2.

**Comment by popnbrown** [comment]
Sorry, you're right. Thanks!
