### ISSUE TITLE
Homepage displays pre-competition layout

### ISSUE THREAD

**Issue by synth3tk** [the-blue-alliance/the-blue-alliance#1172]
As reported here: https://www.reddit.com/r/FRC/comments/32eq8m/the_blue_alliance_is_a_few_months_behind_the_times/

**Comment by fangeugene** [comment]
Oops. That's what happens when there are no events. Time to switch to
champs landing page.

**Comment by fangeugene** [comment]
Fixed in https://github.com/the-blue-alliance/the-blue-alliance/commit/c0003cfd40a56d4fc25d11ae18a6a3fcdc737ed0
