### ISSUE TITLE
Crowdsourcing for team social media

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1177]
Build crowdsourcing flows for facebook / twitter / instagram.

Implementation options:
- separate `facebook`, `twitter`, `instagram` fields on team models
- combined `social_media` json field that is more extensible to add things in the future (github? tumblr? weibo?)

Will enable incorporating features like https://developers.facebook.com/docs/plugins/page-plugin

**Comment by phil-lopreiato** [comment]
I like this. I think the implementation should be a little different though - maybe we can try a SocialMedia model that has a type (via int constant) and a teamKey reference. That way, we can query more easily

**Comment by popnbrown** [comment]
Extensible is the way to go. I can absolutely see teams linking their
github and etc. It'd be a good way for teams to get some extra traffic and
potentially allow people to make some interesting connections.

Sincerely,
Sravan Suryadevara
E-mail | sravan.suryadevara@gmail.com
Phone | (908) 432-5330

**Comment by synth3tk** [comment]
Suggestions for social media is a thing now.

Extensibility discussion currently happening in #1704.
