### ISSUE TITLE
Webhook's content-type header should be application/json

### ISSUE THREAD

**Issue by ironmig** [the-blue-alliance/the-blue-alliance#1178]
Webhook data is formated in json, so the content-type header should be application/json, text/json, etc. Currently, it sends application/x-www-form-urlencoded. This can cause webservers to parse it as if it was a url encoded form (query strings). Looking though the source code, it seems that this might be due to an ouside library (urllib2?), but I'm not sure.

**Comment by phil-lopreiato** [comment]
Hey, somebody using webhooks!

That's a very good point, I'll make sure to fix that asap

**Comment by ironmig** [comment]
Thanks for the speedy fix. Webhooks are great! Just finished implementing secure (verified using hash in header) live updates for TBA for my scouting web app.

**Comment by phil-lopreiato** [comment]
Happy you like them! They were the logical evolution of our mobile push notifications, and surprisingly easy to implement. Plus, we like them because they reduce polling on the API :)

**Comment by gregmarra** [comment]
@phil-lopreiato  is there anything left here?

**Comment by phil-lopreiato** [comment]
#1179 just needs to be merged, then this will auto-close
