### ISSUE TITLE
Look Into Push Notifications for Browsers

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1182]
http://updates.html5rocks.com/2015/03/push-notificatons-on-the-open-web

Looks like we'll just have to add a WEB ClientType, which will act just like android (it seems these APIs go though GCM, as well).

We can make GameDay prompt the user to display the same notifications that would be sent to mobile devices. This might also be a good opportunity to implement cross-device dismisses, as well.

**Comment by phil-lopreiato** [comment]
FYI - what I linked above is just for Chrome 42+. I like it, however, because it fits in _really_ nicely with our existing notification infrastructure (can receive GCM messages, even when the webpage isn't open). This looks like it'll be pretty easy to integrate. FF doesn't not have an equivalent for desktop browsers.

Unless anybody can find a better solution, we can still fall back on [html5 notifications](https://developer.mozilla.org/en-US/docs/Web/API/notification), posted from GameDay, for all other browsers. We can probably base them off the incoming Firebase stream (only notify for favorite teams, which we can already easily filter for)

**Comment by phil-lopreiato** [comment]
And now Firebase Cloud Messaging (successor to GCM) supports this between Chrome/Firefox/Opera.

https://firebase.googleblog.com/2016/10/announcing-firebase-cloud-messaging-for.html?

**Comment by ZachOrr** [comment]
I would love to see this feature 🙏 Let me know if there's something I can help with

**Comment by fangeugene** [comment]
We're not using topics right now right?

**Comment by phil-lopreiato** [comment]
> We're not using topics right now right? 

Nope.

I'm hoping someone who is more competent at javascript than I wants to take a stab at this one. If it'll be easier, we could even restrict the feature to gameday2. The base idea: 
 - Add a [ClientType](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/consts/client_type.py) constant for browsers
 - Get the gcm token client side and send it to the backend somehow, enabling it to associate with your account and create a [MobileClient](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/models/mobile_client.py) model for it.

**Comment by nwalters512** [comment]
I guess I've recently become the resident JS guy, so I can take a stab at this (no guarantee on a timeline though, school is busy). I'll read over the docs sometime and see how we should do this.

**Comment by fangeugene** [comment]
https://github.com/the-blue-alliance/the-blue-alliance/pull/1667
