### ISSUE TITLE
Add Championship webcasts

### ISSUE THREAD

**Issue by synth3tk** [the-blue-alliance/the-blue-alliance#1184]
I should be able to knock this out later tonight.

**Comment by fangeugene** [comment]
http://science.ksc.nasa.gov/robotics/first/st-louis-2015/

**Comment by fangeugene** [comment]
I added them. Hopefully they don't change.

http://ksc-event1.infozen.cshls.lldns.net/infozen/ksc-event1/ksc-event1.m3u8
for event1 thru event8

**Comment by synth3tk** [comment]
Thanks. Travel plans changed so I couldn't get to it tonight.
