### ISSUE TITLE
Match results duplicating alliance as both red and blue

### ISSUE THREAD

**Issue by jlmcmchl** [the-blue-alliance/the-blue-alliance#1185]
I have 27 set as a favorite team, and in Q61 it says their alliance played as both red and blue. The scores are different, however: http://imgur.com/uPTUWvg

Actually, this holds for all the matches that have completed today (56-63). It seems that it is not an issue with the ticker, but the data itself.

**Comment by fangeugene** [comment]
Fixing.

**Comment by phil-lopreiato** [comment]
Fixed in https://github.com/the-blue-alliance/the-blue-alliance/commit/8a0bcfe62546e306a3152cf851be7f2cf9303259
