### ISSUE TITLE
Allow user to change robot picture

### ISSUE THREAD

**Issue by nathan815** [the-blue-alliance/the-blue-alliance#1186]
I think it would be nice if the person who originally submitted a team's robot picture could delete/change it. A little while ago I submitted another robot picture on my team's page and now there is an image carousel (which is cool, but it would be nice to have the option to change it as well).

**Comment by gregmarra** [comment]
More media management options would be awesome, but I'm a bit wary of attaching 'ownership' to suggestions. I'd like to keep media unowned so it's easier for others to suggest corrections / errors / etc without worrying about the original uploader.

**Comment by SUPERCILEX** [comment]
@nathan815 You can now suggest media [here](https://www.thebluealliance.com/suggest/team/media?team_key=frc2521&year=2017).

@phil-lopreiato This issue can be closed.

**Comment by nathan815** [comment]
@SUPERCILEX That functionality already existed when I submitted this request. What I'd like to see, and what this issue is about, is a system for requesting removal of or reordering of media.

**Comment by SUPERCILEX** [comment]
@nathan815 Oh, that sounds really cool actually! Never mind then. (I was going through old issues for @phil-lopreiato)

**Comment by fangeugene** [comment]
This should be implemented as the suggest delete/upvote/downvote system discussed in the 2017 Spring Developers Meeting.

**Comment by bdaroz** [comment]
Also this may be resolved with the "modtools" project underway. Assigning to Phil.

**Comment by bdaroz** [comment]
Closing as fixed with `modtools`
