### ISSUE TITLE
Twitch chat doesn't log in

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1189]
My twitch chat just sits here, expontential backoff erroring. This is when I am signed in via my Facebook as Greg Marra. I do not get this when signed in as tbagameday. Not sure if this is widespread.

![screen shot 2015-04-25 at 14 31 29](https://cloud.githubusercontent.com/assets/57101/7334951/e954514c-eb57-11e4-9058-fa119097f09e.png)

**Comment by synth3tk** [comment]
Do you still have this problem?

**Comment by dracco1993** [comment]
I had this same issue today.

I was able connect after I went to http://twitch.tv/tbagameday, signed in, then refreshed the page.

**Comment by synth3tk** [comment]
They switched from Flash to websockets recently so this shouldn't be happening. 

What's your OS and browser?

**Comment by dracco1993** [comment]
OS X 10.10.4
Chrome 43.0.2357.132 (64-bit)

It could be something different, but it appeared that I was experiencing the same end result.

**Comment by SUPERCILEX** [comment]
@phil-lopreiato This is a really old issue that probably isn't relevant anymore.
