### ISSUE TITLE
Offseason "Event Wizard" for Live Data

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1190]
We should definitely extend the live-input page @fangeugene wrote and make it featured enough to submit all data for an event.

Looking through the FMS user guide, here are the important steps in the real Event Wizard we should implement:
 - Event selection. Either via dropdown of current live events, or by key input
 - Team selection (either by entering a comma separated list, or uploading team list report from FMS)
 - Schedule import (by FMS report)
 - Match play. Select mode (quals or elims), populate existing matches and enter scores. Like the matchinput page used this weekend. There should be an option to auto-calculate rankings on score input, because it would be a  pain to export/upload rankings all the time. It shouldn't be too hard to import our own rankings calculations.
 - Alliances. We can probably do import by csv like we have now. Easy enough to type in. Can do by FMS report if someone can find an example of one
 - Awards. Fields for award name, team number, and person. 

We should try and keep all of these requests to be AJAX so keys don't have to be entered over and over. Looks like we can use [this](https://github.com/SheetJS/js-xlsx) to parse FMS reports client side.

**Comment by nwalters512** [comment]
I'm not super familiar with web bev, but if there's a way to store credentials persistently (in a cookie, local database, whatever) we should take advantage of that. Having to reenter keys every time I refreshed was a pain.

**Comment by fangeugene** [comment]
We can also tie these to Accounts, if people are logged in.

**Comment by phil-lopreiato** [comment]
I think we want to have the possibility to use this without an account - the use case I'm thinking of is having the webpage open on the FMS server also, and I wouldn't be comfortable logging into my Google Account on that.

When the user selects an event, we can check if the keys are stored in a [cookie](http://www.w3schools.com/js/js_cookies.asp) (ensuring the secret stays client side only) and only prompt again if necessary.

**Comment by nwalters512** [comment]
I agree with both points. An advantage of allowing this by account is you can abstract away the key/secret stuff and just tie permissions to an account; that would make it easy to assign/revoke permission on the fly.

**Comment by fangeugene** [comment]
Por que no los dos?

On 4/26/15, Nathan Walters <notifications@github.com> wrote:
> I agree with both points. An advantage of allowing this by account is you
> can abstract away the key/secret stuff and just tie permissions to an
> account; that would make it easy to assign/revoke permission on the fly.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/the-blue-alliance/the-blue-alliance/issues/1190#issuecomment-96419518


-- 
-Eugene

**Comment by phil-lopreiato** [comment]
> Por que no los dos?

:+1: 

If I get the chance in a week or so, I'll take a stab at this. I'd like to have a working prototype by CT Champs, May 16 (which is one of the first offseason events).

**Comment by phil-lopreiato** [comment]
FYI, we'll need #1107 to pull the list of currently active events for this

**Comment by phil-lopreiato** [comment]
Made some updates on https://github.com/phil-lopreiato/the-blue-alliance/tree/event-wizard

Dependencies: 
 - #1115 (rankings need update - can we make it a more generic format, like just send the json array that's stored internally?)
 - #1107 so we can auto-populate a list of currently competing events

![screenshot from 2015-04-29 12 12 53](https://cloud.githubusercontent.com/assets/2754863/7400578/f6a12942-ee8b-11e4-8d47-5bbe59babbae.png)
