### ISSUE TITLE
Media Suggestions allow duplicate suggestions

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1193]
http://www.thebluealliance.com/team/610

**Comment by synth3tk** [comment]
Should be pretty simple, right? Check the key, if it exists, tell them "YOU SHALL NOT PASS"?

**Comment by fangeugene** [comment]
I thought we already prevented duplicates. Might be some concurrency issue if you hit "Accept" twice.

**Comment by synth3tk** [comment]
I think you're right. Just tried submitting that same video twice and it doesn't show up in suggestions.

**Comment by bdaroz** [comment]
#1194 closed as complete. Closing this as likely a concurrency issue per Eugene.
