### ISSUE TITLE
Embeddable Widgets

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1196]
For a team's season results on websites (and maybe CD signatures like back in the old days).

**Comment by gregmarra** [comment]
I'm worried about the maintenance cost here – should we just advise people
to use the API?

**Comment by synth3tk** [comment]
I think it would be nice to have something like this again. Offer dynamic widgets for websites, as well as images like the old signature banners.

**Comment by phil-lopreiato** [comment]
Maybe we write some example snippets that use webhooks/API to "build your own widget"?

The old image bars would be nice to bring back though (currently, tba.net has a redirect loop)

**Comment by fangeugene** [comment]
Greg, what issues with maintenance do you foresee?
