### ISSUE TITLE
Write Offseason Event Spreadhseet Importer

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1205]
Should work similarly to `/admin/offseasons`, except it pulls data from [this spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0ApfHZGrvPfuAdHVZcTczVnhQVnh1RlNEdVFmM2c3Y1E&usp=sharing#gid=4)

We'd need some library to interact with Google Sheets. [This seems like a good place to start](http://stackoverflow.com/questions/1142730/python-spreadsheet)

**Comment by gregmarra** [comment]
I also think we could write an on-site bulk-submitter instead, and deprecated the spreadsheet. It was just a hack that lasted... 3 years :)

**Comment by phil-lopreiato** [comment]
@gregmarra you mean the video spreadsheet? I actually like it, because the video archival scripts I have all generate csv data that I can copy/paste in. Although an API for submissions would eliminate that use case.
