### ISSUE TITLE
[Event Wizard] Second Teams & Pre-Rookies

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1214]
Second teams: 
- Have input on event wizard that maps real team numbers to their second, third, etc. teams
- Do key translation: "9254" -> "frc254B"

Pre-Rookies:
- Team keys that are not real teams or second teams are flagged as "dummies"
- Don't create Team models from offseason events to avoid [Team 6001](https://groups.google.com/forum/#!topic/thebluealliance-developers/e1SDWTr8OLI) issues

**Comment by fangeugene** [comment]
The pre-rookie issue should be fixed not just for event wizard, but also for any manual score input.
