### ISSUE TITLE
GCM Improvements

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1215]
# io2015

Move myTBA notifications to a more pub/sub architecture 
https://developers.google.com/cloud-messaging/topic-messaging

Post notifications to relevant topics (which users are subscribed too), and GCM handles the distribution

**Comment by nwalters512** [comment]
Things to consider:

* what to do if a user has multiple devices (how to keep subscriptions in sync between devices)
* how this fits in with future cross-platform efforts (what will we do if we ever decide to implement for Windows or whatever Samsung will ultimately fork off of Android)
* can subscriptions be managed from server-side code?

Basically, we'll still have to store copies of all this data on the server, and I'm not sure if the work required to keep everything in sync is worth the effort or even possible.

**Comment by phil-lopreiato** [comment]
Definitely some good points. I think the third item is the biggest concern (because integrating myTBA with the web is a big priority), and I didn't see anything in the docs about that. If we need to keep the current infra in order to maintain feature parity/extensibility, then this probably won't be worth it.

**Comment by synth3tk** [comment]
From what I can tell, there's no Windows support for GCM, so we'd definitely need to figure that out.

**Comment by phil-lopreiato** [comment]
Windows has [it's own GCM-like thing](https://msdn.microsoft.com/en-us/library/windows/apps/hh913756.aspx). It should be able to plug into our existing flow pretty well.

We'll have to be careful not to make any core functionality rely on GCM specific features to keep cross-platform compatibility.

**Comment by synth3tk** [comment]
Don't know how I missed that, cheers! I'll probably need to pick your brain once I get around to implementing it, since I didn't pay much attention when GCM was added.

**Comment by phil-lopreiato** [comment]
Sure! Just ping me whenever.

To get started, it should (hopefully) be pretty easy. The points you'll probably have to hit
 - Registration - sending the push data to the server. This might be the trickiest part. Currently, we use App Engine's [Cloud Endpoints](https://cloud.google.com/appengine/docs/python/enadpoints/), which doesn't have direct Windows support, but we might be able to just send POST requests
 - Add a [ClientType](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/consts/client_type.py)
 - Add support in [BaseNotification](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/notifications/base_notification.py) and [Notification Sender](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/helpers/notification_sender.py)

**Comment by nwalters512** [comment]
Regarding bullet 1, I read something somewhere about how cloud enpoints exposes a RESTful API that you can use to manipulate things on platforms without a generated client available. I'll see if I can dig it up again.

**Comment by synth3tk** [comment]
Found it: https://apis-explorer.appspot.com/apis-explorer/?base=https://tbatv-prod-hrd.appspot.com/_ah/api#p/

Just need to figure out how to construct the fields.

**Comment by ZachOrr** [comment]
Hitting Nathan's original comments

`what to do if a user has multiple devices (how to keep subscriptions in sync between devices)`
Either group a user's devices together in to [device groups](https://firebase.google.com/docs/cloud-messaging/js/device-group) (requires some management on our side) or subscribe/unsubscribe all of a client's devices [from a topic](https://firebase.google.com/docs/cloud-messaging/js/topic-messaging) when they update their subscriptions. We'll probably do the latter.

`how this fits in with future cross-platform efforts`
We can dispatch one notification to target all OS' - although only web, Android, and iOS are supported right now. TBANS will be setup to add support for other systems, if we want.

`can subscriptions be managed from server-side code?`
Yes, via the [Instance ID API](https://developers.google.com/instance-id/) - which is what those push tokens we have in the DB are.

**Comment by ZachOrr** [comment]
Going to close this - I think we figured out what it is we want to do using the new FCM stuff
