### ISSUE TITLE
iOS Push Notifications

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1216]
Work with @ZachOrr to add server-side myTBA support for iOS.

Should actually be really easy, since [GCM Supports iOS now](https://developers.google.com/cloud-messaging/ios/start)

Can probably share code with #1182

**Comment by ZachOrr** [comment]
Once we have a developer account/access to an iOS Dev Center where I can generate APNS certs, I can pass over the necessary information to generate a config file. Looks pretty straight forward from there.

**Comment by phil-lopreiato** [comment]
@gregmarra can help with that.

I'm super pumped for the GCM announcements, having iOS support makes this so much simpler

**Comment by phil-lopreiato** [comment]
Here are some docs that'll come in handy whenever we get this done
 - https://developers.google.com/cloud-messaging/ios/client
 - https://cloud.google.com/appengine/docs/java/endpoints/consume_ios

Basic Flow:
 1. Sign in to google account. Cloud Endpoints library [has code to do this](https://cloud.google.com/appengine/docs/java/endpoints/consume_ios#Java_Adding_a_sign-in_dialog_to_your_iOS_client)
 2. Get GCM Token
 3. Send GCM Token to TBA using cloud endpoints
 4. Receive push notifications, or mutate myTBA data, via GCM/Cloud Endpoints

**Comment by gregmarra** [comment]
@ZachOrr are we blocked on the iOS Dev Center thing? Should I figure out how to move that forward?

**Comment by ZachOrr** [comment]
We for sure need to get the iOS Dev Center thing figured out, but I wouldn't say we're blocked by it. There's still code to write.
