### ISSUE TITLE
Windows notifications

### ISSUE THREAD

**Issue by synth3tk** [the-blue-alliance/the-blue-alliance#1217]
Continued from #1215:

> To get started, it should (hopefully) be pretty easy. The points you'll probably have to hit
> - Registration - sending the push data to the server. This might be the trickiest part. Currently, we use App Engine's [Cloud Endpoints](https://cloud.google.com/appengine/docs/python/enadpoints/), which doesn't have direct Windows support, but we might be able to just send POST requests
> - Add a [ClientType](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/consts/client_type.py)
> - Add support in [BaseNotification](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/notifications/base_notification.py) and [Notification Sender](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/helpers/notification_sender.py)

The goal is to have this ready to go by week 1, 2016. We'll need to make GCM and [WNS](https://msdn.microsoft.com/en-us/library/windows/apps/hh913756.aspx) talk nice to each other in order to get this to work.

List of URLs for our GCM API (which addresses the first bulletpoint) can be [found here](https://apis-explorer.appspot.com/apis-explorer/?base=https://tbatv-prod-hrd.appspot.com/_ah/api#p/).

Related issue: the-blue-alliance/the-blue-alliance-windows#6

**Comment by phil-lopreiato** [comment]
Oh yeah, forgot about the API explorer. It will show the full HTTP request/response if you actually go through with a request - that should show you how to construct the body. The server-side spec is [here](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/models/mobile_api_messages.py), if that helps. You'll have to use oauth, it's how we tie the request to an account.

As far as WNS goes, we'll hook the sending logic [like this](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/helpers/notification_sender.py#L14). We'll just need a library that can make the right POST request to WNS - [this looks good](https://github.com/Neetuj/python-wns) from a quick search
