### ISSUE TITLE
Event Wizard - FMS Results input after Quarters returns frcundefined error

### ISSUE THREAD

**Issue by BowlesCR** [the-blue-alliance/the-blue-alliance#1223]
Attempting to import match results after Quarterfinals returns an frcundefined error due to Finals schedule being unknown.

Workaround: Manually delete Finals rows from the spreadsheet before importing.

**Comment by phil-lopreiato** [comment]
Hmm, I thought it would only offer to import matches with known scores. Can you post the file?

**Comment by BowlesCR** [comment]
Unfortunately I overwrote it as the day went on... I was able to recreate it manually though:
https://drive.google.com/file/d/0BxwVS9_3ln3IaWEyVUdSX21fUFU/view?usp=sharing

Error message:
![screenshot 1](https://cloud.githubusercontent.com/assets/3699045/8269484/3b2b3b4c-1778-11e5-8eed-f39becf335dc.png)

Debug data with some highlighting of the issue:
![screenshot 2](https://cloud.githubusercontent.com/assets/3699045/8269485/3c719bae-1778-11e5-86c0-88842c46b627.png)

**Comment by phil-lopreiato** [comment]
[This line](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/static/javascript/tba_js/eventwizard_apiwrite.js#L201) should validate 'Red Score' and 'Blue Score' instead. That way, we only try and post matches that have actually been played. Could've sworn we did that already...

**Comment by bdaroz** [comment]
This looks resolved, either in #1228 or #1929 or via the react version.
