### ISSUE TITLE
iframes on API docs page are rendered

### ISSUE THREAD

**Issue by synth3tk** [the-blue-alliance/the-blue-alliance#1225]
But they shouldn't!

![tba-iframe](https://cloud.githubusercontent.com/assets/2099988/8292880/e845ea60-18ff-11e5-8a14-115f5ee80380.png)

**Comment by gregmarra** [comment]
Oh jeez, we should be escaping the display of this for sure, otherwise we're exposing ourselves to XSS attacks.
