### ISSUE TITLE
Event Wizard matches get "messed up"

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1226]
"There is a bug somewhere that causes some of the submitted matches to mess up when you repull the matches on the match play screen. A couple times I had to have one of my students verify all the scores because a couple would be removed or switched around after we left the page and came back to it. We started just opening a new instance to upload the schedules and the ranks, etc."

**Comment by phil-lopreiato** [comment]
That's strange :open_mouth:

**Comment by bdaroz** [comment]
3 Yr old issue w/ no follow-up. Significant changes to event wizard + move to react have likely solved. Reopen if needed.
