### ISSUE TITLE
apidocs test boxes too small

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1229]
Maybe another Firefox specific bug?
![screenshot from 2015-06-22 22-09-25](https://cloud.githubusercontent.com/assets/2754863/8297452/828cccbc-192b-11e5-8330-bc2288a3faab.png)

**Comment by synth3tk** [comment]
No, definitely happens in Chrome.

![tba-apibox](https://cloud.githubusercontent.com/assets/2099988/8297838/f265e476-192e-11e5-870c-e3569a3e13c7.png)
