### ISSUE TITLE
Convert 2015 ranking data to string

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance#1237]
Hey everyone! It looks like event rankings in 2015 returns arrays containing ints/floats, while for every other year it return strings

![screen shot 2015-08-26 at 9 45 31 pm](https://cloud.githubusercontent.com/assets/516458/9510611/d2f3373e-4c3b-11e5-9b70-73ea0d6fb456.png)

vs

![screen shot 2015-08-26 at 9 45 40 pm](https://cloud.githubusercontent.com/assets/516458/9510613/d5ecb096-4c3b-11e5-9950-4aef6569845e.png)

It would be great to get some type safety for this (all) endpoints.

**Comment by fangeugene** [comment]
Must be because 2015 used the FRC API, while the others were parsed from the website where we couldn't guarantee things to be an int (like 11-1-0).

Stringifying everything is the easy solution, int is the cleaner solution. Not sure which to choose.

**Comment by ZachOrr** [comment]
Thinking about this one - I think we should do all strings. All the data from 2014 and back is strings. Also, you have those "Record" fields in some cases, where those fields can't be numbers. Not mix-and-matching data types in those arrays would be awesome.

Right?

**Comment by gregmarra** [comment]
Although arguably record should just be a tuple of ints, as long as there
are never half wins.

**Comment by ZachOrr** [comment]
I  would love if we could format the record upstream and send it in a structured format via the API. So we can avoid doing [this](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/helpers/EventHelper.java#L442) [nonsense](https://github.com/the-blue-alliance/the-blue-alliance-ios/blob/2f637b6572f5f3932db6419d17ebfa670ced32c3/the-blue-alliance-ios/Models/EventRanking.m#L90)

**Comment by fangeugene** [comment]
I'll make everything a string for now, and apiv3 can clean this stuff up.

**Comment by ZachOrr** [comment]
Sorry to bump this, but :)

**Comment by ZachOrr** [comment]
Thanks Eugene! :+1:
