### ISSUE TITLE
Improve Match View (Score Breakdown + Videos)

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1240]
http://www.thebluealliance.com/match/2015hop_qm8

I think videos should go above the breakdown? Or have to click a chevron in order to expand the score breakdown? Or maybe we make it a two-column layout?

There's got to be a better way to organize the content on the match pages.

**Comment by gregmarra** [comment]
I think matches might need to go two columns :)

On mobile, we should definitely make sure videos is above the fold.
