### ISSUE TITLE
http://www.thebluealliance.net/ redirect is broken

### ISSUE THREAD

**Issue by legoktm** [the-blue-alliance/the-blue-alliance#1244]
Unsure if this is related to the HTTPS changes, but:

```
km@km-tp ~> curl -I "http://www.thebluealliance.net/"
HTTP/1.1 301 Moved Permanently
Date: Tue, 08 Sep 2015 09:12:35 GMT
Server: Apache/2.2.25 (Unix) mod_ssl/2.2.25 OpenSSL/1.0.0-fips mod_auth_passthrough/2.1 mod_bwlimited/1.4
Location: http://www.thebluealliance.net/
Content-Type: text/html; charset=iso-8859-1
```

P.S.: https://twitter.com/thebluealliance still links to .net ;-)

**Comment by SUPERCILEX** [comment]
@phil-lopreiato This issue is insanely old so it might as well be closed because no one is really going to go to the `.net` version of TBA. As for Twitter, that discussion has moved to #1847.

**Comment by fangeugene** [comment]
Refer to https://github.com/the-blue-alliance/the-blue-alliance/issues/685#issuecomment-299899909

**Comment by fangeugene** [comment]
We don't care about .net anymore.
