### ISSUE TITLE
Add SSL Notice to apidocs

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1249]
http://www.chiefdelphi.com/forums/showthread.php?p=1495874#post1495874

**Comment by fangeugene** [comment]
Or not redirect /api/* to https

**Comment by gregmarra** [comment]
We should serve the API over HTTPS I think.

@phil-lopreiato want to comment on that thread we've filed an issue?

**Comment by phil-lopreiato** [comment]
I was just writing the reply post :)

**Comment by fangeugene** [comment]
@gregmarra Is there a good reason for serving the API over HTTPS? It's not like any of the data is sensitive, and it's possible some libraries don't support HTTPS.

We just got another email where we probably broke someone's app with HTTPS.

**Comment by gregmarra** [comment]
I feel we should keep everything HTTPS. It's better practice and everyone
will be able to figure it out pretty quickly. Let's add a banner alert to
the top of the apidocs

**Comment by phil-lopreiato** [comment]
Just got a report, Win XP + Chrome no likey SSL :(
https://code.google.com/p/chromium/issues/detail?id=451311

Banner for people to use FF instead?

**Comment by fangeugene** [comment]
No likey this particular version of SSL*

**Comment by gregmarra** [comment]
What do we need to do to make the SSL work for Chrome?

Can you open a separate issue to track this problem? This definitely needs
to be fixed.

**Comment by fangeugene** [comment]
https://github.com/the-blue-alliance/the-blue-alliance/issues/1250

**Comment by bdaroz** [comment]
Can probably close this with PR #1612, don't know what you'd want to do about #1250 though.
