### ISSUE TITLE
SSL breaks GameDay embeds

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1251]
Twitch doesn't do SSL, so neither the videos nor the chat work because of mixed content errors.
Haven't checked Ustream, Livestream, or a generic player.

**Comment by bdaroz** [comment]
Twitch now supports SSL across the board, as does Ustream and Livestream. Should help w/ #1343

**Comment by fangeugene** [comment]
Seems to work now.
