### ISSUE TITLE
Idea: "Smart GameDay" for Champs

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1252]
User selects a set of matches that are "must watch" matches. GameDay automagically switches the stream to these matches when they begin. If no user-specified matches are on, intelligently choose interesting matches (perhaps based on other users' "must watch" matches, potential high score matches, minimize downtime between field resets, etc). If multiple "must watches" are on at the same time, maybe do a split screen.

Clearly more details need to be worked out, and this relies on the FRC API to not go down.

**Comment by nwalters512** [comment]
I love this! This would be useful to users and a fun engineering problem to solve. This could apply to regular events too, not just champs.

**Comment by fangeugene** [comment]
BlueZone exists. Also FIRSTChampLIVE.
