### ISSUE TITLE
Include a confirmation message with copy-pastable summary after making new Write API token

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1253]
As above, so Greg doesn't send people the wrong codes again.

**Comment by phil-lopreiato** [comment]
You mean return a pre-formatted message about what you can do that includes the new code?

**Comment by gregmarra** [comment]
Yea, basically a green box at the top of the page that says "Success!

Here are your Write API keys
Event ID: 2015asdf
Auth ID: asdf
Secret: asdf

You can visit thebluealliance.com/eventwizard for more info."

**Comment by fangeugene** [comment]
We send emails now.
