### ISSUE TITLE
[Offseason Data] SCRRF

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1259]
SCRRF (Fall Classic) - two separate one day events

Day 1: https://www.facebook.com/groups/moardata/1003140419706253/
Day 2: https://www.facebook.com/groups/moardata/1003140729706222/

**Comment by gregmarra** [comment]
Added!

1: http://www.thebluealliance.com/event/2015cafc
2: http://www.thebluealliance.com/event/2015cafc2
