### ISSUE TITLE
DatafeedUsfirstTeamDetails result doesn't match USFIRST site

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1265]
What's going on here?

http://www.usfirst.org/whats-going-on/team/362387?ProgramCode=FRC shows a different team name and nickname than I get when I run http://www.thebluealliance.com/tasks/get/usfirst_team_details/frc5614

![screen shot 2015-10-25 at 10 54 19 pm](https://cloud.githubusercontent.com/assets/57101/10722257/6a7d211a-7b6b-11e5-9706-91048d9074fd.png)
![screen shot 2015-10-25 at 10 54 13 pm](https://cloud.githubusercontent.com/assets/57101/10722256/6a7cc652-7b6b-11e5-9a77-d0aa05b0beb8.png)
![screen shot 2015-10-25 at 10 54 02 pm](https://cloud.githubusercontent.com/assets/57101/10722258/6a7d3ca4-7b6b-11e5-801b-f6f9fcccd8a1.png)

**Comment by popnbrown** [comment]
Weird....
http://www.usfirst.org/whats-going-on/team/347537?ProgramCode=FRC

**Comment by fangeugene** [comment]
Boom fixed. http://www.thebluealliance.com/team/5614
