### ISSUE TITLE
[Offseason Data] 2015 NHBB

### ISSUE THREAD

**Issue by tytremblay** [the-blue-alliance/the-blue-alliance#1269]
2015 Battle of the Bay - Nov 14, 2015

Teams |
----------
2648|
58|
172|
1831|
1729|
131|
501|
1519|
4906|
5122|
238|
4925|
125|
1721|
151|
811|
1922|
3467|
4564|
213|
4546|
5813|
2370|

58 and 3467 will entering second robots, numbers TBD

**Comment by gregmarra** [comment]
@tytremblay were these numbers figured out? Otherwise entered.

http://www.thebluealliance.com/event/2015nhbb
