### ISSUE TITLE
What to do about branding?

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance#1285]
Now that we're spreading out across platforms (iOS and Android, with maybe more to come), I thought it might be time to discuss the TBA branding. On Android, to fit in with Google's style, I designed [a flatter icon](https://github.com/the-blue-alliance/the-blue-alliance-logo/blob/master/android/svg/ic_launcher_blue.svg). We will also need an icon for the iOS app, which is being discussed in [this PR](https://github.com/the-blue-alliance/the-blue-alliance-ios/pull/24). Frankly the classic logo, with all its gradients and skeuomorphic shininess, doesn't feel at all at home on any of the major mobile platforms.

Before brand fragmentation gets out of hand, I think there should be a discussion of how branding is done. Are we OK with multiple styles of the logo, as long as they retail the general "old alliance light" feel? Do we want to adapt a more modern interpretation of the light? Do we want to move to a new branding scheme altogether? Sound off in the comments.

**Comment by fangeugene** [comment]
@gregmarra

**Comment by synth3tk** [comment]
Taking a look through the Windows app store, it seems like most of those are also moving to simple colors with a flatter overall design. I certainly wouldn't be opposed to it in general if only to maintain uniformity.

**Comment by gregmarra** [comment]
I'd support going flat overall. I think our current design is very busy and
hard to reproduce in different media, and we could come up with something
simpler.

I think we should probably stick with the lamp icon, but I think the
Android app does a good job flattening it. We should explore what that
would like on the web, for example.

**Comment by nwalters512** [comment]
Here's a quick and dirty mockup on the website. If we still wanted it to overlap onto the page, I could rerender it with a drop shadow so it would stand out against the white page background.

![](http://i.imgur.com/F6xP8pv.png)

**Comment by phil-lopreiato** [comment]
Just for reference, here's a screenshot from an old branch where I was playing with a material design bootstrap theme. A bunch of the colors are way off, but it could at least spur the imagination into what a flatter TBA would look like
![screenshot from 2015-11-24 21-40-04](https://cloud.githubusercontent.com/assets/2754863/11386948/20537120-92f4-11e5-9032-219d60f1ab14.png)

**Comment by gregmarra** [comment]
I don't think it needs to overlap on the page (easier to deal with if it
doesn't), but I think the weights on the lamp aren't quite right. I think
the cage needs to be heavier, and we should probably reduce the size of the
icon a bit.

I wonder if there are any very graphic-oriented FIRSTers who'd want to
pitch it and make an array of options?

**Comment by nwalters512** [comment]
Yeah, I literally just took the icon that we use for Android notifications and stuck it in the page, we'd have to optimize it for this use case.

Maybe we could crowd-source this effort via the Facebook page?

**Comment by synth3tk** [comment]
I can also make a post on the subreddit.

**Comment by gregmarra** [comment]
Anyone want to take a cut at drawing this? Otherwise we can put up the
bat-signal!

**Comment by synth3tk** [comment]
When can we start using it?

![tba-bad](https://cloud.githubusercontent.com/assets/2099988/11492042/ca9afd54-97b5-11e5-8d7e-0ca87425f694.png)

**Comment by gregmarra** [comment]
Seems pretty legit.

**Comment by SUPERCILEX** [comment]
@phil-lopreiato I believe this issue can be closed as TBA is now well branded.

**Comment by fangeugene** [comment]
I'm mostly happy with the state of branding right now.
