### ISSUE TITLE
Wipe all 2016 EventTeams and reload data from the FMS API

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1289]
https://www.thebluealliance.com/event/2016incmp

Shouldn't have any teams yet, right?

![image](https://cloud.githubusercontent.com/assets/57101/11491542/b72fbd0e-9797-11e5-9f00-7d808e188b2f.png)

**Comment by fangeugene** [comment]
Yeah the FIRST web pages were wrong for a while. We need should wipe all 2016 EventTeams and redo the import from the API.

**Comment by phil-lopreiato** [comment]
Except they haven't populated 2016 events in the API yet, which is really irritating >_<
![screenshot from 2015-11-30 23-09-56](https://cloud.githubusercontent.com/assets/2754863/11492190/92acc844-97b7-11e5-996c-332e62aa4809.png)

Do we need to update the html parsers to handle this situation then?

**Comment by gregmarra** [comment]
Is there an FMS API issue tracker we've filed this against?

**Comment by fangeugene** [comment]
Ugh. Thanks FRIST.

**Comment by phil-lopreiato** [comment]
They weren't very helpful...
https://usfirst.collab.net/sf/discussion/do/listPosts/projects.first_community_developers/discussion.frc_event_api.topc1650

**Comment by gregmarra** [comment]
I get an error at that link, do I have to be signed in to my TeamForge account?

**Comment by fangeugene** [comment]
Yes you do.

**Comment by phil-lopreiato** [comment]
Yeah, maybe. I linked a topic on the Discussions section. Relevant quotes

> Hi Sunny,
Per the error message, the 2016 data will be available once the new season has started (Jan 9th). Some information may 
be populated prior to that time though, depending on availability, as well as some data being populated on the staging 
server before Kickoff.

and

>   Hi Sunny,
If we finish the updates and maintenance we have scheduled on the API prior to Kickoff (both staging and production), 
data would begin to populate. We just aren't guaranteeing anything prior to the official start of the season in January.
Thanks.

**Comment by gregmarra** [comment]
It seems like our options are:

1/ Have partially wrong data until 1/9
2/ Write a new parser to stopgap until 1/9 (and for 2017?)
3/ Have no data until 1/9

**Comment by phil-lopreiato** [comment]
I think that if the new html pages haven't changed too much, we should go with option (2) - the core focus of the site is up-to-date data, so I wouldn't want to sacrifice that. It would also give us a fallback to use in case the API goes down mid-season again (if last year's reliability is anything to go off of, we'll need it. See #1256). 

If that's a massive undertaking, the first fallback would be mix of (1)/(3), where we keep what it is now and clear things based on reports of incorrectness. 

I'll email Alex tomorrow and ask for an ETA on data in the API and see if we can learn anything.

**Comment by gregmarra** [comment]
I went to go look at one of the new pages last weekend, and the content was rendered using Javascript, so will be slightly trickier to scrape. We possibly can find whatever endpoint that Javascript is calling, and directly access the data?

**Comment by synth3tk** [comment]
`http://es01.usfirst.org/teams/_search?size=1&source={%22query%22:{%22query_string%22:{%22query%22:%22_id:301973%22}}}`

301973 is the unique ID for the team (in this case, it's team 245). [Response is like this](http://pastebin.com/FeunpE60).

**Comment by phil-lopreiato** [comment]
Here's Event Info: `http://es01.usfirst.org/events/_search?size=1&source={%22query%22:{%22query_string%22:{%22query%22:%22_id:17323%22}}}` ([response](http://pastebin.com/B6KXCVp2))

And EventTeams: `http://es01.usfirst.org/teams/_search?size=100&source={%22sort%22:[{%22team_number_yearly%22:{%22order%22:%22asc%22}}],%22query%22:{%22query_string%22:{%22query%22:%22events.fk_events:17323%20AND%20team_type:%20FRC%20AND%20profile_year:2016%22}}}` ([response](http://pastebin.com/J7s4g7fR) - includes teams, every award they won, ever, and every event they attended, ever. Woah - 172kb in response data).

Event Listing: `http://es01.usfirst.org/events/_search?size=100&source={%22query%22:{%22query_string%22:{%22query%22:%22(event_type:FRC)%20AND%20(fk_program_seasons:221)%20AND%20date_end:[2015-12-01%20TO%202016-12-01]%22}}}` ([response](http://pastebin.com/yRX4q5ru) - to get Event IDs)

This actually doesn't seem like too bad a fallback plan

**Comment by synth3tk** [comment]
Don't know why I posted the team info in a thread about events. Anyway, this definitely looks like a solid fallback, assuming the URL structure doesn't change too much, and I don't think it will since it's used in prod on their own site.

**Comment by fangeugene** [comment]
Using undocumented APIs. Sounds great.

**Comment by gregmarra** [comment]
Technically scraping html is using an undocumented API also :)

**Comment by fangeugene** [comment]
touche

**Comment by phil-lopreiato** [comment]
There is some data in these endpoints not exposed in the API that we can also use:

Event Details:
 - Event Website
 - Venue address
 - Total capacity
 - Open spots remaining

Team Details:
 - Team motto


We could also pull the full award/event history from the Team details and verify our own archives. It seems to go back fully to about 2003 and is hit or miss before that

**Comment by fangeugene** [comment]
I think this should be fixed now.

**Comment by gregmarra** [comment]
Should we close this issue?
