### ISSUE TITLE
NE District - Rhode Island Event 2016 has wrong teams!!

### ISSUE THREAD

**Issue by fredghostkyle** [the-blue-alliance/the-blue-alliance#1291]
http://www.thebluealliance.com/event/2016ripro

These teams are not participating in this compition. I've check the FIRST website and they are not listed on there.

**Comment by phil-lopreiato** [comment]
Thanks for the report, this is caused by FIRST's recent website changes, we're working on a fix. 

See https://github.com/the-blue-alliance/the-blue-alliance/issues/1289

**Comment by fredghostkyle** [comment]
See #1289
