### ISSUE TITLE
Remove extraneous whitespace from API responses

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance#1297]
Including whitespace in API responses does make it *slightly* easier to read the responses as a human, but any good client-side JSON parser will just ignore that whitespace. For some of the bigger responses, such as team list, removing extraneous whitespace can shave almost 5kB off the response. That's not much, but that's a very easy optimization to make, and every little bit of data saved helps for mobile devices.

For an example of what I'm talking about, compare

```json
[{"team_name": "wildstang", "team_number": 111}, {"team_name": "wildstang", "team_number": 111}]
```
to
```json
[{"team_name":"wildstang","team_number":111},{"team_name":"wildstang","team_number":111}]
```

**Comment by phil-lopreiato** [comment]
Should be doable with a tweak to `json.dumps`

http://stackoverflow.com/questions/16311562/python-json-without-whitespaces

**Comment by fangeugene** [comment]
With GZIP the whitespace shouldn't make a difference. We should check that things are properly being gzipped.

**Comment by nwalters512** [comment]
Ah, I wasn't aware it was being gzipped. I just looked at the response in Chrome and saw whitespace. I should've investigated that further.

**Comment by nwalters512** [comment]
Content-Encoding of the response is indeed gzip.

I also did some testing, gzipping of whitespace vs no whitespace is only a difference of about 0.5% for a team list response. This should be a non-issue then.
