### ISSUE TITLE
Add Admin Message to API Status Endpoint

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1303]
Will allow us to write a custom message (with expiration date) to the app somehome. Basically, this is the server side component for https://github.com/the-blue-alliance/the-blue-alliance-android/issues/418

Extends #1256 to also add `text` and `expiration` (UNIX timestamp, seconds since epoch) to the response, inside a sub-dict `message` (or `null` if no message available). Both will be input from `/admin/apistatus` and stored with the other data in the sitevar. 

```
{
  max_season: 2015,
  is_datafeed_down: false,
  android: {
    min_app_version: 123456
  },
  ios: {
    min_app_version: 1243
  },
  down_events: [
    2015test,
    2015down
  ],
  message: {
    "text": "blah",
    "expiration": 123456
  }
}
```

**Comment by fangeugene** [comment]
So are we removing the existing admin GCM push?

**Comment by phil-lopreiato** [comment]
Yes, I think this approach is much more reliable. Mainly for devices that miss gcm messages, installs after we do the push, people without myTBA, etc. 

Maybe we want to keep the gcm push for lower priority message, or transform it into a send-to-sync message for status endpoint.

**Comment by fangeugene** [comment]
I agree. I can't think of many things we want to push, only things we want to show while a user is running the app (FIRST is down).

The one thing we may want to push would be that FIRST/an event is down if a user is signed up for push notifications. They may wonder why they aren't getting any notifications and shouldn't have to open the app to discover why. These devices are already set up with GCM.

**Comment by nwalters512** [comment]
The best hybrid approach here is probably to just send a tickle message to registered devices telling them "hey, something in the status API has changed" so they will immediately fetch the new status.

**Comment by phil-lopreiato** [comment]
As implemented in https://github.com/phil-lopreiato/the-blue-alliance-android/commit/9659ba1fd9b2087dc402aae46d90ca4344b4e41d, here's what the two new gcm notifications look like:

Sync Status
type: `sync_status`
body:
```
{}
```

Event Down:
type: `event_down`
body:
```
{
  "event_key": "2015down",
  "event_name": "Down Event"
}
```

**Comment by nwalters512** [comment]
Is there any reason to have an "event down" push? Why not just send a tickle and have each device hit the status API?

**Comment by phil-lopreiato** [comment]
Honestly, just because it's easier to integrate on the server side (fewer queries, simpler flow). It's more straightforward to parse mytba subscriptions (because we'll only send this message to users who are subscribed to the down event) on the server. And we won't have to worry about clients being out of date, etc.

**Comment by nwalters512** [comment]
Ok, that makes sense. I was just curious. We'll have to make sure we handle the edge case where a user is offline while an "event down" push is sent and then comes back online when the event is working again, either by cancelling the pending push or hitting the status API to verify the push is current and correct. Or something like that.

**Comment by bdaroz** [comment]
Bumping for v3 discussion re #1507 - do we want to add an admin message component to the `status` endpoint, or perhaps this can be closed?

**Comment by bdaroz** [comment]
Closing - if this isn't cooked in it's moot now with all the push data updates
