### ISSUE TITLE
Preflight Errors

### ISSUE THREAD

**Issue by chacha** [the-blue-alliance/the-blue-alliance#1312]
Currently trying to design a simple JS API for our team to look at TBA data programatically. However, I keep failing the preflight checks for making an XHR request via Javascript.

The headers being sent during preflight to `https://www.thebluealliance.com/api/v2/team/frc3128` are:

    accept:*/*
    accept-encoding:gzip, deflate, sdch
    accept-language:en-US,en;q=0.8,es;q=0.6
    access-control-request-headers:x-tba-app-id
    access-control-request-method:GET
    origin:http://nar.dev
    referer:http://nar.dev/
    user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

Any thoughts on what might be going wrong?

**Comment by fangeugene** [comment]
I think you need to set an X-TBA-App-Id. The format is documented at
www.thebluealliance.com/apidocs

**Comment by chacha** [comment]
@fangeugene I have the X-TBA-App-Id set. That is why the `access-control-request-headers` key is set to `x-tba-app-id`, as it is telling the server that I will be sending it on the real request (documented in CORS [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)). 

For some reason, even though I am adding that header, the server still is not responding with the correct access origin headers.

**Comment by fangeugene** [comment]
Not sure what the problem is here. What does the server return when you make the request?

**Comment by chacha** [comment]
The script can't get past the preflight because the server isn't responding with the correct accept origin header to my request. Its weird because this is all standard XHR Javascript request stuff.

**Comment by phil-lopreiato** [comment]
Looks like we have to implement the `options` method in the API Controller in order to respond with what requests are allowable. There's a [webapp callback](https://cloud.google.com/appengine/docs/python/tools/webapp/requesthandlerclass#RequestHandler_options). The [docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests) have an example

**Comment by chacha** [comment]
Currently I've fallen back to using the [parameter method](https://github.com/Team3128/tba-analysis/blob/performance-stats/api-thebluealliance.js#L313), but the header option would be a much more attractive option.

**Comment by phil-lopreiato** [comment]
Can you try and hit http://tba-dev-phil.appspot.com instead as a test? It's my own instance of TBA that I've deployed with [this commit](https://github.com/phil-lopreiato/the-blue-alliance/commit/694b37ac95c0497c3a6272a6096f34496e488b86), which will hopefully accept the `OPTIONS` method. If there any others I've missed, let me know

Here's a full request/response when I hit something running that commit:
```
curl -v -X OPTIONS http://localhost:8088/api/v2/events/2016
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8088 (#0)
> OPTIONS /api/v2/events/2016 HTTP/1.1
> Host: localhost:8088
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< access-control-allow-headers: X-TBA-App-Id
< pragma: Public
< cache-control: public, max-age=61
< access-control-allow-origin: *
< access-control-allow-methods: GET, OPTIONS
< content-type: application/json; charset="utf-8"
< Content-Length: 0
< Server: Development/2.0
< Date: Fri, 18 Dec 2015 17:52:13 GMT
< 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host localhost left intact
```

**Comment by chacha** [comment]
I hit your sever several times and it looks like we are good to go.

**Comment by fangeugene** [comment]
@phil-lopreiato if you PR it i'll deploy it.

**Comment by phil-lopreiato** [comment]
https://github.com/the-blue-alliance/the-blue-alliance/pull/1314

**Comment by fangeugene** [comment]
Deployed on production. @chacha give it a go?

**Comment by chacha** [comment]
@fangeugene Tested. It works. Thanks!

**Comment by phil-lopreiato** [comment]
Glad to hear it!
