### ISSUE TITLE
Integrating a youtube playlist splitter

### ISSUE THREAD

**Issue by anlsh** [the-blue-alliance/the-blue-alliance#1316]
[I wrote a program](https://github.com/pipsqueaker/PlaylistSplitter) to automatically split long youtube playlists and submit the videos to their corresponding pages on TheBlueAlliance. However I have no idea how to integrate it with the website itself, so could someone do that for me?

The readme on the repo I linked is a bit long, but it should contain all the needed info to test and integrate the script.

**Comment by jaredhasenklein** [comment]
I believe that support for this was added in #1719 with the creation of [`templates_jinja2/suggestions/suggest_match_video_playlist.html`](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/templates_jinja2/suggestions/suggest_match_video_playlist.html) and the issue should be closed. If there's functionality I'm not seeing, though, let me know.
