### ISSUE TITLE
api/v2/districts/2014 returns an HTTP 500 error

### ISSUE THREAD

**Issue by synth3tk** [the-blue-alliance/the-blue-alliance#1323]
This seems to be the only year that does it. All previous and later years are fine.

![image](https://cloud.githubusercontent.com/assets/2099988/12080440/13746dda-b228-11e5-8597-c141a18992a5.png)

**Comment by phil-lopreiato** [comment]
@fangeugene can you check the logs and see what the error is?

**Comment by fangeugene** [comment]
Some 2014 event district types got nuked. Not sure why. Kind of concerned.

**Comment by fangeugene** [comment]
500 error is fixed though.
