### ISSUE TITLE
Team average scores

### ISSUE THREAD

**Issue by mastercoms** [the-blue-alliance/the-blue-alliance#1327]
The api doesn't allow access to team's average qualifying and elimination scores

**Comment by phil-lopreiato** [comment]
Qual average can be found in the event rankings request (see [docs](http://www.thebluealliance.com/apidocs)).

You are correct that playoff round averages are not exposed, but you can calculate it yourself easily by fetching the playoff matches and doing some quick math.

**Comment by mastercoms** [comment]
Ok, thanks!
