### ISSUE TITLE
broadcast notifications don't work

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1330]
I attempted to send one this morning, and did not receive it on my Android device.

**Comment by gregmarra** [comment]
Error from logs:

```
400, Invalid GCM JSON message: '{"data": {"message_data": {"url": "http://www.thebluealliance.com", "desc": "Watch live at thebluealliance.com/gameday#kickoff . Join the pre-kickoff chat as \\u201cFIRST Stronghold\\u201d is unveiled!", "title": "Kickoff starts shortly!!"}, "message_type": "broadcast"}, "registration_ids": [<snip>...(length 669105)
```

**Comment by gregmarra** [comment]
Also webhooks failed in parallel:
* `Other Exception: An error occured while connecting to the server: Unable to connect to server at URL: https://riptiderobotics.com:3000/api/game/55359dbd1ead7c4f6841b460/TBA/hook`

**Comment by bdaroz** [comment]
Is this a one-off? Reopen if it's still happening please.

**Comment by ZachOrr** [comment]
I’ll make sure broadcast notifications work during the TBANS migration
