### ISSUE TITLE
Make an easy paver deploy script

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1333]
The AppEngine GUI no longer works, so we need a manual deploy script.

**Comment by gregmarra** [comment]
@fangeugene is your script already in paver? I think you're the only one who can deploy until we fix this.

What are the set of steps we need it to do? What parts are missing from the GUI?

**Comment by fangeugene** [comment]
Check out `deploy.py` The thing is that `APP_CFG_DIR` may not be the same for everyone. The GUI doesn't handle modules properly.

**Comment by phil-lopreiato** [comment]
As another point of reference, here's the basic script I use to update my dev instance: https://gist.github.com/phil-lopreiato/2949eaa26a154caf9c58

**Comment by bdaroz** [comment]
T believe this is resolved with the `vagrant` and `paver` scripts.
