### ISSUE TITLE
UNH District Event missing from TBA

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1337]
http://www.firstinspires.org/team-event-search/event?id=17459

Why wasn't it scraped?

**Comment by fangeugene** [comment]
http://www.thebluealliance.com/event/2016nhdur

?

**Comment by gregmarra** [comment]
Nevermind I'm just bad at searching >.<

**Comment by fangeugene** [comment]
Way to waste issue number 1337
