### ISSUE TITLE
Import Old Alliances

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1345]
I wrote some hacky scripts to parse alliances out of old CD threads. Alliance data is a prerequisite for #1342, so we'll need this before that gets run. Hopefully its **mostly** accurate, but since its not from an official source there may be typos.

Each file is a json dict with the event key mapping to the json alliance object for TBA.

https://gist.github.com/phil-lopreiato/08c302070e12e59ced34

**Comment by fangeugene** [comment]
Thanks that was painless. They should all be in.
