### ISSUE TITLE
Repair 2010ct data

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1346]
It seems to be missing rankings and awards, I grabbed them from archive.org (https://web.archive.org/web/20100405222040/http://www2.usfirst.org/2010comp/events/CT/rankings.html) and ran the html through an old checkout of the parsers. Hopefully it should be importable.

https://gist.github.com/phil-lopreiato/c1e615148d77be6832d0

**Comment by fangeugene** [comment]
Done.
