### ISSUE TITLE
What data will be available from matches in the API this year?

### ISSUE THREAD

**Issue by weaversam8** [the-blue-alliance/the-blue-alliance#1357]
Is this something that TBA would make a decision, or is this dependent on what information _FIRST_ makes available?

Specifically, I am curious if we will be able to programmatically retrieve the defense setup for a match.

I hope this isn't the wrong place, if so, point me in the right direction please...

**Comment by fangeugene** [comment]
The match details will be the same that FIRST documents here: http://docs.frcevents2.apiary.io/#reference/match-results/score-details

**Comment by phil-lopreiato** [comment]
@fangeugene got the list of properties, but it's also good to note that FIRST won't make the defense configuration available before a match is played. It'll be posted along with the score

**Comment by weaversam8** [comment]
Awesome guys, thanks!
