### ISSUE TITLE
404 on Team Page URL

### ISSUE THREAD

**Issue by flamespinner** [the-blue-alliance/the-blue-alliance#1358]
When I click on the Team Website URL on team pages it gives me a 404 because it can not find the page at https://www.thebluealliance.com/team/www.2491nomythic.com because its trying to redirect me to a blue alliance page still instead of www.2491nomythic.com

**Comment by phil-lopreiato** [comment]
#1341 is the fix for this, is just needs to be merged in

**Comment by flamespinner** [comment]
Awesome! Thanks!
