### ISSUE TITLE
TBA hosts team media?

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance#1362]
Way back when we did the [Android hackathon](https://github.com/the-blue-alliance/the-blue-alliance-android/issues/94) last summer, one of the suggestions was to "Take photos/videos on device, submit to TBA for team/match media." I still love this idea: it would significantly reduce the friction necessary to get photos of robots on the site and I think we'd see a lot more submissions.

The problem with this is that we currently rely on third parties to host media; namely Chief Delphi and YouTube. I think it makes sense to keep hosting videos on YouTube; no issues there. However, by relying on CD for photos, that makes it impossible to have this sort of simple upload flow that we'd want. Is it feasible for TBA to host media directly, thus enabling this kind of feature?

**Comment by phil-lopreiato** [comment]
This might be a time to break out an old PR: https://github.com/the-blue-alliance/the-blue-alliance/pull/976 (imgur support for images)

We could have the app take pictures and upload to imgur (basic example: https://github.com/AKiniyalocts/imgur-android) and only allow suggestions from imgur via the app. We'd add the suggestion via authenticated cloud endpoints to ensure that.

That gives the app an upload vector, prevents users from spamming images from imgur that weren't app-uploaded, and still lets TBA avoid paying image hosting costs.

**Comment by nwalters512** [comment]
That looks like a nice option. I definitely think authentication is key, we don't want people spamming the site with images. If you can finish building out the backend, I can put a nice frontend on this in the app.

**Comment by phil-lopreiato** [comment]
@fangeugene, @gregmarra This idea seem okay to you?

**Comment by gregmarra** [comment]
I love the idea of making it easy to add robot images. I'd prefer to continue to use external image hosts, because I don't want to deal with issues like copyright. We haven't had spam issues with any of the other suggestion flows, but I think an all in one "upload to imgur and suggest for team" flow is pretty nice.

**Comment by fangeugene** [comment]
I like this idea as well. Spam isn't too big of a concern because we can just flag an account, and like Greg said we haven't had any huge issues so far (even for YouTube vids). Also, once we get account permissions so we can have more mods, it may be even less of an issue.
