### ISSUE TITLE
"Team year" endpoint

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance#1363]
I'm going back and tackling old Android issues. For https://github.com/the-blue-alliance/the-blue-alliance-android/issues/112 (Team details view changes for more glancability), it would be really helpful to have an endpoint describing a team's performance during a specific year. I would envision the endpoint being something like

```
/api/v2/team/frc254/2014
```

It could return things like overall record for the season, number of blue banners, etc. It would be feasible to do this without the extra endpoint (just fetch the event list, then each individual event), but it would be significantly easier to simply have a single endpoint to hit for this data.

**Comment by phil-lopreiato** [comment]
So this would return:
 - Overall Record
  - For 2015, return qual/playoff averages instead
 - events competed in (do we return the whole dict? a subset?)
 - Awards won

Anything else?

**Comment by nwalters512** [comment]
That's all I can really think of at this point. This seems to be pretty much a "team events" on steroids.

**Comment by bdaroz** [comment]
Bumping for discussion for v3 in #1507

**Comment by bdaroz** [comment]
To a lesser extent this can be done in v3 with a few calls.
