### ISSUE TITLE
Team Data Not Getting Updated

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1365]
Source: https://www.facebook.com/groups/moardata/permalink/1062997170387244/

The current page for team 4488 has a typo in their robot name, but it's since been fixed in the TIMS/FRCAPI. Since FRCAPI has the highest datafeed priority, the Robot model should be getting updated every run of the cronjob.

Things to investigate:
 - Is the cronjob actually running (it's scheduled to be run daily)
 - Is proper data being returned
 - Are updated models being written?

This is where #1360 would come in handy

Here's the relevant API response:
```
➜  phil@fedora-desk ~  frc-api https://frc-api.firstinspires.org/v2.0/2016/teams\?teamNumber=4488
HTTP/1.1 200 OK
Cache-Control: public, max-age=300
Content-Length: 546
Content-Type: application/json; charset=utf-8
Date: Wed, 17 Feb 2016 02:59:32 GMT
Last-Modified: Mon, 15 Feb 2016 08:00:31 GMT
Server: Microsoft-HTTPAPI/2.0

{
    "pageCurrent": 1,
    "pageTotal": 1,
    "teamCountPage": 1,
    "teamCountTotal": 1,
    "teams": [
        {
            "city": "Hillsboro",
            "country": "USA",
            "districtCode": "PNW",
            "nameFull": "Lam Research / Intel Corp. / Hillsboro School District / Boeing Corportation / Entro Industries / Oregon Department of Education / Profacture / Legacy Semiconductor / Hillsboro Optimists / Valley Machine / Hoffman Construction & Glencoe High School",
            "nameShort": "Shockwave",
            "robotName": "Solar Flare ",
            "rookieYear": 2013,
            "stateProv": "Oregon",
            "teamNumber": 4488,
            "website": "http://glencoerobotics.com/"
        }
    ]
}
```

**Comment by phil-lopreiato** [comment]
Wait, I see the `Last-Modified` header is set to yesterday, so maybe the cronjob just hasn't run to update it yet.

**Comment by fangeugene** [comment]
Another thing, I dont think we ever hit the team API, only the event teams API. Can you check if that returns the correct info?

**Comment by phil-lopreiato** [comment]
Yeah, that endpoint has the same (correct) robot name. And it also has the same `Last-Modified` time

**Comment by fangeugene** [comment]
Fixed in https://github.com/the-blue-alliance/the-blue-alliance/commit/2c231277e8bf8cbbe3f99f64a04cd9c0775431a9

**Comment by fangeugene** [comment]
Wasn't too hard to track down. Just need to check the error logs more frequently...

**Comment by gregmarra** [comment]
Is there a way we can set a bot up to ping slack when we have big errors?

**Comment by phil-lopreiato** [comment]
Google Cloud Monitoring can send slack notifications. I'll break it off into a new issue to discuss what to enable
