### ISSUE TITLE
Show Preseason Events on Build Season homepage

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1366]
Two events this weekend, we should show them on homepage.

Should audit that they work in gameday.

**Comment by fangeugene** [comment]
Add add them as events. I will add the FIRST official one once it shows up on their API.

**Comment by phil-lopreiato** [comment]
Here are the details for Suffield Shakedown

http://www.aceshigh176.org/ss-scrimmage
team list: http://www.chiefdelphi.com/forums/showpost.php?p=1532198&postcount=8

**Comment by phil-lopreiato** [comment]
And official week 0 will be streamed from Gamesense's twitch channel

http://www.chiefdelphi.com/forums/showpost.php?p=1541879&postcount=33

**Comment by gregmarra** [comment]
We've got week zero set with it's webcast.

I'll make Suffield Shakedown.
