### ISSUE TITLE
Connect Monitoring to Slack

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1368]
Broken off from #1365, @gregmarra @fangeugene 

Google Cloud Monitoring can integrate with Slack, so we can post to a channel when certain events happen:
https://support.stackdriver.com/customer/portal/articles/1750158-integrating-with-slack

Use this issue to discuss what kind of monitoring thresholds we should set up:
 - Lots of 4XX or 5XX responses. I think we want a rate of change threshold here
 - Lots of logging.error messages. Maybe also rate of change?

We can also track tons of other metrics, like datastore operations, memcache operations, cached responses, CPU usage, network traffic, etc.

You can create policies in the App Engine Console, under "Monitoring" and connect slack there.

**Comment by phil-lopreiato** [comment]
We can also connect Google Analytics (daily reports, user activity, etc): http://alerts.ryanbrink.com/

**Comment by gregmarra** [comment]
Oh sweet. This is exciting

**Comment by phil-lopreiato** [comment]
Is there anything else you'd want to monitor via slack?

You or Eugene will have to add this through the app engine dev console

**Comment by fangeugene** [comment]
I can't. Owners only.

**Comment by gregmarra** [comment]
I get this error after logging in after clicking the link in the linked Stackdriver page. Stackdriver's main page says "14 day free trial" – does this work the way we want it to?

![image](https://cloud.githubusercontent.com/assets/57101/13198516/70033402-d7bf-11e5-99c7-54ec0ac72071.png)

**Comment by gregmarra** [comment]
Set up the GA monitoring. Site costs $10/year if we like it we can turn it on.

**Comment by gregmarra** [comment]
@phil-lopreiato  and I compared screenshots, and he has different options in Stackdriver than I do, which is a problem since I am the project owner? I posted in the Stackdriver help forum asking for clarification on what to do. Not sure if I'll learn what's up.

**Comment by gregmarra** [comment]
The page works for me now, I will try setting this up tonight

**Comment by gregmarra** [comment]
Got this set up for 500 errors.

![image](https://cloud.githubusercontent.com/assets/57101/13486607/51420e24-e0c7-11e5-8913-9718e150d505.png)

**Comment by phil-lopreiato** [comment]
Nice!
