### ISSUE TITLE
Deleting media doesn't clear cache of team pages

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1392]
1. removed media from team 610 via admin tool
2. shows as removed in admin tool
3. still shows on /team/610

expected result
1. /team/610 should have had cache cleared
2. /team/610/2016 should have had cache cleared

**Comment by fangeugene** [comment]
We don't bust caches for any html pages except for those with webcasts. Everything else is on a timer. 5 minutes for teams and events that are ongoing, 1 day otherwise.
