### ISSUE TITLE
District Elimination points calculation error

### ISSUE THREAD

**Issue by jgrimm74** [the-blue-alliance/the-blue-alliance#1396]
It appears that winning alliances who had a tie match in eliminations are receiving an extra 5 district points. They are getting 5 points for each match they competed in during eliminations rather than 10 points for a win in the series. 

3 cases in this example: 

Example: [https://www.thebluealliance.com/event/2016waspo#district-points](https://www.thebluealliance.com/event/2016waspo#district-points) 

![image](https://cloud.githubusercontent.com/assets/10381902/13561378/3ae7a464-e3e1-11e5-95b6-caffa3aa1088.png)

2147 5450 and 4495 are all inaccurate. They had tiebreakers in both quarters and semis, however 4495 was a backup robot who came in for match 2 in quarters, after that alliance lost match 1.  2147 and 5450 thus each had 6 wins and 2 losses, whereas 4495 had 6 wins and 1 loss. All 3 teams should have 30 elimination points (10 points for each series), However 2147 and 4450 have 40 and 4495 has 35 - thus it appears to be calculated as 5 * number of matches competed in.

Additionally 4082 which is the robot replaced in match 1, Participated in one match in that quarterfinals round. However they are listed as having 5 points. I believe since they competed in that round they should receive 10 elimination points. 

This does not seem to match the game manual 7.4.1.3: 

> All Teams on the Alliance winning a particular playoff series, who participate in matches with their
robots, receive 5 points per match won. In most cases, this will usually mean Teams will receive 10
points at each of the Quarter Final, Semi-Final, and Final levels, unless a backup robot is called in to
play

**Comment by fangeugene** [comment]
Thanks for catching this. We will work on a fix.

**Comment by fangeugene** [comment]
This look better?

![image](https://cloud.githubusercontent.com/assets/1421884/13576503/0635a57e-e45c-11e5-9ea8-194b19a51e21.png)

**Comment by jgrimm74** [comment]
Looks perfect now. Sorry for the late reply I was getting confirmation that the backup robot points are being applied correctly on TBA. Based on my review the backup robot situations are scoring properly now as well. 

Good job and thank you ;-)

**Comment by fangeugene** [comment]
Great, thanks for the verification!
