### ISSUE TITLE
Add support for Twitter Summary Cards

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance#1400]
We already provide metadata for the Open Graph Protocol as used by Facebook. We can add a few more tags to the headers to get a nice summary card in tweets with TBA links:

https://dev.twitter.com/cards/types/summary

Now that we're getting more serious about robot images, we could even change the headers to use said robot images as the image metadata for year-specific team pages.

**Comment by gregmarra** [comment]
Ohh yea, we should use media for the og: tags on Facebook, too! Great idea.

**Comment by nwalters512** [comment]
Something to keep in mind for images on Twitter:

> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages.
> 
> The image must be a minimum size of 120px by 120px and must be less than 1MB in file size. The image will be cropped to a square on all platforms.

This is easy enough to accomplish on Imgur with their thumbnail generation API: https://api.imgur.com/models/image#thumbs. Not so much with CD photos. We'd have to prefer Imgur photos, and if we only have Chief photos, stick one in the image tag and hope it's not too big :smile: 

Facebook's restrictions are much looser:

> Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images. Images can be up to 8MB in size.
> ...
> The minimum image size is 200 x 200 pixels. If you try to use an image smaller than this you will see an error in the URL Debugger.

**Comment by synth3tk** [comment]
This has been implemented.
