### ISSUE TITLE
Implement "Preferred" Robot Images

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1401]
This will allow us to accept a wider variety of images, but set a few (up to 3?) "Preferred" ones that are clear images of the robot that we can use at the top of Team pages and in the Team list for Event pages to ease in scouting. This way a team's images won't be cluttered with "irrelevant" images in terms of scouting. We can also use these Preferred images for stuff like #1400 

Reviewers choose the Preferred image when reviewing. The interface would be something along the lines of "Choose the image to replace" if 3 are already filled, or if not all 3 are filled then a simple "add".

Reviewing of Video and Photo media should also be separated, to reduce mental load on the reviewer.

**Comment by gregmarra** [comment]
Alternatively some media could be marked as "social" vs "robot"?

**Comment by fangeugene** [comment]
Not a bad idea.

**Comment by fangeugene** [comment]
What about bad robot photos though? Should we have have some standard of quality?

**Comment by nwalters512** [comment]
I still think tagging some as "preferred" is a good idea. For some teams, the only submissions we get might be a slightly blurry phone pic from a competition. We'd probably still want to accept and display that pic. Some teams might have a combination of professional DSLR and blurry phone pics; I think we definitely want a way to tag and give display preference to the "good" pic without categorically rejecting anything that isn't a flawless image.

**Comment by fangeugene** [comment]
I like the idea of top X preferred per year per team. We can do that with the current model.

**Comment by fangeugene** [comment]
Okay so to be more clear, what if we have top 3 preferred per team per year that show up in the carousel at the top of team pages and in the team list on event pages. Then all other images can be at the bottom of the Team pages  (but perhaps more spatially condensed as to not get obtrusive). Not sure how we can condense videos though (I've seen teams with 8+ videos because of weekly build blogs, etc).

Thoughts on this? Where does this leave us in terms of approving images such as a trophy on a table or team logos?
