### ISSUE TITLE
Looking for work

### ISSUE THREAD

**Issue by csteward24** [the-blue-alliance/the-blue-alliance#1403]
Hi, I'm Christian, avid robot programmer. I'd like to help out with TBA. Could someone please point me in the right direction to get started?

**Comment by phil-lopreiato** [comment]
Hey there!

Step 1 to contributing is to get a local dev server set up. There are instructions in the readme: https://github.com/the-blue-alliance/the-blue-alliance/blob/master/README.md

**Comment by synth3tk** [comment]
Once you have the server up and running, here are a list of issues that should be fairly simple to jump into:
https://github.com/the-blue-alliance/the-blue-alliance/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22

Any issue with the green "Help Wanted" label are tagged so that anyone new to TBA or coding can get started.

**Comment by csteward24** [comment]
When I installed the app engine it didnt ask me to make symbolic links. Is this a problem?

**Comment by phil-lopreiato** [comment]
> When I installed the app engine it didnt ask me to make symbolic links. Is this a problem?

I don't think so

**Comment by csteward24** [comment]
Should I install Node.js 4 or 5?

**Comment by csteward24** [comment]
I got this error when trying to run the dev server:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\dev_appserver.py", line 83, in <module>
    _run_file(__file__, globals())
  File "C:\Program Files (x86)\Google\google_appengine\dev_appserver.py", line 79, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 1040, in <module>
    main()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 1033, in main
    dev_server.start(options)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 758, in start
    options.config_paths, options.app_id)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\application_configuration.py", line 831, in __init__
    module_configuration = ModuleConfiguration(config_path, app_id)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\application_configuration.py", line 127, in __init__
    self._config_path)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\application_configuration.py", line 423, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: 'dispatch.yaml app.yaml app-backend-tasks.yaml'
2016-03-09 16:24:14 (Process exited with code 1)

**Comment by phil-lopreiato** [comment]
Add the `dev_appserver.py` script to your system `PATH` variable and run it from within the `the-blue-alliance` directory. Alternatively, pass the fully qualified path (starting with `C:\`) for each of the `.yaml` files

**Comment by csteward24** [comment]
this is my path:
C:\Program Files (x86)\Google\google_appengine\dev_appserver.py

and these are my flags:
app.yaml app_shared.yaml app-backend-tasks.yaml bulkloader.yaml cron.yaml dispatch.yaml index.yaml queue.yaml .travis.yml

what am I doing wrong?

**Comment by phil-lopreiato** [comment]
What directory are you in while running the devserver?

If you are in `the-blue-alliance`, run `C:\Program Files (x86)\Google\google_appengine\dev_appserver.py dispatch.yaml app.yaml app-backend-tasks.yaml`

**Comment by csteward24** [comment]
Just to clairfy, should I be running this is powershell? Because its getting hung up on parsing the filepath when i run that command. btw, yes im running it from C:\Users\Christian\Documents\GitHub\the-blue-alliance

thank you for your help and patience, im new at this

**Comment by phil-lopreiato** [comment]
I think you should use cmd, but I don't run windows so I can't say specifically. [This page](https://cloud.google.com/appengine/docs/python/tools/devserver) has the docs for the devserver

**Comment by csteward24** [comment]
THANK YOU
The path worked when I used cmd

**Comment by phil-lopreiato** [comment]
Nice! You should be able to get to an instance of TBA using your web browser. @fangeugene what's the best way to populate it these days?

**Comment by fangeugene** [comment]
Hm I'll have to think about that. There actually may not be a good way right now if you don't have a FRC API key. There's an easy way to populate it with event data (matches, rankings, alliances, everything you want), but it requires you to know the events first.

**Comment by phil-lopreiato** [comment]
Can we do csv imports from https://github.com/the-blue-alliance/the-blue-alliance-data?

**Comment by fangeugene** [comment]
That's what the thing I mentioned does, but it only knows where to look for the details (matches, rankings, etc.) if you already have Events in the database. I think I took out all of our old datafeeds (HTML scrapers).

If you don't care about having real data, and just want some fake teams and events to play with, you an go to localhost:<port>/admin/ and on the top right click the buttons for "Create Test Teams" and "Create Test Events."

**Comment by seldenr** [comment]
It's also not too difficult to get an FRC api key. I applied for one for team projects, and got one very quickly.

**Comment by phil-lopreiato** [comment]
Glad to hear it! We also broke improving the initial data loading out into #1433, so we can hopefully improve that soon. 

Is there anything else we can help you with?

**Comment by SUPERCILEX** [comment]
@phil-lopreiato Since this is an old issue that seems to be resolved, I believe it can be closed.
