### ISSUE TITLE
Print when insights were last updated

### ISSUE THREAD

**Issue by chacha** [the-blue-alliance/the-blue-alliance#1411]
Somewhere on the place we should list the last time the insights stats were actually updated. Currently the page simply lists that it updates `nightly`, which is not specific. Giving the most recent timestamp would give users a better sense of what data has been included in it.

**Comment by nwalters512** [comment]
This would also be valuable for international users, where "nightly" wouldn't necessarily line up with what we mean by that (night in the US).
