### ISSUE TITLE
Disable response output for taskqueue tasks

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1413]
Apparently responses from task queues use up bandwidth quota.

20 events of fully populated matches (~300KB each) every minute = 8 gigs a day and is killing our bandwidth quota.

https://cloud.google.com/appengine/docs/python/taskqueue/overview-push#Python_Quotas_and_limits_for_push_queues

I thought something was funny about our bandwidth usage. For example on 3/13 CloudFlare saw 9GB and over 5 of that was cached. But GAE said we used 14.5 GB and still said we had high bandwidth usage at night even though the number of requests had died down.

**Comment by nwalters512** [comment]
![RIP](http://ericpetersautos.com/wp-content/uploads/2014/07/RIP-2.gif)

**Comment by fangeugene** [comment]
So much rip. when >50% of your bandwidth used (after CF caching) is all internal...

**Comment by fangeugene** [comment]
84B vs 300KB

![image](https://cloud.githubusercontent.com/assets/1421884/13735564/b10121a2-e981-11e5-861a-63fcbcb9e766.png)

**Comment by gregmarra** [comment]
At work, we give out "fix of the week" awards. I think you just landed one
here! Nice.

**Comment by fangeugene** [comment]
![image](https://cloud.githubusercontent.com/assets/1421884/13746711/fe8fd230-e9ca-11e5-927b-dc8aa1f2a8db.png)

**Comment by phil-lopreiato** [comment]
> At work, we give out "fix of the week" awards. I think you just landed one here! Nice.

Agreed! #dataWinsArguments
