### ISSUE TITLE
FIRST event page link outdated

### ISSUE THREAD

**Issue by aherreidFIRST** [the-blue-alliance/the-blue-alliance#1417]
The link to "FIRST's Event page" on the top of some pages (like https://www.thebluealliance.com/event/2016scmb#rankings) is outdated. 

The new links are formatted with year and event code (such as http://frc-events.firstinspires.org/2016/SCMB)

Thank you.

**Comment by nwalters512** [comment]
The "old" pages have more information than frc-events (website, address, and PDFs of site info and the public schedules), and also have links to rankings/results/awards on frc-events. If FIRST is hoping to phase out the "old" event pages, we can of course make this switch, but it would be great to have information parity on both pages before that's done.

**Comment by fangeugene** [comment]
@nwalters512 I think Alex is referring to the link at the top of the rankings page, not the top of the page.

**Comment by nwalters512** [comment]
This is what happens when I review issues late at night. Disregard that!

**Comment by phil-lopreiato** [comment]
@aherreidFIRST thanks for the report! This must have snuck through the cracks of not getting updated last year with the new results pages. We'll be sure to get it updated.
