### ISSUE TITLE
Provide a way to get a list of events for dev environment

### ISSUE THREAD

**Issue by synth3tk** [the-blue-alliance/the-blue-alliance#1433]
As it stands now, there's no real easy way to generate a list of events for any given year without an FMS API key so that it can be populated with teams and whatnot.

Phil came up with the idea of creating a CSV of events (in the [the-blue-alliance-data](/the-blue-alliance/the-blue-alliance-data) repo). This could include just the minimum amount of information needed to create a valid model. Location would most likely be in each year's root folder.

**Comment by fangeugene** [comment]
@phil-lopreiato's bootstrap from APiv3 script takes care of this.
