### ISSUE TITLE
Update FMSAPI Matches Parser for Octofinals

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1436]
According to the info from Alex

> The Octofinals (as we call them) will appear this year in all the normal spots as Regional (and other) events. We'll get some test data onto staging before too long, hopefully.
This includes: 
> The number of alliance in the alliance endpoint will be 16 alliance

> Matches will be numbered starting with Octofinals 1 being #1 (so the numbering won't match 8-alliance events)

> Alliance are not re-numbered between sublevels (which did happen last year, since there was no concept of 16 alliances on our side)

To me, the best approach would be to check the match description from the first item, if it contains the string "Octofinal", do the special renumbering

**Comment by phil-lopreiato** [comment]
Staging data is available to test with

> Test data is now available on the Staging API. For example, here's a few calls:
https://frc-staging-api.firstinspires.org/v2.0/2016/schedule/micmp/playoff
https://frc-staging-api.firstinspires.org/v2.0/2016/alliances/micmp/
This data may come and go as other things are tested, but they can be used as examples.

**Comment by fangeugene** [comment]
Can you save those pages right now?

**Comment by phil-lopreiato** [comment]
https://gist.github.com/phil-lopreiato/b498f2a3ab9ae4681ffe4274db6d3d36

**Comment by fangeugene** [comment]
Can you grab hybrid_schedule as well? Thanks.

**Comment by phil-lopreiato** [comment]
Updated the gist.
