### ISSUE TITLE
Match video icons not displaying on event page for Livonia District 2016

### ISSUE THREAD

**Issue by Joshfoxy** [the-blue-alliance/the-blue-alliance#1438]
On the overall event page, the icon indicating a video exists for a match is only there for the finals matches. If you click on any other elims match, the video shows up at the bottom, and the icon also shows up on individual team pages match lists.

**Comment by phil-lopreiato** [comment]
It's probably due to the fact that the caches for the pages are out of sync, if you wait a bit, it should fix itself. Or someone can clear the page manually.

**Comment by fangeugene** [comment]
I manually cleared cache so video icons show up now.

Caching is fun... We should rework HTML caching in the offseason.
