### ISSUE TITLE
some regionals give inaccurate district points for playoff rounds

### ISSUE THREAD

**Issue by frc-guy** [the-blue-alliance/the-blue-alliance#1439]
On the mobile app and the API, a number of regionals, including onto, txda, and nyro, give all teams 0 elims points instead. I enjoy looking at the hypothetical district points, and they're just not accurate for a whole bunch of regionals.

**Comment by phil-lopreiato** [comment]
I believe this is caused by https://github.com/the-blue-alliance/the-blue-alliance/issues/1434

**Comment by fangeugene** [comment]
Weird that this issue is only now showing up..
