### ISSUE TITLE
Return timezone for regional events

### ISSUE THREAD

**Issue by hexane360** [the-blue-alliance/the-blue-alliance#1444]
My team is automatically pulling data from a regional into a google spreadsheet. All time data is returned in Unix time, which we then convert. However, we'd like to get the schedule in local time for arbitrary regionals. Would it be possible to return the timezone of a regional as an integer compared to UTC within the JSON Event model?

**Comment by fangeugene** [comment]
What about returning timezone as a standard string like `America/Los_Angeles` (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

We already have that information on the server and makes more sense than an integer UTC offset due to weird things like daylight savings time.

**Comment by hexane360** [comment]
That works too, as long as the list is documented on the wiki.

I'm glad you already have the data available.

**Comment by phil-lopreiato** [comment]
@hexane360 It should be live now, if you take a look. Does that work for you?

**Comment by hexane360** [comment]
It's working great for me! Thanks!
