### ISSUE TITLE
Update contact page for what to do w wrong team robot name

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1446]
http://www.thebluealliance.com/contact

We should change the 'team name' part to say 'team info' with a 'team name' and 'robot name' sub-header. We've gotten lots of email about robot names – teams need to update this in TIMS and we will automatically update. We have no way to manually override this.

**Comment by brycematsuda** [comment]
If changing both team name and robot name require TIMS, I'm not seeing what the purpose of the subheaders would be.

Could it be edited to something like this?

![tba1446](https://cloud.githubusercontent.com/assets/6787907/14444820/0f15f0b0-fffd-11e5-8e17-85503614d599.png)

**Comment by phil-lopreiato** [comment]
We'll probably want to mention that we update that info daily now

**Comment by synth3tk** [comment]
What about location? Sponsors? Etc.

I think "Team Info[rmation]" would fit better than listing everything out.

**Comment by brycematsuda** [comment]
New header: Team information wrong?
New paragraph: If your team's information, such as team name, sponsors, and robot name, is incorrect on The Blue Alliance, please check if it is correct on FIRST's website. We update our records from FIRST's TIMS daily, and are unable to change your team information to anything other than what is listed there.
