### ISSUE TITLE
Red and Yellow Cards

### ISSUE THREAD

**Issue by weaversam8** [the-blue-alliance/the-blue-alliance#1454]
Is there a way to view red and yellow cards assigned to teams at events?

**Comment by phil-lopreiato** [comment]
There is not, unfortunately. That information is not exposed the the FRC API, I don't think.

**Comment by weaversam8** [comment]
Gotcha. I took a quick look through the FRC API docs, and I think you're right.

**Comment by phil-lopreiato** [comment]
There is already an open feature request for card information on the FRC API tracker, so this may be something we can add in the future

https://usfirst.collab.net/sf/go/artf4843
