### ISSUE TITLE
2016 Stat Suggestion: RP/match

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1455]
could rank by team, or by team@event

**Comment by phil-lopreiato** [comment]
That would be cool. We could calculate it just as am average, or we could do an opr-like contribution matrix of the different RPs (victory, breach, challenge). The latter would also allow us to do ranking predictions, which would be cool also

**Comment by bdaroz** [comment]
Closing this as going forward HQ is doing RP as an average anyway.
