### ISSUE TITLE
Show "Match Previews" for GAs

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1458]
Suggested on FB:
https://www.facebook.com/groups/moardata/permalink/1094808283872799/

**Comment by synth3tk** [comment]
Whatever this ends up being, it should be very minimal, or at least provide a button/option that takes away any extra stuff. Some GA's calling style (including mine) is to walk around, sometimes in front of the scorers table. It'd be nice to have a tablet/phone in hand to reference quickly while I'm moving around.

**Comment by synth3tk** [comment]
We now have the fantastic [GA Tool](https://gatool.jameslockman.com/)!

**Comment by fangeugene** [comment]
No we don't?

**Comment by synth3tk** [comment]
Sorry, I should have clarified. The GA tool has this functionality and more for GAs, who I assumed were the intended audience of this feature.
