### ISSUE TITLE
Flag GCM Messages as High Priority

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1462]
So that they'll still go through, even with Doze enabled
See https://github.com/the-blue-alliance/the-blue-alliance-android/issues/678

**Comment by fangeugene** [comment]
Is this necessary? Why not respect priority/doze?

**Comment by nwalters512** [comment]
Because if your phone enters Doze mode while in your pocket like it will in Android N, you'll wonder why match results are showing up to your phone half an hour late.

**Comment by fangeugene** [comment]
Didnt realize N was so aggressive about it.
