### ISSUE TITLE
Suggestion: Show Ranking Points/Match to compensate for different # of matches played

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance#1465]
It's weird and confusing enough (esp. for spectators) when rankings bounce around just because some teams have played one more match than others, but it's much worse when one team played 2 fewer matches because they played a surrogate match.

See #1464 . FRC254 is doing awesome and achieving 2-ball autonomous, but they were ranked something like 30. After playing Q43 they're ranked 8 with 3-0-0 and 11RP, compared to FRC4186 which is ranked 5 with 3-2-0 and 12RP.

TBA could help by displaying another rank that compensates for the number of matches (that count).

**Comment by 1fish2** [comment]
I was thinking something like: `rank / number_of_matches_played * max_number_of_matches_played` but if the stat was just `rank / number_of_matches_played` then this becomes the same as Issue #1455

To be clear, it's also worth being able to sort by the adjusted-rank value.

**Comment by phil-lopreiato** [comment]
I think we want the rankings to stay sorted by the "official" values we get from FIRST and anything else would be even more confusing (we want them to match the results on the pit display as well as on frc-events).

**Comment by 1fish2** [comment]
@nwalters512 pointed out that we wouldn't want this feature to require a long text explanation, and it's hard for an explanation to be short when it mentions the problems with the official ranking.

Anyway, here's a mockup. It's a snapshot of tonight's Curie rankings with an added **RP/Match** column. Imagine that clicking a column header sorted the table by that column. (That works in the live page but the snapshot must've broken some relative link or CSS hack needed for that to work.)

Let's assume for the moment that people understand the term "RP" (which FIRST uses) and also the existing column header **Ranking Score**. (That disconnect is not ideal.)

It doesn't pretend that the **RP/Match** column is an official ranking. It's just a value. This mockup doesn't explain it or suggest that you sort by it. That's not ideal.

The page doesn't make it obvious that you can sort by clicking on a column header. It doesn't even switch from an I-beam cursor to an arrow cursor when you hover over one of these headers. We should fix that.

Another issue is **RP/Match** only accounts for the first ranking factor. No tiebreakers. OTOH it's simple and no lie.

Still, looking down the new column you can easily see that the `#4` team ought to be first while the `#10`, `#15`, and `#16` teams are vying for second position.

HTML file: [Curie Division_2016-04-28_extra_column.html.zip](https://github.com/the-blue-alliance/the-blue-alliance/files/241669/Curie.Division_2016-04-28_extra_column.html.zip)

<img width="967" alt="rp-per-match" src="https://cloud.githubusercontent.com/assets/1043120/14906196/7fb470f8-0d6d-11e6-9bb7-783a24a4daf1.png">

**Comment by 1fish2** [comment]
I retitled this suggestion. If it doesn't claim to be a ranking then it won't confuse people about the difference vs. official rankings.

In the mockup it's not obvious why this column is there and that you can sort by it. It'd help to change the column header **Ranking Score** to **Ranking Points** or **RPs**.

**Comment by 1fish2** [comment]
This got implemented #1573 by @maherb , yay!!
I'll mark it closed. Please correct it if needed.
