### ISSUE TITLE
gameday drops links to remove chat, social on narrow browsers

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1467]
Should drop other elements first to save space, since you need these to fix layout. Should also drop into an overflow "more" menu.

![image](https://cloud.githubusercontent.com/assets/57101/14406906/88587f04-fe6a-11e5-8ea5-f98054b21757.png)

**Comment by gregmarra** [comment]
@fangeugene @nwalters512 if one of you wanted to fix this quickly before champs that'd be awesome. I'm out of town this weekend and don't have my personal laptop.

**Comment by nwalters512** [comment]
I can take a look at this in the morning.

**Comment by phil-lopreiato** [comment]
I think the other quick fix before champs, if possible, should be #1448

**Comment by fangeugene** [comment]
GameDay2 exists.
