### ISSUE TITLE
Add GameSense stream as a special event for champs

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1479]
Using the sitevar 'gameday.special_webcasts', include the GameSense Champs stream.

http://www.thebluealliance.com/admin/sitevar/edit/gameday.special_webcasts

Should also update the description of the sitevar to include it's required format.

**Comment by gregmarra** [comment]
Stream will be https://www.twitch.tv/frcgamesense

We don't have a way to add a date range for this, so will just have to manually turn on/off.

**Comment by phil-lopreiato** [comment]
I'm so excited for this! In the future, this will be a great application for #1267

**Comment by fangeugene** [comment]
Or just add it like we add Kickoff because i dont want to build new things
2 weeks before champs unless it's predictions :P.

**Comment by phil-lopreiato** [comment]
Yeah, that's more for future events, we can just use the sitevar for champsr

**Comment by fangeugene** [comment]
Done.
