### ISSUE TITLE
4 Team Alliances Check for CMP

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1486]
Ensure everything works
- [ ] Playoff Advancement on Event Pages
- [ ] Nightbot status
- [ ] MyTBA Page Playoff Advancement (as well as backup bots)

**Comment by fangeugene** [comment]
There are a few cases and we should make sure they all work.

1) Alliances are 4 teams and the 4th team never plays
2) Alliances are 3 teams and a backup bot is used
3) Alliances are 4 teams and a backup bot is used (this should be functionally the same as #2)

**Comment by fangeugene** [comment]
This works as far as I know.
