### ISSUE TITLE
GameDay2 UI/UX

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance#1489]
Opening this issue to discuss some thoughts Eugene and I were tossing around regarding the GameDay2 UI/UX.
### Terms

View: one box that a video goes in
Layout: an arrangement of Views
Overlay: the header that appears when a View is hovered on
### Proposals for GD2
- Layouts and the choosing of Layouts shouldn't change (a dropdown that selects the layout)
  - If you go from a Layout to another Layout with fewer Views, it maintains the logical order of the webcasts in the Views; true even if Views were swapped since the former Layout was selected
  - If you go from a Layout with more Views to fewer Views, back to more Views, it should remember the webcasts that were in the hidden Views
- Eliminate the current drag-and-drop way of selecting webcasts. Instead, each View should provide a UI for selecting the webcast it will display
  - This selector could take the form of a dropdown, a list that overlays the current video, or something else
  - The webcast selector should be visible if the View is empty, or accessible from the Overlay if the View is already populated.
  - It might be wise to have a 2 stage selector, the first for the event and the second for the webcast, so one event with 10 webcasts doesn't flood the entire dropdown
    - Alternatively, any event with multiple webcasts can display the webcasts as nested & indented under the event name; not all webcasts are necessarily associated with an event, and there's little point to requiring a user to click an event before they can click on that event's only webcast
- Swapping Views should also be supported. When hovering on a View, a Swap option should appear in the Overlay. Swap could have one of several behaviors:
  - A dropdown; on dropdown, all Views other than the current one get overlaid a number. The dropdown should contain numbers corresponding to these Views. Clicking on a number swaps the current View with the selected one.
  - A dropdown; on dropdown, iconography shows which View this current View will be swapped with, using icons similar to the Layout icons, but graying out all of them except for the swap target
  - Instead of a dropdown, overlay the entire View with a miniature version of the current layout composed of grey boxes. Clicking on a box will swap the current View with the View at the clicked box's location

**Comment by gregmarra** [comment]
One thing we could try to simplify some of the interactions is to use buttons that open dialogs with more verbose displays of options. For example, "change layout" could open a dialog displaying thumbnails of all the views available. A view could have a menu to select what event you want, then pick "event details", "webcast1", "webcast2" etc.

One thing that will be nice with React is that it should be easier to separate the state of the viewer from the elements that modify that state, keeping the code cleaner and easier to work with. :)

**Comment by nwalters512** [comment]
> One thing that will be nice with React is that it should be easier to separate the state of the viewer from the elements that modify that state, keeping the code cleaner and easier to work with.

That's one of my favorite things about React so far, modularity and separation of concerns are so easy! I'm looking at Redux for state management, it looks very promising.

**Comment by fangeugene** [comment]
Yay gd2
