### ISSUE TITLE
FIRST team data website with relative URL could be scraped anyway

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1491]
http://www.firstinspires.org/team-event-search/team?id=357831 shows Team 1310's website with a link to http://www.firstinspires.org/team-event-search/www.team1310.ca, which is obviously not their website. It does display the string www.team1310.ca, so we could probably succeed in guessing the website, and we could also do a regex that removes "www.firstinspires.org/team-event-search/" from websites.

I'm not sure what actually is updating team details these days, but Team 1310 reported this to us.

**Comment by fangeugene** [comment]
The problem is this line

https://github.com/the-blue-alliance/the-blue-alliance/blob/master/datafeeds/parsers/fms_api/fms_api_team_details_parser.py#L38

**Comment by bdaroz** [comment]
With the data coming from the FRC API now this is moot. If there's an error it's going to be on the team to fix in TIMS.
