### ISSUE TITLE
Engineering Inspiration Award

### ISSUE THREAD

**Issue by weaversam8** [the-blue-alliance/the-blue-alliance#1493]
So, I have found an issue, and I think it's not a bug, but rather a failure in an edge case. Our team, 4534, The Wired Wizards, won an Engineering Inspiration award at our last district qualifying event, `2016ncbui`, qualifying us to win it at our state district championship `2016nccmp`, which we did. Unfortunately, we did not qualify with our robot for our championship, we just went to compete for the award itself. Due to the fact that we did not compete with a robot at the event, it does not show up on our team page, which therefore does not have a place to display our award which we won. Thoughts?

**Comment by fangeugene** [comment]
I manually added you to the event. It shows up on your page now.

http://www.thebluealliance.com/team/4534
