### ISSUE TITLE
show upcoming match times

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance#1497]
It'd be great for the upcoming match schedule (with its super helpful yellow marks identifying your followed teams):
<img width="569" alt="hopper upcoming quals" src="https://cloud.githubusercontent.com/assets/1043120/14919956/fd2cf31c-0ddf-11e6-8b0a-e62ea1f907dd.png">

to also include upcoming match times like TBA Android has:
![hopper schedule on android](https://cloud.githubusercontent.com/assets/1043120/14920285/81abfa10-0de1-11e6-836f-6dd4b7fd233f.png)
(or better yet, [estimated match times](https://github.com/the-blue-alliance/the-blue-alliance-android/issues/723)), so that combined, you have enough information to plan when to tune in and when to get lunch.

This would also make it workable to combine upcoming match schedules across multiple CMP fields.

**Comment by 1fish2** [comment]
Ditto in the focussed match schedule on the Team@Event page:
<img width="961" alt="971 on hopper" src="https://cloud.githubusercontent.com/assets/1043120/14920913/57cac91c-0de4-11e6-94f7-28b73007c332.png">

**Comment by fangeugene** [comment]
Fixed in 2017.
