### ISSUE TITLE
indicate surrogate matches on each match list

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance#1500]
[Split out from #1464.] It's important to know which matches are surrogates, i.e. matches that don't count towards ranking.

If the FIRST API doesn't include this info, we could derive it from the length of each team's quals match list.

**Comment by phil-lopreiato** [comment]
This one isn't in FIRST's API, but I think the simpler solution is to just ask them to include it for next year

**Comment by fangeugene** [comment]
It is in the api

**Comment by phil-lopreiato** [comment]
Oh, right, it was cards that aren't in the API.

**Comment by chacha** [comment]
You can calculate it retroactively by taking the number of matches played and detecting if a team deviated from that. If so, their 3rd match would be the surrogate.

To quantify the number of matches that should be used as the standard would be the hardest part. It is probably sufficient to take the median matches played, and detect surrogate matches from there.

**Comment by fangeugene** [comment]
Predictions calculates surrogates by looking at the min # of matches played by a team at an event, and any team that plays more than that min must have the 3rd as the surrogate.

**Comment by fangeugene** [comment]
DONE!
