### ISSUE TITLE
Match predictions for playoffs

### ISSUE THREAD

**Issue by tsteward** [the-blue-alliance/the-blue-alliance#1502]
Currently, the Advanced Insights page only shows predictions for qualifications matches. It would be nice to have predictions for the playoff matches.

**Comment by phil-lopreiato** [comment]
The reason we didn't enable them for playoff initial is for two reasons. One, there are scoring differences (points for breaches and captures) that would require some math tweaks. And two, we can't model Alliance synergy. 

We figured if we enabled them, they'd be way off and confusing, so we didn't. Open to reconsidering that though

**Comment by fangeugene** [comment]
Breach capture is easy since we already predict that.

**Comment by gregmarra** [comment]
We'd predict highest sum(opr) wins the division, since the alliances don't
change, right?

**Comment by jhtervay** [comment]
Not sure that highest sum OPR is a fantastic measurement- especially due to defense being much more common in playoffs than qualifications in my experience.

**Comment by tsteward** [comment]
This was implemented in #1783.

**Comment by fangeugene** [comment]
"They may be bad, but they exist."
