### ISSUE TITLE
"Highest Scoring Match" in Homepage is wrong.

### ISSUE THREAD

**Issue by guoxiangyang** [the-blue-alliance/the-blue-alliance#1504]
Now the home page give this:

===================================================
New England District Championship Quarters 4 Match 2

Teams	                       Score
230	       1519	 176   	257
1058	319	3467	178

=====================================================

Carver Division Quarters 3 Match 2
120	2481	330	        3478	360	       57	**275**	155

Newton Division Quarters 3 Match 1
118	1519	3309	3476	4678	217	190	**260**

**Comment by phil-lopreiato** [comment]
That gets calculated once every 24 hours, so you must have looked before the data updated.

**Comment by chacha** [comment]
This has now been automatically updated to point to the Carver Division Quarter 3 Match 2 score.
