### ISSUE TITLE
Championship Conference Indicator

### ISSUE THREAD

**Issue by chacha** [the-blue-alliance/the-blue-alliance#1510]
Next to the location field of each team, it would be nice to add a Blue or Yellow Indicator (in the form of a small dot?) that showed which championship the team would usually be assigned to.

Obviously, this could change if they petitioned to go to a different championship, but it would be nice context to add.

**Comment by fangeugene** [comment]
Fixed in https://github.com/the-blue-alliance/the-blue-alliance/commit/66d53bf75bd1a6803dc93c6f10eb49ac8a58b731
