### ISSUE TITLE
sign in redirects don't work

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1521]
Clicking "Take me to the login page!" on https://www.thebluealliance.com/account/login_required?redirect=http://www.thebluealliance.com/suggest/team/media?team_key=frc1086&year=2016 then reloads the homepage, or reloads my accoutn page if I am already logged in.

I expect it to reload the media suggestion page I was on.

**Comment by fangeugene** [comment]
That link still won't work since all the symbols (especially `?` and `&`) after the first `?` should be escaped. Now the URLs should look like:

`http://localhost:8080/account/login_required?redirect=http%3A//localhost%3A8080/suggest/team/media%3Fteam_key%3Dfrc254%26year%3D2016`
