### ISSUE TITLE
Instagram support for Social Medias

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1522]
ie https://www.instagram.com/bobcatrobotics/

**Comment by tsteward** [comment]
I'll work on this.

**Comment by phil-lopreiato** [comment]
@tsteward if you wait until https://github.com/the-blue-alliance/the-blue-alliance/pull/1525 gets merged, it should be much simpler to do (all the urls are nicely put into constants). 

The only issue is that all the rendering is pretty messy, it should be refactored to use partial templates more. If I get the chance today, I'll try and refactor that one too to make it even simpler
