### ISSUE TITLE
YouTube videos can't be added to Team Media.

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1523]
https://www.youtube.com/watch?v=_aA59BsOCeEQ can't be added to http://www.thebluealliance.com/suggest/team/media?team_key=frc1086&year=2016

Attempts get "Uh oh! // Sorry, but we are currently unable to support the URL you submitted. See below for currently supported formats."

No YouTube URL I tried works.

**Comment by phil-lopreiato** [comment]
Shoot, I know why. 

I'll fix this and clean up the media parsing process, as well.
