### ISSUE TITLE
Scraping USFIRST offseasons is broken

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1528]
Probably due to URL change or page formatting?

http://www.thebluealliance.com/admin/offseasons is a 500.

**Comment by fangeugene** [comment]
We need to find the page again. The current page we look at is `http://www.usfirst.org/roboticsprograms/frc/calendar/list` but when FIRST moved to firstinspires.org they broke a ton of existing links.

**Comment by fangeugene** [comment]
Found it. http://www.firstinspires.org/robotics/frc/calendar

**Comment by gregmarra** [comment]
Should a unit test have broken?

**Comment by fangeugene** [comment]
Nope because we test the parser on local data. Almost nothing tests on actually making requests because most of the stuff is on the API now and there's no easy way of testing without storing an API key. If someone can figure that out that would be great.

**Comment by phil-lopreiato** [comment]
You can put keys in Travis environment variables. I'll link the docs when I get home

**Comment by fangeugene** [comment]
But how do we make it private?

**Comment by phil-lopreiato** [comment]
I think there was something about encrypting them? Not sure if it solves our issue though
