### ISSUE TITLE
Insights that rely on score breakdowns should not be calculated for events that do not have score breakdown data.

### ISSUE THREAD

**Issue by tsteward** [the-blue-alliance/the-blue-alliance#1533]
This page is filled with a bunch of 0s
https://www.thebluealliance.com/event/2016ctsc#event-insights

**Comment by bdaroz** [comment]
Just checking, but that page doesn't seem to have an Insights tab currently. Perhaps this can be closed?

**Comment by fangeugene** [comment]
Yep, it was fixed here: https://github.com/the-blue-alliance/the-blue-alliance/commit/eeb6ba0345ce94d292c69e3d34e5187804cc239d
