### ISSUE TITLE
Look into improving GD2 loading performance

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance#1538]
Some statistics on GD2's current page loading (averaged over a few hard refreshes; note this bypasses caching so repeat visits will of course be faster):
- 134 network requests
- 1.8MB loaded
- 1.5s until DOMContentLoaded
- 1.7s until the first meaningful paint
- 13.1s until "everything" is loaded and requests stop for the most part

Time until first meaningful paint is pretty good; anything under 2s is great in my book. The only way we could maybe improve that is be prerendering the body on the server then letting React take over once that loads - I think that's a technique but I haven't looked into it much.

I'm concerned with the sheer amount of things that are loaded - most of the 1.8MB comes from the social panel (should we remove that entirely) and the Twitch chat. We should look into lazy-loading them once the panels are opened, not immediately upon page load. This is especially important on mobile, where neither of those things will ever even be visible.

Perhaps that's premature optimization, though. That's a relatively small amount of data compared with what's required to stream video. Is it worth the effort?

I did notice an anomaly during one of the page loads: the browser waited almost 9 seconds to get a response for the main GameDay js file. @fangeugene can you comment on how appengine serves static files? Should we be looking as some kind of CDN for that pretty static and pretty large JS file?

**Comment by fangeugene** [comment]
All static files (like our images and css/js) are automagically served over Google CDN (and CloudFlare on top of that).

**Comment by nwalters512** [comment]
Yay, good news. Guess that 9s wait was a fluke on their part?

**Comment by fangeugene** [comment]
The page practically instaloads for me.

**Comment by nwalters512** [comment]
It does virtually every time for me too.

**Comment by fangeugene** [comment]
Must have been a fluke.

**Comment by nwalters512** [comment]
With #1716, the whole page loads and renders in ~1.3s. I'm considering this resolved.
