### ISSUE TITLE
Show when a team last competed

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1546]
[Suggested on fb](https://www.facebook.com/groups/moardata/permalink/1126063504080610)

> If someone were to implement this on TBA (this sounds like an awesome starter task for someone looking to get their feet wet)...
We'd probably want to use [EventTeams](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/models/event_team.py) (which events the team is/has registered for). We could add a line saying "Last competed in X" when X is not equal to the current year

This is the [template for the team details page](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/templates_jinja2/team_partials/team_info.html) and this is the [controller that fills it](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/renderers/team_renderer.py#L26).

You can use the [TeamParticipationQuery](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/database/team_query.py#L89) to find all the years in which the team has registered for an event

**Comment by phil-lopreiato** [comment]
To clarify, this is most helpful to clarify team pages showing a year that isn't their last. In those pages, there is no way to know that the team you're looking at is no longer active. For example, Team 1717 folded after 2015, but you can't tell that from [their 2013 page](http://www.thebluealliance.com/team/1717/2013)

**Comment by technonerdz** [comment]
I Will look at that today and when I get home!

Felix G.

**Comment by MC42** [comment]
Perhaps the easiest way is to use the participation array, though my Python is rather rusty.

if (participation[-1] != current_game_year)
    last_playing_year = participation[-1]

And then if the template sees last_playing_year as null, it just doesn't render the line?

Sorry I can't help more.
