### ISSUE TITLE
2016cmp Rankings & Stats Question

### ISSUE THREAD

**Issue by jhtervay** [the-blue-alliance/the-blue-alliance#1548]
Ah, I hit enter too early and goofed the title.

Anyway, these two API endpoints and giving me back the same data. It doesn't look like the typical event/_____/stats page. Is this typical for CMP data?

**Comment by phil-lopreiato** [comment]
`2016cmp` is the event code for [Einstein](http://thebluealliance.com/event/2016cmp). The stats endpoint should look similar to other events (it should contain OPRs, year specific game stats, etc) and the rankings endpoint should return empty because there are no quals matches played on Einstein. I just hit both endpoints and they returned the proper data.

Can you share how you're querying these/what exactly you're seeing (curl logs would be awesome)?

**Comment by fangeugene** [comment]
This is what I get for rankings:
`
[]
`

and stats:
`
{"year_specific": {"qual": {}, "playoff": {"C_SallyPort": [3, 20, 15.0], "scales": [38, 108, 35.185185185185183], "captures": [26, 36, 72.222222222222229], "challenges": [59, 108, 54.629629629629626], "A_Portcullis": [4, 5, 80.0], "D_RockWall": [35, 35, 100.0], "LowBar": [36, 36, 100.0], "average_high_goals": 16.0, "C_Drawbridge": [2, 16, 12.5], "B_Moat": [23, 23, 100.0], "breaches": [36, 36, 100.0], "average_boulder_score": 72.083333333333329, "A_ChevalDeFrise": [30, 31, 96.774193548387103], "average_low_goals": 0.27777777777777779, "average_score": 210.69444444444446, "average_win_score": 222.66666666666666, "B_Ramparts": [13, 13, 100.0], "average_win_margin": 23.944444444444443, "average_foul_score": 4.8611111111111107, "average_auto_score": 43.611111111111114, "average_crossing_score": 28.055555555555557, "D_RoughTerrain": [1, 1, 100.0], "high_score": [255, "2016cmp_qf2m2", "QF2-2"], "average_tower_score": 24.027777777777779}}}
`

**Comment by jhtervay** [comment]
Ugh.. I'm gonna close this. I had two functions:

```
def get_event_stats_json(event_key):
    url = __tba_url + 'event/{0}/rankings'.format(event_key)
    return requests.get(url, headers=__api_key).json()


def get_event_rankings_json(event_key):
    url = __tba_url + 'event/{0}/stats'.format(event_key)
    return requests.get(url, headers=__api_key).json()
```

And if you look at the URLs, you'll see they're in the wrong functions... Oops. Anyway. Both definitely returned the same data, though, and it was likely the typical `stats` breakdown and I was too tired to differentiate the two... Maybe I'm crazy. >_>
