### ISSUE TITLE
Match predictions use bad OPR for Einstein teams

### ISSUE THREAD

**Issue by sciencewhiz** [the-blue-alliance/the-blue-alliance#1555]
@fangeugene Looking at the 2016 IRI predictions, it appears that matches that have teams from 2016 Einstein have incorrect predictions (possibly because OPR wasn't calculated for Einstein). For example, in Match 97, team 2056, 118, and 4587 are predicted to score 55 points. If you assume 2056 and 118's OPR are zero, then the prediction matches 4587's Hopper OPR.

**Comment by fangeugene** [comment]
Good call.

**Comment by sciencewhiz** [comment]
Not being familiar with the site update schedule, should the fix be live? It still shows the same predictions as before the patch for me.

**Comment by fangeugene** [comment]
Had to clear caches. Should be good now.

**Comment by phil-lopreiato** [comment]
The page won't update immediately, as the prior version will continue to live in cache for up to 24 hours. It should be fixed and update soon, though
