### ISSUE TITLE
Incorrect match data at IRI 2008

### ISSUE THREAD

**Issue by jhtervay** [the-blue-alliance/the-blue-alliance#1560]
At [IRI 2008](http://www.thebluealliance.com/event/2008iri), team 1738 supposedly played in Qual Match 78. This team never existed, let alone be invited to IRI to play for 1 single match.

You can slightly tell from the match video that the overlay shows 1739 is playing that match. Additionally, the TBA page says 1739 only played 6 matches while other teams played 8 matches - except for 1731, which supposedly only played 7.

**Comment by fangeugene** [comment]
Fixed.
