### ISSUE TITLE
API endpoint for single match - does not support eigthfinals in MICMP

### ISSUE THREAD

**Issue by jhtervay** [the-blue-alliance/the-blue-alliance#1562]
Requesting the match data for MICMP eigthfinals does not return any data. For example, the endpoints `/api/v2/match/2016micmp_ef1m1` and `/api/v2/match/2015micmp_ef3m1`.

This appears to affect match lists as well.

**Comment by phil-lopreiato** [comment]
Hmm, the [validator](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/models/match.py#L246) seems to support `ef`, not sure what the issue is, at a quick glance

**Comment by jhtervay** [comment]
Just to confirm - can you replicate the issue?

**Comment by brandondean** [comment]
Actually, the validator doesn't support `ef1m`, it only supports `ef`.

**Comment by phil-lopreiato** [comment]
Yeah, I could repro it. @brandondean has got it covered
