### ISSUE TITLE
2015mrcmp_qm72 has (-1) blue far totes scored

### ISSUE THREAD

**Issue by tervay** [the-blue-alliance/the-blue-alliance#1563]
Requesting `/api/v2/match/2015mrcmp_qm72` returns JSON with the following data:

```
{ "score_breakdown": {
    "blue": {
        "tote_count_far": -1
        ...
    }
    ...
}
```

This should be 0 instead, after watching the match video.

**Comment by phil-lopreiato** [comment]
Interestingly, [FRC-Events](https://frc-events.usfirst.org/2015/MRCMP/qualifications/72) shows the same error. I'd probably chalk this up to human error with the clickers, but I vote we leave this as is, since it's consistent with upstream. @fangeugene?

**Comment by fangeugene** [comment]
If frc-events has the same error, then we should leave it imo.
