### ISSUE TITLE
Make `paver deploy` More Versitile

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1568]
Take server target as an input

**Comment by phil-lopreiato** [comment]
Another improvement for the deploy script, allow setting a flag to pass through the `--no_cookies` flag to `appcfg.py`. I use multiple accounts to deploy different projects and would prefer to be able to confirm which account I try and auth with

**Comment by phil-lopreiato** [comment]
One more suggestion: Use the travis CLI to wait for the build on the current HEAD to pass before we deploy. See what I did with android: https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/scripts/do_release.py#L56
