### ISSUE TITLE
Write postmortem for July 24th, 2016 incident #243f99b4

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1571]
What went wrong?

What should we change technically to prevent it?

What should we change operationally to prevent it?

What should we change to make recovery faster?

**Comment by phil-lopreiato** [comment]
# Issue Timeline
*some data from #1565*
 - Commit 9820629080ba5822942a74635b7b2f62bde8517b made at Sun Jul 24 14:24:27 2016 Eastern
 - Event started in #monitor Slack channel at Sun Jul 24 14:33 2016 Eastern
![screenshot from 2016-07-24 19-28-44](https://cloud.githubusercontent.com/assets/2754863/17087388/8da0bf5c-51d6-11e6-91a9-98c7f324e10e.png)
 - 500 Error graph
![8dcf4a3c-51b0-11e6-8c11-7be4cf1ebb81](https://cloud.githubusercontent.com/assets/2754863/17087285/af833f48-51d4-11e6-950f-a441250d2a7c.png)
 - New build pushed Sun Jul 24 14:47:32 2016 Eastern
 - #1565 opened by @gregmarra Sun Jul 24 17:41:32 2016 Eastern
 - @gregmarra having issues making a working build, opened #1566, #1567, #1568  Sun Jul 24 18:59:32 2016 Eastern
 - @phil-lopreiato managed to push a working* build Sun Jul 24 19:38:32 2016 Eastern
 - Event closed in #monitor Sun Jul 24 19:39 2016 Eastern
![screenshot from 2016-07-24 19-39-54](https://cloud.githubusercontent.com/assets/2754863/17087385/76ad25b0-51d6-11e6-836e-db73b6416d36.png)

# Proposed Mitigation
 - *placeholder* (I'll fill this in later)

### Footnotes
\* Uploading the main module, I got this error log, but the push seems to have succeeded:
```
07:37 PM Cloning 77 static files.
07:37 PM Cloning 2506 application files.
07:37 PM Cloned 2000 files.
07:37 PM Compilation starting.
07:37 PM Compilation completed.
07:37 PM Starting deployment.
07:37 PM Checking if deployment succeeded.
07:37 PM Deployment successful.
07:37 PM Checking if updated app version is serving.
07:37 PM Checking if Endpoints configuration has been updated.
07:37 PM Will check again in 1 seconds.
07:37 PM Checking if Endpoints configuration has been updated.
07:37 PM Will check again in 2 seconds.
07:37 PM Checking if Endpoints configuration has been updated.
07:37 PM Will check again in 4 seconds.
07:37 PM Checking if Endpoints configuration has been updated.
07:37 PM Completed update of app: tbatv-prod-hrd, version: 1-3
07:37 PM Uploading index definitions.
07:37 PM Error 403: --- begin server output ---
You do not have permission to modify this app (app_id='s~tbatv-prod-hrd').
--- end server output ---
Your app was updated, but there was an error updating your indexes.
07:37 PM Uploading cron entries.
07:37 PM Error 403: --- begin server output ---
You do not have permission to modify this app (app_id='s~tbatv-prod-hrd').
--- end server output ---
Your app was updated, but there was an error updating your cron tasks.
07:37 PM Uploading task queue entries.
07:37 PM Error 403: --- begin server output ---
You do not have permission to modify this app (app_id='s~tbatv-prod-hrd').
--- end server output ---
Your app was updated, but there was an error updating your queues.
07:37 PM Uploading dispatch entries.
Error 403: --- begin server output ---
You do not have permission to modify this app (app_id='s~tbatv-prod-hrd').
--- end server output ---
```

**Comment by fangeugene** [comment]
We have continuous deployment now thanks to @phil-lopreiato
