### ISSUE TITLE
Improve Rankings Display

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1572]
Some good feedback from this thread: https://www.chiefdelphi.com/forums/showthread.php?t=149455

## Ideas
 - Add an "offset" to the "# Matches Played" column that shows how many matches behind the current max a team is.
 - Add RP/match

Both of these items, I feel, should go in parentheses alongside the official number so it's clear they aren't official metrics.

## Implementation
TBA stores rankings in a JSON array of arrays. The first row is an array of column headers and then following are rows in the rankings table. This is because we want the storage format to be generic enough to store multiple years of ranking data (which vary pretty widely). We need to be careful about backwards compatibility - existing versions of the android expect the format to be a certain way, and if we change it, we'll cause crashes.

 We can calculate these fields in [the parser](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/datafeeds/parsers/fms_api/fms_api_event_rankings_parser.py).

**Comment by fangeugene** [comment]
For simplicity, we should just render this on the fly for now. Add a property `rankings_enhanced` or something right below https://github.com/the-blue-alliance/the-blue-alliance/blob/master/models/event.py#L205 and make the appropriate changes in the templates.

**Comment by phil-lopreiato** [comment]
For the played offsets (only for live events, I think), the table should look something like this:

| Team | RP | Played |
| ----- | --- | ------- |
| 254   | 10  | 3          |
| 123   | 8    | 2  *(-1)*  |
| 1114 | 8     | 3  |
