### ISSUE TITLE
Infer Red Cards?

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1585]
We can probably take mostly reasonable guesses about when red cards occur, even though they aren't officially published. For official matches, if `adjustPoints < 0 && adjustPoints + score == 0`, then there was probably a red card. Maybe we can catch this scenario and show a hovertext explaining that?

From fb: https://www.facebook.com/groups/moardata/permalink/1166640610022899/

**Comment by fangeugene** [comment]
That would only work for playoffs though.

**Comment by phil-lopreiato** [comment]
True. Maybe kinda still worth doing?

**Comment by maherb** [comment]
If we want to implement this, I can do it

**Comment by phil-lopreiato** [comment]
Sure! This one might be a little more involved. The idea in my head is to put a '?' next to the 0 score for possibly affected playoff matches that has a hovetext saying something like "We think there was a red card here, that's probably why you're seeing this"

**Comment by fangeugene** [comment]
We backfilled DQ data from the FRC API.
