### ISSUE TITLE
IRI 2015/2016 listed as official in API

### ISSUE THREAD

**Issue by bdaroz** [the-blue-alliance/the-blue-alliance#1607]
`/api/v2/event/2015iri` and `/api/v2/event/2016iri` API endpoints return `"official': true,` while the 2012-2014 IRI events return `false`. (I didn't check further back).

This throws off official vs non-official W-L-T totals for API clients, while, amazingly, the website is correct....

**Comment by fangeugene** [comment]
The website uses `SEASON_EVENT_TYPES` (https://github.com/the-blue-alliance/the-blue-alliance/blob/master/consts/event_type.py#L38) to calculate W-L-T (https://github.com/the-blue-alliance/the-blue-alliance/blob/master/renderers/team_renderer.py#L68), not whether an event is labed as "official". "official" indicates that an event uses the official FMS, which IRI 2015/2016 did. Perhaps we shouldn't expose the "official" field in APIv3.

**Comment by bdaroz** [comment]
Understood.. I'll look to switch to that for now, however the v2 docs list the `official` field as:

```
Whether this is a FIRST official event, or an offseaon event.
```

(And yes, the typo is in the docs.) :)

**Comment by bdaroz** [comment]
Closing with merge of #1611
