### ISSUE TITLE
Data inconsistency regarding event 2015mabos and team 88

### ISSUE THREAD

**Issue by jhtervay** [the-blue-alliance/the-blue-alliance#1617]
On the rankings page for 2015mabos (http://www.thebluealliance.com/event/2015mabos#rankings), you can see that Team 88 is ranked 4th.

However, if you go to the team list for that event, 88 is not there. Additionally, visiting Team 88's 2015 page, the 2015mabos event does not appear.

**Comment by fangeugene** [comment]
Fixed, will update when caches clear.
