### ISSUE TITLE
No match data in 2015ilch_f1m3

### ISSUE THREAD

**Issue by jhtervay** [the-blue-alliance/the-blue-alliance#1619]
http://www.thebluealliance.com/match/2015ilch_f1m3

The second video attached to the match shows the final score - 172 for red, 166 for blue. Score breakdown from the API returns null for the points as well.

**Comment by fangeugene** [comment]
Fixed, thanks.

**Comment by fangeugene** [comment]
For the record, it's FIRST that's missing the data. https://frc-events.usfirst.org/2015/ILCH/playoffs

**Comment by jhtervay** [comment]
I'm almost positive that the data was there a few weeks ago. That's quite odd to be missing it in the first place -- especially for a f3 match. Is there a chance they fix it (ever)?

**Comment by phil-lopreiato** [comment]
Interesting. TBA only scrapes data while the events are live, so it was mostly like missing back when the event was happening
