### ISSUE TITLE
GameSense Twitch does not work in GameDay

### ISSUE THREAD

**Issue by technonerdz** [the-blue-alliance/the-blue-alliance#1621]
![ss 2016-09-20 at 07 55 20](https://cloud.githubusercontent.com/assets/1951283/18692994/3fc4cd6e-7f6c-11e6-9cea-af33232750f1.png)

They are live right now and nothing is showing up!

**Comment by phil-lopreiato** [comment]
Flash is dumb. Try this: http://www.thebluealliance.com/gameday2#layout=0&view_0=gamesense-0

**Comment by nwalters512** [comment]
Reason number 1432 to formally roll out GD2 by the time competitions start :stuck_out_tongue:

**Comment by fangeugene** [comment]
Switched to html5 Twitch embed.
