### ISSUE TITLE
Some teams website have 3 / after the http:///

### ISSUE THREAD

**Issue by technonerdz** [the-blue-alliance/the-blue-alliance#1635]
Some teams like 354 have this issue. Their listed website is http:///www.withs.org/robotics . It should be http://www.withs.org/robotics . People were confused by this bug in my Messenger Chatbot

**Comment by bdaroz** [comment]
We had this same problem in FRC5881/TBASlackBot#8 and our digging showed the error was present in the data from FIRST so we just run a quick regexp on the value of the field. (We also strip out the "default" value if no website is given, but that's not relivant here.)

**Comment by phil-lopreiato** [comment]
Thanks for catching this one. We've had some trouble in the past standardizing websites (https://github.com/the-blue-alliance/the-blue-alliance/commit/c900b429cea37abc00675573b50bcd54d6f088d2 and https://github.com/the-blue-alliance/the-blue-alliance/commit/a4e54311c29a280a87b59481670c9b37d06a5d30).

It looks like this is being introduced on the TBA side, as 354's website doesn't come back with a scheme from FIRST (`http://www.withs.org/robotics`), so the issue probably lies with [this line](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/datafeeds/parsers/fms_api/fms_api_team_details_parser.py#L35)

**Comment by technonerdz** [comment]
Thanks!

**Comment by phil-lopreiato** [comment]
These should fix over time as teams get updated
