### ISSUE TITLE
Support B teams in trusted API

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1638]
Need to not add match team keys, at least.

**Comment by fangeugene** [comment]
Depends on https://github.com/the-blue-alliance/the-blue-alliance/issues/1636 if we decide to rework how match team keys are stored.

**Comment by ograff** [comment]
I don't quite follow what is currently unsupported with regards to B teams in the trusted API. Local testing seemed to function alright, and pushing results for non-existent teams (ie "frc9234" as the backup bot for "frc1234") I imagine also adds match team keys.

**Comment by fangeugene** [comment]
Currently, matches with backup teams don't have the backup teams added to `Match.team_key_names`, which is used for querying. If Cheesy Arena pushes pushes "254B" to TBA right now, we would add "frc254B" to team_key_names which probably won't do anything bad, but may have unintended consequences.

The reason this relates to #1636 is because in order to show matches on a Team's page, we need to either a) add "frc254B" to `team_key_names` and on 254's page query for 'frc254', 'frc254B', etc. which is inefficient, b) add "frc254" to `team_key_names` even if the robot is "frc254B", so it can be fetched with one query, and then sort teams from backup teams by looking at `Match.alliances`, or c) something else entirely.

**Comment by ograff** [comment]
Interesting, how does the CSV importer handle team "254B"? It appears the CSV importer just puts "frc254B" into the Math.team_key_names array (https://github.com/the-blue-alliance/the-blue-alliance/blob/08650ed4ee586f7f40772090c49c0a4575bdb094/datafeeds/offseason_matches_parser.py#L37)
