### ISSUE TITLE
Build a way to delete EventTeams

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1644]
http://www.thebluealliance.com/admin/event/2016wmri

"""
Hello, I noticed on TBA that we (4967) are listed as attending WMRI and we are not.  I checked their website and there was a mistake.  Someone had entered our number instead of our friends, The Robosharks 4956, who are attending.  It is fixed now on the WMRI site.  Please update on TBA.  Thanks!
"""

Should allow removing an EventTeam from an offseason.

**Comment by first3234** [comment]
its my bad i was just about to fix it today and i figured that it was 4967 and that they made a mastake when they typed the names of the teams
