### ISSUE TITLE
Add Admin Interface to Upload FMS Reports

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1647]
Same thing as eventwizard

**Comment by fangeugene** [comment]
How do we implement this?  I don't want to implement it serverside because then we can't share EventWizard JS code, but where would that store the API key?

**Comment by phil-lopreiato** [comment]
Hmm, this could be tricky. What if we shared the eventwizard code, but had some additional script that used the current user's signed in email as the auth ID and secret. Then the backend could check if the logged in user was an admin and compare the expected values that way?

**Comment by fangeugene** [comment]
I think that is as simple as making the ApiTrustedBaseController check for admin OR keys.
