### ISSUE TITLE
Incorrect team listed at event 2011va

### ISSUE THREAD

**Issue by jhtervay** [the-blue-alliance/the-blue-alliance#1657]
Would have also put this in the issue I opened the other day if I had found it but only just found it now. At event `2011va`, TBA lists the 6th seed alliance captain as team `17311058` and their first pick to be team `2386`. This should be `1731` / `1058` / `2386` instead, as I don't think we've quite reached 17,311,058 teams yet :)

**Comment by fangeugene** [comment]
Awesome thanks! It is now fixed.
http://www.thebluealliance.com/event/2011va

Probably an error when we manually imported alliance selections from old events from ChiefDelphi.

**Comment by jhtervay** [comment]
Just found another issue with `2014mxmc`, I can open a new ticket if you like. If you go to https://www.thebluealliance.com/event/2014mxmc and look at the alliances you can pretty clearly see what the issue is.

It's a little odd thought that we have the brackets below on the same page though. Alliances I'd imagine are:

1. 3472 / 3478 / 3933
2. 3794 / 2283 / 3480
3. 4400 / 3526 / 5312
4. 4403 / 3158 / 4977
5. 4775 / 3522 / 4667
6. 4262 / 4735 / 5133
7. 4673 / 4635 / 4820
8. 4355 / 4401 / 4742
