### ISSUE TITLE
No alliances listed at 2014mxmc

### ISSUE THREAD

**Issue by jhtervay** [the-blue-alliance/the-blue-alliance#1658]
Related to old info from CD posts, this time with `2014mxmc`. If you go to https://www.thebluealliance.com/event/2014mxmc and look at the alliances you can pretty clearly see what the issue is.

It's a little odd thought that we have the brackets below on the same page though. Alliances I'd imagine are:

1. 3472 / 3478 / 3933
2. 3794 / 2283 / 3480
3. 4400 / 3526 / 5312
4. 4403 / 3158 / 4977
5. 4775 / 3522 / 4667
6. 4262 / 4735 / 5133
7. 4673 / 4635 / 4820
8. 4355 / 4401 / 4742

Is this issue fixable?

**Comment by fangeugene** [comment]
LOL who did that @phil-lopreiato

**Comment by fangeugene** [comment]
For posterity, because I think this is hilarious.
![image](https://cloud.githubusercontent.com/assets/1421884/19612895/4b1c44d6-97b7-11e6-8219-0df7f4f6e501.png)

**Comment by fangeugene** [comment]
Fixed
