### ISSUE TITLE
Build tool for users to request API write keys

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1659]
We can tie keys to an account, users can view keys when logged in, approval can just be a single button click instead of copy/pasting keys and sending them.

We should probably require full name and a description of their role (offseason event FTC, event organizer, etc.) when requesting keys. We already have emails associated with the account if we need to contact them.

**Comment by phil-lopreiato** [comment]
Yeah, this is a great idea. We can then display a user's API keys on their account page.
