### ISSUE TITLE
Alliance List Should Handle <8 Alliances

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1660]
http://www.thebluealliance.com/event/2016mnri

![screenshot from 2016-10-22 00-04-12](https://cloud.githubusercontent.com/assets/2754863/19616809/1f378d60-97eb-11e6-915f-692041a9e29d.png)

**Comment by fangeugene** [comment]
It does. the problem is with the importer which creates blank alliances. We should sanitize the input.

**Comment by phil-lopreiato** [comment]
Oh.... These were added via eventwizard. Guess we should filter out blanks there

**Comment by fangeugene** [comment]
This should also fix 

```
team_points[alliance['picks'][0]] = (17 - n) * multiplier
IndexError: list index out of range
```
