### ISSUE TITLE
Wrong team listed at 2011ca

### ISSUE THREAD

**Issue by jhtervay** [the-blue-alliance/the-blue-alliance#1662]
This took a bit of investigation to uncover. Not sure how it happened but it did. Anyway, at `2011ca`, TBA lists team 1366 as in attendance and also listed as having played in 10 matches (e.g. `qm_7` and `qm_20`).

Note that `2011ca` lists 64 teams in attendance but only displays 63 in the rankings. Team 1366 is not displayed in the rankings.

Going to [the official FIRST page for the event](http://www.firstinspires.org/team-event-search/event?id=5539), you can see that 1366 did not attend this event. Going into the official match results for the event shows that team 1702 actually played in matches at `2011ca` - the same matches that TBA lists as 1366 playing.

So somehow TBA lists 1366 as having played all of 1702's matches at `2011ca`.

**Comment by phil-lopreiato** [comment]
Wow, you're on fire with finding these, nice work!

Fixed: http://www.thebluealliance.com/event/2011ca
