### ISSUE TITLE
Link to "suggest offseason" on the main page

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1665]
We should try to make everything suggestions and use the #moardata Facebook group primarily for data corrections, not data entry.

**Comment by gregmarra** [comment]
I love this idea.

**Comment by fangeugene** [comment]
Alternatively, have the "Help Add Data" button link to a page that describes all the ways to add data (Suggestions, EventWizard, requesting keys once we have #1663, etc) and then have the #moardata Facebook page at the bottom as a last resort option.

**Comment by phil-lopreiato** [comment]
This is also similar to #1661, something I think we should definitely do
