### ISSUE TITLE
InvalidSenderError: Unauthorized sender

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1675]
APIWrite  emails are failing. 

http://stackoverflow.com/questions/30834395/sending-mail-by-unauthorised-sender-in-google-appengine

@gregmarra can you give contact at tba.com email permissions (I think Viewer is enough)

Then setting the sender to the contact email should work.

**Comment by phil-lopreiato** [comment]
We aren't using that email as the sender, but the service account address:
```
"{}@appspot.gserviceaccount.com".format(app_identity.get_application_id())
```

I worked on my dev instance yesterday, but I'll test it out this afternoon

**Comment by fangeugene** [comment]
That service account isn't a service account for tbatv-prod-hrd

**Comment by phil-lopreiato** [comment]
Maybe we need to make the service account? From what I read, that was supposed to be a universal solution. But I guess not...
