### ISSUE TITLE
Don't send admin notification emails if suggestions are declined

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1681]

**Comment by phil-lopreiato** [comment]
Do you mean when an invalid suggestion is submitted? Because we *should* only send it when we successfully create the suggestion: https://github.com/the-blue-alliance/the-blue-alliance/blob/master/controllers/suggestions/suggest_offseason_event_controller.py#L45

**Comment by fangeugene** [comment]
It doesn't do that for api auth requests.
