### ISSUE TITLE
paginate the 'all users' page

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1687]
![image](https://cloud.githubusercontent.com/assets/57101/19833270/02da7676-9df1-11e6-97a1-03e260b7c938.png)

**Comment by gregmarra** [comment]
We probably need:
1/ Paginate this so the page loads faster and doesn't eventually break
2/ A way to search for specific users

**Comment by fangeugene** [comment]
We can search by email. Still needs pagination.
