### ISSUE TITLE
Get Winning Alliance Of Match

### ISSUE THREAD

**Issue by KyleDavidKrueger** [the-blue-alliance/the-blue-alliance#1688]
It would be very nice to have an indicator on the Match model for what Alliance won.  Preferably, this would actually be a property of the Alliance model under the Match ("is_winner":"true"), but it could be a property of the Match ("winning_alliance":"blue").  Right now you can usually find the winner by comparing scores, but in the event of a tie, the handling is different every year.  This requires looking at the score_breakdown data that changes every year (requiring a switch case) and taking into account all of the tie-breaking logic.  While this is possible, it seems a waste that TBA has already applied this logic (probably more reliably) and already knows who won each match.  Thanks if you can help me!

**Comment by fangeugene** [comment]
Yep, this is planned.

**Comment by KyleDavidKrueger** [comment]
Awesome, Thanks! is there any way for me to "subscribe" to that change so I know when it would be done?

**Comment by bdaroz** [comment]
@KyleDavidKrueger You should get a notification from GitHub when this issue gets closed (after the work is completed).

**Comment by fangeugene** [comment]
Done in APIv3
