### ISSUE TITLE
Hanging Awards for 2006sdc

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1698]
Reported in https://www.facebook.com/groups/moardata/permalink/1243073109046315/

Find them by running `SELECT * FROM Award WHERE event = Key(Event, "2006sdc")` in the datastore GQL field. http://thebluealliance.com/event/2006sdc doesn't exist and it looks like everything has been properly migrated to http://thebluealliance.com/event/2006ca

**Comment by fangeugene** [comment]
How did he even find those awards? Where are they exposed?

**Comment by phil-lopreiato** [comment]
The team history awards endpoint for any one of those teams. For example: https://www.thebluealliance.com/api/v2/team/frc501/history/awards?X-TBA-App-Id=foo:bar:baz (which lists the award both for `2006ca` and `2006sdc`)

**Comment by fangeugene** [comment]
Fixed with

```
from models.award import Award
from google.appengine.ext import ndb
from helpers.award_manipulator import AwardManipulator

awards = Award.query(Award.event == ndb.Key('Event', '2006sdc')).fetch()
AwardManipulator.delete(awards)
```

**Comment by phil-lopreiato** [comment]
Should now be fixed once edge cache ages out
