### ISSUE TITLE
Search Nearby Result Count Issue

### ISSUE THREAD

**Issue by bdaroz** [the-blue-alliance/the-blue-alliance#1701]
When looking up teams in Isreal to see what effect that has on total registration count (See [this CD Thread](https://www.chiefdelphi.com/forums/showthread.php?t=151460&page=16)) I got an odd result set.

https://www.thebluealliance.com/nearby?year=2016&location=isreal&page=4&range_limit=250&search_type=teams

The header is reporting 103 teams, but when paging through, many of the pages show significantly less than the 20 per page listed. In fact the page above, 81-100, lists only 8 teams. Best guess, the actual number of records returned is about 2/3rds of the total listed.

**Comment by fangeugene** [comment]
Yes, this is a known bug. The count includes all teams, but the list only shows those that are competing in a given year. A fix is coming soon.
