### ISSUE TITLE
District Chairman's showing up as Regional (and twice)

### ISSUE THREAD

**Issue by MC42** [the-blue-alliance/the-blue-alliance#1711]
At MAR CMP, 1923 won the District Chairman's Award (as far as I remember.)  However, in the event overview, it is listed as a "Regional" Award, as well as awarded to another team simultaneously.  The same can be said for EI for some reason.

https://www.thebluealliance.com/event/2016mrcmp#awards

**Comment by fangeugene** [comment]
Multiple teams are awarded Chairman's and EI at the district level.

Also, FIRST calls it the "Regional" Chairman's Award for district championships, so we're sticking with it.
