### ISSUE TITLE
Create "Advanced Search" page

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1713]
Search for teams and events with advanced filters like "year" or "has CAD" or "within X miles" or "won X events"

Should be doable efficiently with the Search API. Use post update hooks to keep search index in sync with rest of db.

**Comment by runneals** [comment]
Would this also include location searching?

**Comment by phil-lopreiato** [comment]
@runneals Check out thebluealliance.com/nearby

**Comment by fangeugene** [comment]
Yes.
