### ISSUE TITLE
Update FRC API for 2017 

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1741]
Includes match breakdown and award types.

Documented changes that don't seem to be live yet:
> The Team's Home FIRST Championship has been added to the Teams endpoint
> The Team's School or Community Group name has been added to the Teams endpoint
> New event types have been added to the Events endpoint
> The address of the venue has been added to the Events endpoint
> The website of the event has been added to the Events endpoint
> 2017 Score Details Object has been posted in the score details endpoint

**Comment by inkling16** [comment]
If possible, could you guys get this going soon? I have some excel workbooks that use this api, and I would like to verify operation using week 0 data before the week 1 events start. 

Thanks, 
Caleb

**Comment by fangeugene** [comment]
FIRST doesn't have any of the data live yet. They updated their documentation, but the servers aren't.

**Comment by fangeugene** [comment]
Score Details should just work. The rest aren't really competition season relevant, so I'm moving this out of that milestone.

**Comment by ZachOrr** [comment]
Going to close this - confirmed we got all of these changes added in our API
