### ISSUE TITLE
Stop-build API endpoint

### ISSUE THREAD

**Issue by phantamanta44** [the-blue-alliance/the-blue-alliance#1750]
It would be nice to have an API endpoint somewhere that returns the stop-build day for the current season.

**Comment by bdaroz** [comment]
`/api/v3/apocalypse` ? 😁

**Comment by ZachOrr** [comment]
This is actually a fairly easy thing to derive https://github.com/the-blue-alliance/the-blue-alliance-ios/blob/master/the-blue-alliance-ios/Extensions/Calendar%2BTBA.swift#L49 (assuming build season is always some set period of time)

**Comment by bdaroz** [comment]
And moot in 2020+ anyway.
