### ISSUE TITLE
GameDay requires Flash

### ISSUE THREAD

**Issue by MC42** [the-blue-alliance/the-blue-alliance#1793]
Attempting to view GameDay on Linux doesn't work and simply returns an error to "get Flash".  I was under the impression that Twitch's player was HTML5.

**Comment by MC42** [comment]
Sorry, I made an error.  TwitchTV loads fine, but uStream's player uses Flash.

**Comment by nwalters512** [comment]
We specifically request the HTML5 version: https://github.com/the-blue-alliance/the-blue-alliance/blob/master/react/gameday2/components/embeds/EmbedUstream.js#L6

If they refuse to serve it to us, there's not much we can do :confused:

**Comment by MC42** [comment]
Dang, didn't realize that. Thanks...
