### ISSUE TITLE
Formatting is weird for multiple high scores

### ISSUE THREAD

**Issue by inkling16** [the-blue-alliance/the-blue-alliance#1798]
The formatting for multiple playoff high scores is weird. It is currently putting the Northern Lights info to the right of the Lake Superior results. 
![image](https://cloud.githubusercontent.com/assets/5760180/23589915/3c6c8ee2-019c-11e7-9978-7808ed1706ce.png)

**Comment by fangeugene** [comment]
This was fixed in https://github.com/the-blue-alliance/the-blue-alliance/commit/b3d104725e46d5a1be0e537cc93dc2768b3946d2
