### ISSUE TITLE
Fix too much caching on events for webcasts

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1809]

**Comment by phil-lopreiato** [comment]
Introduced here: https://github.com/the-blue-alliance/the-blue-alliance/commit/425b7a8485bd7c8238406f512057552a89298263

**Comment by fangeugene** [comment]
What do you guys think about temporary fixing it by dropping the cache time down from 60 min to a few minutes, and moving webcasts to EventDetails sometime in the future?
