### ISSUE TITLE
Team Repeated in MyTBA

### ISSUE THREAD

**Issue by tsteward** [the-blue-alliance/the-blue-alliance#1825]
Not sure  why, but the High Rollers were repeated in my myTBA.

![capture](https://cloud.githubusercontent.com/assets/4777935/23956158/ea22628a-0969-11e7-9b89-395a5ceb03c1.PNG)

**Comment by fangeugene** [comment]
Does refreshing fix it?

**Comment by tsteward** [comment]
No, refreshing doesn't fix it. They are also repeated in other places.

![capture](https://cloud.githubusercontent.com/assets/4777935/23956491/c8de2798-096a-11e7-901c-e1b6e9c25fbd.PNG)
![capture](https://cloud.githubusercontent.com/assets/4777935/23956536/e11fc9c4-096a-11e7-8912-36e87109cbed.PNG)

**Comment by fangeugene** [comment]
Uh what.

**Comment by tsteward** [comment]
Adding and removing the team resolved the issue. It must of somehow gotten in the database twice. I am closing this for now.
