### ISSUE TITLE
Gameday chat switching UI breaks on long event names

### ISSUE THREAD

**Issue by KevinEmery** [the-blue-alliance/the-blue-alliance#1837]
If you switch to the chat for an event with a long name (such as [PNW] Central Washington University), the text forces the arrow selector out of the view, making it impossible to switch to any other chat. Without the ability to resize the chat window width, is it possible to expand the click listener to be the entire view instead of (as it appears to be now) the arrow at the end?

**Comment by fangeugene** [comment]
Yes, the click listener should be the entire thing.
