### ISSUE TITLE
Insights Page Job + Timestamp

### ISSUE THREAD

**Issue by runneals** [the-blue-alliance/the-blue-alliance#1838]
It looks like a job hasn't been run since it shows only 96 matches played this week, which is not possible because KC ran 64 matches today (also mokc insights shows a high score of 431), even thought the insights page says it was updated at around 11 pm central tonight.
https://www.thebluealliance.com/insights/2017#year-specific-week-3

Second, can we include a timezone with the timestamp on the insights page so we know when exactly it was last ran because is that 7:10PM on the east coast or west coast or here in Iowa? Would also be nice to include a timestamp on the event insights pages (or are those being queried right from the DB?)

**Comment by fangeugene** [comment]
There was a bug in the time being shown where we were displaying page generation time, not the calculation time. The times displayed throughout the site are local time, unless explicitly stated, which should be intuitive enough.

**Comment by gregmarra** [comment]
I actually think displaying local time without a timezone is surprising. I
viewed the source to try to tell what was happening once.
