### ISSUE TITLE
Update Twitter Account

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1847]
Photo, website, whatever else.

**Comment by jaredhasenklein** [comment]
**Picture**
Is currently the old logo
![image](https://cloud.githubusercontent.com/assets/22439365/24076363/8d8081d6-0beb-11e7-9149-4aede59c45ed.png)

**Website**
Is currently listed as thebluealliance.net (lol)

**Description**
I think the description should be updated to match Facebook:
> FIRST Robotics Competition team information, webcasts, event results, videos, and more. 

Current description:
> The Blue Alliance is a resource site for teams in the FIRST Robotics Competition

**Comment by SUPERCILEX** [comment]
@phil-lopreiato or @fangeugene could either of you [email me](mailto:saveau.alexandre@gmail.com) the password so I can update the bio? Or maybe you guys could do it?

**Comment by synth3tk** [comment]
BTW, it may be a good idea to set up TBA under TweetDeck as a team, so you can hand out post-only access to the account. I'd love to help keep it updated, since I use Twitter quite a bit more than Facebook.

**Comment by andrewda** [comment]
We could also try getting [verified on Twitter](http://verification.twitter.com/welcome).

**Comment by gregmarra** [comment]
![image](https://cloud.githubusercontent.com/assets/57101/25835282/43f62c5e-3432-11e7-8e93-82fc08fe9cae.png)

**Comment by SUPERCILEX** [comment]
@gregmarra 🎉 🚀

**Comment by gregmarra** [comment]
Also requested to be verified.
