### ISSUE TITLE
Show team's overall district point breakdown

### ISSUE THREAD

**Issue by WardBenjamin** [the-blue-alliance/the-blue-alliance#1856]
Right now, a district point breakdown is computed and available for district events, but to get a team's district point breakdown overall you have to view their individual events. It would be ideal to be able to view this on their team page.

**Comment by fangeugene** [comment]
It's available on the web for district events, no?

**Comment by WardBenjamin** [comment]
(Updated original issue)

**Comment by ZachOrr** [comment]
https://github.com/the-blue-alliance/the-blue-alliance/pull/2241
