### ISSUE TITLE
More status on Event Table

### ISSUE THREAD

**Issue by jaredhasenklein** [the-blue-alliance/the-blue-alliance#1858]
I'm really liking the next match stuff on the homepage as discussed in #1842.

I think it would be cool if someone is up for coding:

- Event Approaching (date hasn't happened yet)
- No match schedule yet
- Event Complete
- Event offline (however this is determined for Android)

**Comment by fangeugene** [comment]
To help with clutter, we can consider things like adding a column, different colors for the statuses, etc.

**Comment by jaredhasenklein** [comment]
That would be awesome. There's a lot of extra space on most displays
