### ISSUE TITLE
Allow Instagram, Facebook Media

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1859]
Sometimes media is available on social networks, but not on image hosting platforms.

ie https://www.instagram.com/p/BSAm1_RlEvy/

I think we'd have to use social media embeds, because we can't get hotlinkable image URLs as easily as CD or Imgur.

**Comment by jaredhasenklein** [comment]
Even if you could get the actual image URL, at least with Facebook, the link is no longer valid after some time (similar to googleusercontent links)

**Comment by ZachOrr** [comment]
Going to close this one, since we've added support for Instagram media

**Comment by gregmarra** [comment]
I have seen several teams that are more active on FB than Instagram. We may
want to have an issue for other types of Media support in the future.
Facebook is a heavy embed widget though.
