### ISSUE TITLE
Usability bug: Can't find the tab to view teams on TBA Web

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance#1866]
I wanted to see the event's list of teams, couldn't find it, gave up, and opened the Android app instead.

<img width="1227" alt="casj" src="https://cloud.githubusercontent.com/assets/1043120/24541895/587803d4-15ae-11e7-8ba8-f0cea6259b2d.png">

After going back a few times I eventually discovered that the small text "Teams (60)" next to the big "Results" button is clickable, but it does not look like a button or a tab!

I went for another opinion. She said to say my smart wife couldn't find it, either.

It's broken.

**Comment by fangeugene** [comment]
Agreed.

**Comment by fangeugene** [comment]
Is this any better? This is what it used to be before I switched it 2 weeks ago.

![image](https://cloud.githubusercontent.com/assets/1421884/24554841/0021a268-15fd-11e7-8413-f0f09d5e0667.png)

**Comment by gregmarra** [comment]
I think the explicit tabs are clearer

**Comment by 1fish2** [comment]
Yes. The explicit tabs are much clearer.

Can you also make the tab labels larger or bolder?
