### ISSUE TITLE
Mobile Version: "Watch Now" button is hidden 

### ISSUE THREAD

**Issue by sorianog** [the-blue-alliance/the-blue-alliance#1867]
The Mobile Version of the site seems to not display the "Watch Now" button for viewing an event's stream. Switching to the Desktop Version shows the button fine.

**Comment by fangeugene** [comment]
It was purposely hidden in the past due to space reasons and because GameDay flat out didn't work on mobile. Now that it does, maybe we can bring the button back.

**Comment by sorianog** [comment]
#bringthebuttonback Would you like some help with that?

**Comment by fangeugene** [comment]
Yes please!

**Comment by sorianog** [comment]
Where should I start? I'm new to the code base :/

**Comment by sorianog** [comment]
In file ```event_details.html```, I see the following code that I think is related to this issue:

```javascript
          <div class="hidden-xs pull-right">
            {% if event.webcast %}
              {% if event.webcast_status == 'offline' %}
                <a class="btn btn-default btn-xs" href="{{event.gameday_url}}" target="_blank"><span class="glyphicon glyphicon-facetime-video"></span> Offline</a>
              {% else %}
                <a class="btn btn-success btn-xs" href="{{event.gameday_url}}" target="_blank"><span class="glyphicon glyphicon-facetime-video"></span> Watch Now</a>
              {% endif %}
            {% else %}
              <a class="btn btn-xs btn-default" href="/suggest/event/webcast?event_key={{event.key_name}}" target="_blank">Add webcast</a>
            {% endif %}
          </div>
```

What would need to be changed?

**Comment by fangeugene** [comment]
Take a look at http://getbootstrap.com/css/#responsive-utilities

the `hidden-` and `visible-` classes determine what shows up on various screen sizes. In this case, `hidden-xs` is saying "don't show this element on extra small devices (phones)" If you remove that class, it will show up on phones.

**Comment by sorianog** [comment]
Ah, that makes sense! No wonder the "xs" is there. I attempted to reproduce this issue when trying to spoof Android mobile-agent mode in Chrome but I was unsuccessful. When I visited an event on my Google Pixel though, I was able to reproduce this issue. How do you and the others test on mobile devices?

**Comment by fangeugene** [comment]
We use responsive design, so different layouts are determined by screen size, not user agent. Resizing a window on desktop is a good way to test for "mobile."

**Comment by sorianog** [comment]
Interesting. So when the browser width is <768px, that is when the button disappears (tested locally and saw that the docs say that too). Good to know.
