### ISSUE TITLE
2014abca displays wrong location

### ISSUE THREAD

**Issue by jhtervay** [the-blue-alliance/the-blue-alliance#1872]
Not sure what's going on with how you are linking locations to Google Maps links, but I think the process is a little buggy.

[2014abca (Western Canada Regional 2014) has an interesting location](http://i.imgur.com/HwzZSfj.png): Salt Lake City, UT.

The API endpoint `/api/v2/event/2014abca` returns ` { "venue_address": "The Olympic Oval\nUniversity of Calgary\n2500 University Drive NW\nCalgary, AB T2N 1N4\nCanada" }` which makes me believe that somehow "The Olympic Oval" at University of Calgary got turned into a link for "Utah Olympic Oval" out in Salt Lake City.

I have not found any other instances of this bug occurring, but it is likely more than just this event.

**Comment by fangeugene** [comment]
Oh this again. I'll fix it.

**Comment by fangeugene** [comment]
Fixed.
