### ISSUE TITLE
Change link URL to third party API

### ISSUE THREAD

**Issue by wdavies973** [the-blue-alliance/the-blue-alliance#1877]
Hi, I'm the owner of the TBA-API listed on your website. I recently made a username change and would like you to update the link to the API repository. The old link was [https://github.com/techguy9984/TBA-API](https://github.com/techguy9984/TBA-API). The new link is: [https://github.com/wdavies973/TBA-API](https://github.com/wdavies973/TBA-API).

**Comment by dracco1993** [comment]
This is a duplicate of #1913, which was already fixed and closed.
