### ISSUE TITLE
Awards at District Champs for teams who only present do not show up

### ISSUE THREAD

**Issue by kcgodzyk** [the-blue-alliance/the-blue-alliance#1888]
Example: 6324 won Rookie All Star at NE Championship
https://www.thebluealliance.com/event/2017necmp#awards

but if I go to their direct team page, I can't see that they won that award to qualify for Championship
https://www.thebluealliance.com/team/6324

Not sure if this is posted in the right place

**Comment by fangeugene** [comment]
Fixed.

**Comment by kcgodzyk** [comment]
@fangeugene Just checked on the page I sent an example of, https://www.thebluealliance.com/team/6324 and don't see their award at NE CMP.

**Comment by fangeugene** [comment]
It's back.... Let me investigate to see why it keeps disappearing.
