### ISSUE TITLE
Include districts in search.

### ISSUE THREAD

**Issue by CarlColglazier** [the-blue-alliance/the-blue-alliance#1893]
I often use the district pages, but they are rather difficult to get to at the moment. Currently, the way I get to the North Carolina district page is searching "North Carolina", clicking the [first result](https://www.thebluealliance.com/event/2017nccmp) and then clicking [*North Carolina District*](North Carolina District) at the top of the page.

It would be useful to make district pages more accessible by making districts searchable (only events and teams are searchable at the moment).

**Comment by fangeugene** [comment]
Implemented in #1896
