### ISSUE TITLE
3+1+3 GameDay view for Champs

### ISSUE THREAD

**Issue by bkeeneykid** [the-blue-alliance/the-blue-alliance#1894]
For watching champs, having the main FIRST Champ Live in the center with the six divisions around the edge would be a really good way of watching. I think having three on each side would be a good way of doing this.

**Comment by phil-lopreiato** [comment]
We really need a scalable way to build arbitrary GD layouts...

**Comment by fangeugene** [comment]
At least it's trivial to create new layouts...

![image](https://cloud.githubusercontent.com/assets/1421884/25092591/620435c4-235c-11e7-90dd-fc93772e3a52.png)

**Comment by fangeugene** [comment]
I'm going to call this "1+6"
