### ISSUE TITLE
incorrect match video

### ISSUE THREAD

**Issue by inkling16** [the-blue-alliance/the-blue-alliance#1898]
Idaho s1m2 has the incorrect video linked.

**Comment by andrewda** [comment]
This probably needs a better way of being reported. I've seen this several times, especially for matches that were replayed.

**Comment by themacman** [comment]
@andrewda Agreed. Would some sort of Google Form do the trick?

**Comment by fangeugene** [comment]
I removed the video.

@andrewda We want to implement some rating and/or removal suggestion system. Not sure if there's an existing issue for it, feel free to file one if there's not.

**Comment by tsteward** [comment]
@fangeugene @andrewda see #996
