### ISSUE TITLE
Accept streamable.com links for match videos

### ISSUE THREAD

**Issue by spinda** [the-blue-alliance/the-blue-alliance#1905]
I'm generating recordings of every match at Houston today, but they're all on streamable.com and I don't want to upload to YouTube.

**Comment by nwalters512** [comment]
A quick run through the website didn't reveal any information on embeds. Could you give us a few examples of what their embed code looks like?

**Comment by phil-lopreiato** [comment]
You can get mp4 links for a video here with their API: https://streamable.com/documentation

**Comment by fangeugene** [comment]
If we do this we should take the opportunity to start making actual Media
models for match vids

**Comment by spinda** [comment]
The embed code looks like this:

 ```html
<div style="width: 100%; height: 0px; position: relative; padding-bottom: 56.250%;"><iframe src="https://streamable.com/s/mtdwt" frameborder="0" width="100%" height="100%" allowfullscreen style="width: 100%; height: 100%; position: absolute;"></iframe></div>
```

for the link https://streamable.com/mtdwt

**Comment by ZachOrr** [comment]
Using https://github.com/the-blue-alliance/the-blue-alliance/issues/1104 as a precedent - going to close this one out
