### ISSUE TITLE
Unhack Emergency Einstein Hack

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1907]

**Comment by runneals** [comment]
Don't know if this a bug from your emergency hack, but Finals 3 is still showing up with the estimated time... https://www.thebluealliance.com/event/2017cmptx
![screen shot 2017-04-23 at 3 10 30 pm](https://cloud.githubusercontent.com/assets/1879617/25317064/056375b6-2837-11e7-80ef-8870472a058d.png)

**Comment by fangeugene** [comment]
It is.
