### ISSUE TITLE
"Championship by the Numbers" Feature Request

### ISSUE THREAD

**Issue by maxnz** [the-blue-alliance/the-blue-alliance#1915]
Would it be possible to add the Houston and St. Louis totals underneath the larger total numbers? They could be a little smaller.

Like:

                  [Total]
              HOU         STL
          [HOU Total] [STL Total]

**Comment by bdaroz** [comment]
My only problem with this is that the numbers only become comparable after St. Louis is done. What does it tell you when you see 5,101 Houston rotors and say 0 St. Louis, or maybe a few hundred shortly after matches start?

While this could be interesting after St. Louis is over, you can derive the same numbers from the field insight pages. (Admittedly kPa requires some math and is subject to rounding, but....)

**Comment by maxnz** [comment]
I still think there should be some way to determine whether the numbers are for one or both championships. I know that the code calculates both combined but the page doesn't say that. Like, what if someone saw 5,101, but checked a week later and saw 10,030 and thought that St. Louis had twice as many rotors as Houston? Maybe just something that clarifies that it is for both championships combined would be enough.

**Comment by bdaroz** [comment]
Would making "Championship" (both occurrences) above the images plural cover that, you think?

**Comment by maxnz** [comment]
Probably.

**Comment by fangeugene** [comment]
I guess this is irrelevant now.
