### ISSUE TITLE
2007 "Kansas" Regional

### ISSUE THREAD

**Issue by bkeeneykid** [the-blue-alliance/the-blue-alliance#1921]
Looking at the awards for the 2007 Greater Kansas City regional, the blue banners on team's pages show up as the "2007 Kansas Regional". I'm going to assume this isn't how the actual banners type saying the event was held in Missouri. The 2008 banners also show this, but all the years forward show "Greater Kansas City" as expected.

**Comment by fangeugene** [comment]
Fixed.
