### ISSUE TITLE
CCA and CCF banners do not list championship

### ISSUE THREAD

**Issue by dracco1993** [the-blue-alliance/the-blue-alliance#1922]
The Championship Chairman's Award and the Championship Chairman's Award Finalist banners do not list which championship they were awarded at.

[Example](https://www.thebluealliance.com/team/2614)

**Comment by legoktm** [comment]
This also affects the Winner banners too fwiw.

**Comment by dracco1993** [comment]
@legoktm Good point.  The good thing is, the way I wrote the fix, it'll add the championship city to all blue banners starting in 2017.
