### ISSUE TITLE
Incorrect Event Factored into District Ranking

### ISSUE THREAD

**Issue by JCharante** [the-blue-alliance/the-blue-alliance#1935]
## Steps to Reproduce:

1. Go [here](https://www.thebluealliance.com/events/ne/2017#rankings) to view the 2017 District Rankings for New England.
2. You will find:
    - `125` in 10th place.
    - `125` having zero district points for event.
    - If you hover over the arrow next to the zero points for `125`, a popover will appear that says `SE Mass`, with a link to [the event page](https://www.thebluealliance.com/event/2017mabri)

## Diff

All three items listed above are incorrect. According to http://frc-districtrankings.firstinspires.org/2017/NE `125` came in 5th place for the NE District and obtained 67 points from Event 1.

`125`'s first event in the NE District was [Greater Boston](https://www.thebluealliance.com/event/2017mabos) as shown on their [team page](https://www.thebluealliance.com/team/125/2017). Not SE Mass.

**Comment by fangeugene** [comment]
Fixed. The issue was that someone on 125 won volunteer of the year at SE Mass, and we counted that as the first event.
