### ISSUE TITLE
Israel districts are showing ambiguous blue banners

### ISSUE THREAD

**Issue by dracco1993** [the-blue-alliance/the-blue-alliance#1937]
(Initially brought up on the [Facebook page](https://www.facebook.com/groups/moardata/permalink/1464087356944888/).)

Basically, district blue banners from Israel aren't showing the full event name, which appears to be the only thing differentiating them, as they are all "[ISR District Event #X](https://www.thebluealliance.com/events/isr/2017)".

Here is an example of this happening: [Team 1574 - MisCar](https://www.thebluealliance.com/team/1574/2017)

**Comment by dracco1993** [comment]
FYI: I've already started to look into this.

**Comment by gregmarra** [comment]
Possibly the short event names are all the same?

**Comment by fangeugene** [comment]
Greg is right.

**Comment by dracco1993** [comment]
Yeah, I'm gonna work on a fix.

Turns out, there are other instances of this issue:
- [FIM District - Kettering University Event #1 ](https://www.thebluealliance.com/event/2017miket)
- [FIM District - Kettering University Event #2 ](https://www.thebluealliance.com/event/2017mike2)
