### ISSUE TITLE
API Page Layouts & Other Docs

### ISSUE THREAD

**Issue by bdaroz** [the-blue-alliance/the-blue-alliance#1940]
With the change to the v3 landing page, being basically just a swagger API, we've lost the links to other doc pages like `/apidocs/webhooks`, and the link to v2 is shoehorned into the v3 description.

We also don't have a place to list 3rd party libraries, ala #1938.

**Comment by phil-lopreiato** [comment]
Oh yeah, forgot about the webhooks page. We can modify the overview text, or make a generic /apidocs page that acts like more of an overall developer portal. Personally, I like the latter. 

As far as third party libraries go, we were thinking of actually auto generating/publishing them with swagger codegen tied into our existing release pipelines.

**Comment by bdaroz** [comment]
Fixed with commit 69685f616c08a58c287bf88698b188120436ceeb
