### ISSUE TITLE
Can't accept this video suggestion

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1941]
Clicking "accept" then "act on selected" returns to the same page with the same suggestion. Refreshing the page still shows it. Not sure what's happening.

Edit: Removed image due to user email -Eugene

**Comment by fangeugene** [comment]
Event doesnt exist. @phil-lopreiato probably has to do with renaming 2017bc18 to 2017bc

**Comment by phil-lopreiato** [comment]
If you change the video keys to use 2017bc, it might work?

**Comment by fangeugene** [comment]
No longer an issue.
