### ISSUE TITLE
Old(er) events not returning Alliances in APIv3

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance#1946]
Looks like some older events with alliances online aren't returning alliances via the API
Ex: `2009gg`, `2005ga`

**Comment by fangeugene** [comment]
@ZachOrr Are you sure? I don't have any record of those events ever having alliance selections (in the DB or in https://github.com/the-blue-alliance/the-blue-alliance-data) as far as I can tell.

**Comment by ZachOrr** [comment]
I mean, the 2009 Kettering event for sure had alliance selections.

**Comment by fangeugene** [comment]
Well ****

**Comment by fangeugene** [comment]
Time to dig through backups.

**Comment by fangeugene** [comment]
Miscommunication. 99% sure we never had the data to begin with.

**Comment by phil-lopreiato** [comment]
Yeah, there were some old html pages that went missing (so we never ended up with the data). I remember manually fixing 2010ct using archive.org...

**Comment by ZachOrr** [comment]
I was able to pull the data for 2009gg. Not sure where to find 2005ga... I'd be interesting to know how many one-off events like this we theoretically should have some piece of data for but don't
