### ISSUE TITLE
Event websites missing scheme do not link correctly

### ISSUE THREAD

**Issue by andrewda** [the-blue-alliance/the-blue-alliance#1949]
For example, the website on the [BunnyBots event page](https://www.thebluealliance.com/event/2017orbb) (`team1540.org/competition`) is missing a `http://` or `https://`, so when clicked it links to `https://www.thebluealliance.com/event/team1540.org/competition` instead of the actual website.

**Comment by phil-lopreiato** [comment]
Fixed https://www.thebluealliance.com/event/2017orbb manually
