### ISSUE TITLE
District rankings are innacurate

### ISSUE THREAD

**Issue by Zinka010** [the-blue-alliance/the-blue-alliance#1962]
The district rankings in the JSON for the /district/{district_key}/rankings command are inaccurate. My issue is almost identical to #1166. For example, team 33 is rank 1 in the 2017fim district according to the official FIRST rankings, but the JSON file shows them as second.

**Comment by fangeugene** [comment]
Oh this must be due to the FiM divisions this year....

**Comment by Zinka010** [comment]
It is also present in the ONT district, I have tested them and they are almost always slightly higher or lower.

**Comment by fangeugene** [comment]
Can you give an example of an error for ONT?

**Comment by Zinka010** [comment]
Team 2706, according to the official rankings is 38th according to the official rankings with 115 points. The JSON says they are 37 with 115 district points. Minor but existing.

**Comment by fangeugene** [comment]
That's due to 4343 not receiving 5 points for winning the safety award at ONNOB because the award was submitted late into FIRST's database. 4343 is bumped up to 36, which pushes 2706 down to 38.

**Comment by Zinka010** [comment]
Oh ok, thanks for the quick clarification.

**Comment by Zinka010** [comment]
This seems to have pushed around quite a few teams in the ONT district.
