### ISSUE TITLE
playoff bracket teams overlap medal icons

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1965]
![image](https://user-images.githubusercontent.com/57101/28747165-73903a1c-744d-11e7-81b2-64b1b71f29cc.png)

**Comment by fangeugene** [comment]
And the winners are wrong xD

**Comment by fangeugene** [comment]
Fixed in 53652d08f7dcd2686435d8fa1765fbdc1626246e
