### ISSUE TITLE
API Team Event Status response does not match spec

### ISSUE THREAD

**Issue by dc74089** [the-blue-alliance/the-blue-alliance#1967]
In the Team Event Status endpoint, results returned are not consistent with the spec/model posted on the `/apidocs/v3` page. The team event status endpoint (for example, `api/v3/team/frc1902/event/2017lake/status`) returns a `WLT_Record` object at `playoff.record` while the spec shows to expect a string.

**Comment by bdaroz** [comment]
I'll check into this before the weekend and issue a PR if needed. Thanks for the report!

**Comment by dc74089** [comment]
Also: in the event rankings endpoint (`api/v3/event/2017flor/rankings`), the model specifies 
```json
"record": {
        "qualifications": {
          "losses": 0,
          "wins": 0,
          "ties": 0
        },
        "overall": {
          "losses": 0,
          "wins": 0,
          "ties": 0
        }
      }
```
but the endpoint returns
```json
"record": {
        "losses": 0,
        "ties": 0,
        "wins": 8
      },
```

(shall I open a new issue, or keep this comment here?)

**Comment by bdaroz** [comment]
Here is fine.
