### ISSUE TITLE
Team ID Not Existing returns single quotes

### ISSUE THREAD

**Issue by bkeeneykid** [the-blue-alliance/the-blue-alliance#1970]
When using API V3 and searching for a team that doesn't exist (ala http://www.thebluealliance.com/api/v3/team/frc2 ) the error returned includes on single quotes, which is not only against the JSON standard but also breaks many JSON decoders, like the on used in tbapy, which I'm using.

**Comment by fangeugene** [comment]
https://github.com/the-blue-alliance/the-blue-alliance/blob/master/controllers/apiv3/api_base_controller.py#L74
probably needs to be `self.response.out.write(json.dumps(self._errors))`

**Comment by fangeugene** [comment]
The fix is live.
