### ISSUE TITLE
EventWizard uses APIv2

### ISSUE THREAD

**Issue by bdaroz** [the-blue-alliance/the-blue-alliance#1984]
https://github.com/the-blue-alliance/the-blue-alliance/blob/f5d9f855125470d9667dd60c88fbc61ef1214b7f/static/javascript/tba_js/eventwizard.js#L306

**Comment by fangeugene** [comment]
I think EW2 uses APIv3

**Comment by fangeugene** [comment]
EventWizard2 uses APIv3. EventWizard won't see any further development.
