### ISSUE TITLE
Remove team motto's if they aren't in TIMS anymore

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1994]
```We have a slogan under our team name that we want to change.  How would we do this?  We have looked on our FIRST account and can’t find it anywhere on that account to change.```

**Comment by bdaroz** [comment]
We have the same problem, however the motto is coming from _FIRST_, it's not something you can edit on TBA. That said, there is no where to edit it in TIMS anymore. We emailed _FIRST_ but have no solution yet. I strongly suggest you do the same.

**Comment by phil-lopreiato** [comment]
I'd emailed FRC about it, and they said they hope of have the ability to edit mottos restored for this season.

I think we hold off for now, but if nothing happens by kickoff, we can hide them

**Comment by bdaroz** [comment]
I don't know if hiding them all would be worse than having a few out of date.

**Comment by phil-lopreiato** [comment]
Mottos removed in https://github.com/the-blue-alliance/the-blue-alliance/commit/88b40100749dd8a914718db32c5b29e2270296db
