### ISSUE TITLE
Automatically pull from FRC API in the offseason

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#2001]
Right now we have to manually enable it for each event.

**Comment by fangeugene** [comment]
This is slightly hard, as we sometimes learn of offseasons before they're on the FRC API, so keys end up being different. We need a way to detect that two events are actually the same, or at least bug admins if new events are on the FRC API that aren't "dealt with" so we can manually link keys.

**Comment by phil-lopreiato** [comment]
I want to automatically add new events to the offseason queue where we can link the various keys

**Comment by phil-lopreiato** [comment]
This was done in 2296cadfa2848b88768ae81abdb346e1ab1c0e18 and c6e337b79ee6cc707ac9bcd5b5817251b162fa57
