### ISSUE TITLE
Match  "actual_time" providing suspicious results

### ISSUE THREAD

**Issue by bdaroz** [the-blue-alliance/the-blue-alliance#2003]
(From a CD Thread)
https://www.chiefdelphi.com/forums/showthread.php?t=159694

I have been working on a project that uses the "actual_time" api v3 response, and a couple of matches are providing extremely strange results. The most common strange result is that, for a handful of matches, the "actual_time" is about 4 hours earlier than I am expecting. This can be seen for example, in matches 56-59 at Hub City, matches 61-64 at Rock City, and matches 56-62 at Dalton. There are also a few events where the "actual_time" values are extremely strange, namely (Kettering 1, San Diego, and Los Angeles). I have attached a spreadsheet which contains scheduled times and actual times for all matches, and I have marked the matches that have suspect actual times. 

Is there a reasonable explanation for this these discrepancies that I am missing?

**Comment by inkling16** [comment]
Thanks for opening this issue. It didn't cross my mind to make an issue mainly just because I was confused by the data and thought it might be something on my end.

**Comment by fangeugene** [comment]
This looks like a bug on FIRST's side.

![image](https://user-images.githubusercontent.com/1421884/31024001-a4bb0236-a50b-11e7-8847-b0e900a46673.png)

**Comment by phil-lopreiato** [comment]
Those values are derived from the FMS server time, so it's possible the machine had the wrong time (or timezone) set and some bad data got posted

**Comment by phil-lopreiato** [comment]
Not much we can do here, I don't think
