### ISSUE TITLE
Team 2018 doesn't really exist

### ISSUE THREAD

**Issue by andrewda** [the-blue-alliance/the-blue-alliance#2006]
Probably too silly to take the time to fix any time soon. At IRI 2008, team `1018` was incorrectly entered as `2018` for one match, meaning there's an extra team `2018` with no info except for that match. https://www.thebluealliance.com/match/2008iri_qm43 – you can see team `1018` playing, not `2018`.

**Comment by phil-lopreiato** [comment]
This is actually a pretty easy fix, should be all set now
