### ISSUE TITLE
AKA not being used correctly. Should probably be renamed to Sponsors.

### ISSUE THREAD

**Issue by hook54321a** [the-blue-alliance/the-blue-alliance#2015]
On team pages there's a section for names that the team might also go by, but almost all of the time it's used to put names of companies that sponsor the team.

**Comment by andrewda** [comment]
Technically, the `AKA` is the team's official full name, which FIRST officially returns to us from their API. What's displayed at the top of the page is the team's nickname. It's true that it's usually used for name-level sponsors, but don't think we should rename it.

**Comment by phil-lopreiato** [comment]
Yeah, @andrewda is right. This is a bit of a historical artifact about the way teams used to be named (way back in the 90s), but it is _technically_ the team's full name.
