### ISSUE TITLE
Backfill DQ Data from FIRST

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#2020]
We want to hit the FRC API and store/expose the DQ/surrogate data.

However, we want to be careful about re-syncing everything from FIRST, since it may clobber any manual corrections we've made. This should depend on implementing a "whitelist" of fields that we can write due to a given FIRST API call.

**Comment by fangeugene** [comment]
Surrogates were already taken care of (we didn't have to hit the FRC API because we could determine those automagically).

2015-2017 DQ data should all be in.
