### ISSUE TITLE
Clean up Vagrant Rough Edges

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#2031]
`vagrant plugin install vagrant-share`

![image](https://user-images.githubusercontent.com/57101/32987359-5ae98c4e-cc9e-11e7-9572-76f0472238b2.png)

**Comment by phil-lopreiato** [comment]
Other stuff from @gregmarra:

ok so stuff to fix:

1/ having to touch a file in /dev-datastore
2/ add a note about what ports in the setup instructions
3/ the thing about having to install that other vagrant plugin
