### ISSUE TITLE
Multiple event IDs incorrect

### ISSUE THREAD

**Issue by dc74089** [the-blue-alliance/the-blue-alliance#2041]
The value of `first_event_id` returned by ~~`/api/v3/event/2015cacc`~~ _many events (see comment below)_ is a `string`, when the API docs specify `first_event_id` should be an `int`. 
## Expected Behavior

The values that are currently in the field `first_event_id` should be in the field `first_event_code` (expected to be a string if provided, currently null in most if not all of the events in the comment below). 
## Current Behavior

The value of `first_event_id` returned by ~~`/api/v3/event/2015cacc`~~ _many events listed below_ is a string, not an integer. 
## Possible Solution

Change value in database
## Steps to Reproduce (for bugs)

1. `curl -X GET "https://www.thebluealliance.com/api/v3/event/2015cacc" -H "accept: application/json" -H "X-TBA-Auth-Key: key"`

## Context

This mismatched value causes crashes in strongly-typed API clients that expect results returned to match the API docs. 
## Your Environment

* Version used: N/A
* Environment name and version (e.g. Chrome 39, node.js 5.4): N/A
* Operating System and version (desktop or mobile): N/A

**Comment by dc74089** [comment]
Actually, this problem is bigger than I had originally discovered. [Here is a file](https://github.com/the-blue-alliance/the-blue-alliance/files/1525365/wrong-id.txt) with the codes of all of the events that use a string for `first_event_id` instead of an integer.  Most (if not all) of these appear to be offseasons from the years 2013-2015.

**Comment by fangeugene** [comment]
Solution: the docs are wrong, fix the docs.
