### ISSUE TITLE
Import 2018 team avatars from FRC API

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#2061]

**Comment by dracco1993** [comment]
I've got something going already for this.  I'll clean it up today/tonight and get in a PR.

**Comment by fangeugene** [comment]
@dracco1993 ping

**Comment by dracco1993** [comment]
For reference:
WIP at https://github.com/dracco1993/the-blue-alliance/commit/f9d5cfb6dfa1d47fb59c9ff93962e3f46d2d8823
