### ISSUE TITLE
include Content-Type in Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by ariovistus** [the-blue-alliance/the-blue-alliance#2065]
I'm trying to hit the v3 api with whatwg-fetch, and it is balking at the preflight request, saying

```
Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.
```

So I guess it needs to be there?

**Comment by bdaroz** [comment]
@phil-lopreiato CORS is out of my wheelhouse but... https://github.com/the-blue-alliance/the-blue-alliance/blob/9601bc2ed9fdf6419b1f67211003ca870427be49/controllers/apiv3/api_base_controller.py#L113 ?

**Comment by fangeugene** [comment]
You shouldn't need to be issuing GET requests with a content-type. Try removing that header from your request.

**Comment by ariovistus** [comment]
oh, its in `access-control-request-headers`. I didn't set that; I'll see if I can clear it.
