### ISSUE TITLE
Add background to team avatars

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#2075]
Avatars are meant to be shown over blue or red, so some avatars that are only white + transparency won't show up.

This applies to individual team pages as well as the "All Avatars" page (/avatars/2018)

# Solution
Give the `team-avatar` css class a background color that's blue. If implemented properly, an icon with no transparency will not show any background.

The colors for blue and red should be: #4487da and #cd2626 respectively. If those look too dark, try #5995de and #da3434. FMS uses both those colors in their overlay.

On the all avatars page, add a button under the "For more information..." section that says "Show on red background" that, when clicked, changes the background to blue and changes the text to "Show on blue background". The scripts can be inlined using:
```
{% block inline_javascript %}
<script>
  // Code goes here
</script>
{% endblock %}
```

On the team pages, we'll just leave the blue as default and not provide a toggle. May be ugly, we'll see once we get some screenshots.

**Comment by dracco1993** [comment]
Note: we decided to use the second set of colors (#5995de and #da3434), as they look better.
