### ISSUE TITLE
Hovering over avatars in certain areas make the tooltip flash infinitely

### ISSUE THREAD

**Issue by SPCOxion** [the-blue-alliance/the-blue-alliance#2077]
## Expected Behavior

Hovering over the avatars should show a tooltip, no matter where the mouse is on the avatar

## Current Behavior

If the tooltip starts to show up where the mouse is, the site thinks the mouse isn't over the avatar anymore, and hides the tooltip. Once the tooltip is gone, the mouse is hovering over the avatar again, and thus shows the tooltip again. This repeats infinitely.

## Possible Solution

I looked around a little bit for a CSS property that causes this, but I couldn't find any. Seems like it might be an issue with Bootstrap?

## Steps to Reproduce (for bugs)

1. Go to [the avatars page](https://www.thebluealliance.com/avatars/2018)
2. Hover over any avatar
3. If it doesn't start flashing, move your mouse over the tooltip
4. If the tooltip doesn't show at all, try reloading the page and repeat 1-3

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4): Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 7, desktop

**Comment by fangeugene** [comment]
I think this is because the tooltip is on the <a> instead of <img>.
