### ISSUE TITLE
? in old GP awards

### ISSUE THREAD

**Issue by jaredhasenklein** [the-blue-alliance/the-blue-alliance#2096]
Old Gracious Professionalism Awards have a ? in place of the TM. The old FRC API spits out the name of the award with the TM symbol. TBA picked these up as a ?. The system no longer outputs with the symbol so newer events are not affected.

## Expected Behavior
`Gracious Professionalism Award sponsored by Johnson & Johnson`

## Current Behavior
`Gracious Professionalism? Award sponsored by Johnson & Johnson `

## Steps to Reproduce (for bugs)
Pre-2015 season award pages for events show the ? instead of the TM symbol.

**Comment by fangeugene** [comment]
Should be fixed now.
