### ISSUE TITLE
Robot Name

### ISSUE THREAD

**Issue by runneals** [the-blue-alliance/the-blue-alliance#2097]
Don't know if this is a issue or if it is coming from FIRST like this, but the robot name is the same as last year's robot name.
To-Do
1) Hit up FIRST API for robot names
2) Verify if 3928's robot name is "Tremor"
3) If it is, then this is not an issue. If it is not, then it is an issue.

**Comment by andrewda** [comment]
The robot name stays the same as the previous year(s) until updated by the team in STIMS.

**Comment by fangeugene** [comment]
FIRST shows "Tremor" https://frc-events.firstinspires.org/2018/team/3928
