### ISSUE TITLE
"shortName" response for API event request is not unique

### ISSUE THREAD

**Issue by inkling16** [the-blue-alliance/the-blue-alliance#2104]
## Expected Behavior

I really like the "shortName" field of an API event request. I had expected all responses to be unique, although this may not be a primary intent for this field. 

## Current Behavior

Both "IN District St. Joseph Event" and "FIM District St.   Joseph Event" return "St. Joseph" as their "shortName" response to an API call for their event info. 

## Possible Solution

I don't know a good general solution, perhaps St. Joseph could be dealt with individually (such as FiM St. Joseph and IN St. Joseph). Alternatively short district names could be appended to the front of these names, although that may be changing the intent of this field. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I'm trying to put sheet names in an excel sheet for events, and sheet names are restricted to 31 characters. 

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by fangeugene** [comment]
Short name is not intended to be unique. If you want to prepend district names/abbreviations ahead of them, you can.

**Comment by inkling16** [comment]
Okay, I thought that might be the case. I can deal with it on my side. Thanks.

**Comment by dracco1993** [comment]
If you're interested in how the `shortName`s are actually pulled out, feel free to check out the code here:

https://github.com/the-blue-alliance/the-blue-alliance/blob/96a272ecca684c6486f4d535bd87cf25545732f7/helpers/event_helper.py#L222-L268
