### ISSUE TITLE
If-Modified-Since header giving Access-Control-Allow-Headers preflight error.

### ISSUE THREAD

**Issue by emwjacobson** [the-blue-alliance/the-blue-alliance#2150]
## Expected Behavior
I am making a typical GET request to /events/2018/keys using Angular 5, after getting the response back I store the 'last-modified' header for future requests.
When I make a 2nd request, I set the If-Modified-Since header to the value from Last-Modified, and as stated in [the api docs](https://www.thebluealliance.com/apidocs).

## Current Behavior
Each GET request is preceded by an OPTIONS request, which responds with "access-control-allow-headers:X-TBA-Auth-Key".  Im not too familiar with this, and I am assuming that its allowing only the X-TBA-Auth-Key header, as when I attach the If-Modified-Since header, I get the error:
`Failed to load https://www.thebluealliance.com/api/v3/events/2018/keys: Request header field If-Modified-Since is not allowed by Access-Control-Allow-Headers in preflight response.`

## Possible Solution
Add If-Modified-Since to Access-Control-Allow-Headers?

## Steps to Reproduce (for bugs)
I have this code:
![image](https://user-images.githubusercontent.com/23322336/36881382-aa997c2e-1d82-11e8-931b-614a63ac6f78.png)

and this output in Chrome
![image](https://user-images.githubusercontent.com/23322336/36881399-bdd8ef2c-1d82-11e8-8c2e-f095c35a27e1.png)

Note, the first HttpHeaders, 300, and data is from the FIRST calling of craftTBARequest, and the 2 errors come during the SECOND request.

## Your Environment
* Version used: TBA API v3
* Environment name and version:
Angular 5
Node v6.10.2
Chrome 64
* Operating System and version (desktop or mobile):
Windows 10

**Comment by phil-lopreiato** [comment]
Yeah, this seems like a reasonable ask. Fix incoming. Thanks for filing an awesomely thorough bug report :)
