### ISSUE TITLE
Question about live match data

### ISSUE THREAD

**Issue by rjbell4** [the-blue-alliance/the-blue-alliance#2160]
Sorry, this just a question, but I don't know how else to contact the team.

While watching the "mawor" event, I see near-live "Current Match" data in the "Event in progress" panel.  Where is this data coming from?  I query the FRC REST API for my own tool, but I wasn't aware of any access to such data.  Understanding the source of the data could be very helpful to me.

Thanks!

**Comment by andrewda** [comment]
We're using computer vision to access data from the Twtich livestream. Still very early in its development, but it's shaping up to be something pretty cool!

https://github.com/the-blue-alliance/gdcv-backend
https://github.com/andrewda/frc-livescore

**Comment by rjbell4** [comment]
Wow, nice!
