### ISSUE TITLE
Implement Shadow-Bans for SPAMers

### ISSUE THREAD

**Issue by bdaroz** [the-blue-alliance/the-blue-alliance#2174]
For accounts that submit SPAM or inappropriate images or videos, implement an admin-set shadow ban. All submissions should be routed to /dev/null w/o informing the user.

**Comment by phil-lopreiato** [comment]
A few cases:
 - Make sure this also works for app submissions (and end up returning a dummy response): https://github.com/the-blue-alliance/the-blue-alliance/blob/master/mobile_main.py#L263
 - For submissions that come up with a deletehash (images the app uploaded to imgur), we can just [delete the image](https://apidocs.imgur.com/#949d6cb0-5e55-45f7-8853-8c44a108399c)
