### ISSUE TITLE
API V3 [/team/{team_key}/districts]: received != model

### ISSUE THREAD

**Issue by rakusan2** [the-blue-alliance/the-blue-alliance#2183]
I have tried out the `/team/{team_key}/districts` endpoint of V3  with `team_key = frc3571` in the "Try it out" section of the site and received this:
```json
[
  {
    "abbreviation": "ont",
    "display_name": "Ontario",
    "key": "2017ont",
    "year": 2017
  },
  {
    "abbreviation": "ont",
    "display_name": "Ontario",
    "key": "2018ont",
    "year": 2018
  }
]
```

Expected Value Model:
> A key-value pair with year as key and district key as value
```ts
{
  [year: number] : string
}
```

Enviroment:
  * https://www.thebluealliance.com/apidocs/v3 on March 5 / 2018

**Comment by phil-lopreiato** [comment]
Ah yeah, the docs are wrong here. Thanks for calling this out!
