### ISSUE TITLE
Nearby team search broken for 2018

### ISSUE THREAD

**Issue by jaredhasenklein** [the-blue-alliance/the-blue-alliance#2201]
When using the nearby search feature, there are no results returned for 2018 teams.

## Expected Behavior
When typing in a team number and location at https://www.thebluealliance.com/nearby there should be a list of teams matching the criteria returned. 

## Current Behavior
Nothing is being returned for queries like teams within 500 miles of Los Angeles for the 2018 season. This works with 2017 teams and with 2018 events so it appears that the issue is isolated to just 2018 teams.

## Steps to Reproduce (for bugs)

- [Broken search](https://www.thebluealliance.com/nearby?year=2018&location=Los+Angeles&range_limit=500&search_type=teams
)

![image](https://user-images.githubusercontent.com/22439365/37495176-5f63f90e-2869-11e8-89c7-c7d57396f3cb.png)

## Context
Can't search for 2018 teams which is need to do something like finding local rookies or something.

**Comment by dracco1993** [comment]
Interesting.  I can reproduce the issue, but looking through the code, nothing jumps out right away:
https://github.com/the-blue-alliance/the-blue-alliance/blob/ea263d172a89bc946124ac460df178a7ecf0d53a/controllers/nearby_controller.py#L14
https://github.com/the-blue-alliance/the-blue-alliance/blob/ea263d172a89bc946124ac460df178a7ecf0d53a/tba_config.py#L8

It seems like that should work.  🤔

**Comment by fangeugene** [comment]
Issue: we disabled normalized locations for teams (because they were inaccurate), but the search index requires it to know a team's lat/lng.

**Comment by fangeugene** [comment]
https://github.com/the-blue-alliance/the-blue-alliance/blob/master/helpers/search_helper.py#L37

**Comment by fangeugene** [comment]
Hang on that shouldn't be the whole problem...

**Comment by fangeugene** [comment]
The issue is twofold: 1) new teams dont have normalized_locations, and 2) there's no job that builds search indexes for a given year.

**Comment by fangeugene** [comment]
We need a task like this one, but for nearby search not advanced team search.
https://github.com/the-blue-alliance/the-blue-alliance/blob/98ab5e922b15fe5c3088934fbf430c6994eafe7c/cron_main.py#L77
