### ISSUE TITLE
GameData for 2018 is always red-alliance relative.

### ISSUE THREAD

**Issue by JacisNonsense** [the-blue-alliance/the-blue-alliance#2210]
Score breakdowns for `tba_gameData` are the same for red and blue breakdowns. In this case, it always shows the gamedata string for the red alliance (it has to be inverted for the blue alliance).

Issue stems from here: 
https://github.com/the-blue-alliance/the-blue-alliance/blob/master/datafeeds/parsers/fms_api/fms_api_match_parser.py#L264-L273

**Comment by JacisNonsense** [comment]
Nevermind, I made an error here

**Comment by fangeugene** [comment]
I've had about 5 people tell me we were doing it wrong for the same reason :P

**Comment by bdaroz** [comment]
_raises hand_ ☹️
