### ISSUE TITLE
Feature Request: Make Team pages more mobile friendly

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#2217]
## Current Behavior
Some improvements are possible to team pages on phones.

![image](https://user-images.githubusercontent.com/57101/37883905-1a51d736-3062-11e8-8b6f-e9a0bbda1636.png)

## Possible Solution
1. Rename "Media" -> "Photos & Videos" in the left nav, and remove the sub-items. It's very rare you'd want to see one without the other, and this makes the page 2 items shorter.
2. Remove the "like button" "google+ button" and "Live Data: At the Control" row – these are almost never used.
3. Hide "Add CAD Model!" button that appears on top of page to make page shorter.
4. Similar change to actual "Media" section as to the left-nav to remove headers and make page shorter.

## Steps to Reproduce (for bugs)
Visit a team page like https://www.thebluealliance.com/team/5507 on a narrow browser

**Comment by pordonj** [comment]
Made a PR for this: #2218
