### ISSUE TITLE
Media Suggestion Review Github Card Previews Flaky

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#2235]
I've filed this issue against the project we use to render these cards.

https://github.com/lepture/github-cards/issues/57

**Comment by gregmarra** [comment]
There was a bug in the parent project for Gh accounts with no display name,
just usernames. I filed an issue upstream and do not recall whether it was
resolved.

**Comment by bdaroz** [comment]
Upstream resolved the issue and published Apr 19th. We should test/check to make sure this works and then close.

**Comment by ZachOrr** [comment]
Going to resolve this one - we pull latest, and the issue should be fixed upstream, so this should be fixed.
