### ISSUE TITLE
Some alliances for 2018micmp are unknown

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#2252]
Probably has to do with the playoff type.

**Comment by ZachOrr** [comment]
@fangeugene Is this still true? Alliances look right to me for 2018micmp

**Comment by fangeugene** [comment]
I'm not sure anymore... I admit this is a pretty vague issue.

On Dec 29, 2018 8:05 AM, "Zachary Orr" <notifications@github.com> wrote:

@fangeugene <https://github.com/fangeugene> Is this still true? Alliances
look right to me for 2018micmp

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/the-blue-alliance/the-blue-alliance/issues/2252#issuecomment-450502587>,
or mute the thread
