### ISSUE TITLE
Sorting events on team pages

### ISSUE THREAD

**Issue by runneals** [the-blue-alliance/the-blue-alliance#2258]
Has anyone thought about sorting pages where the latest event is at the top, and the first event is at the bottom so you don't have to scroll down as far to see the latest and greatest?

**Comment by gregmarra** [comment]
The disadvantage to this is that several unplayed Events may be at the top. A smarter "current event" hoist might be the elegant way to fix this.

I'm going to close this issue to try to minimize our open issues, but it's a good idea for the future.
