### ISSUE TITLE
Convert GCM to Firebase

### ISSUE THREAD

**Issue by tweirtx** [the-blue-alliance/the-blue-alliance#2268]
## Expected Behavior

Google is deprecating GCM next year, and I think it would be best to have the transition done well before it's a time sensitive issue.
## Current Behavior

Use Firebase Cloud Messaging over GCM.
## Steps to Reproduce (for bugs)

N/A
## Context

If this issue is not taken care of by April 2019, notifications will stop working.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
N/A

I'll claim this issue but I can't assign myself to it.

**Comment by ZachOrr** [comment]
We need to consider how moving will affect existing mobile users. Is FCM backwards compatible with our GCM notifications? If not, we should leave both side-by-side and try to push users to update, and then kill GCM at the latest possible date.

**Comment by bdaroz** [comment]
https://developers.google.com/cloud-messaging/android/android-migrate-fcm

This looks like a good off-season project. It's not clear when the server side flips to FCM if GCM clients will continue to receive messages (eg Android App). We should aim for a lull in events in the off season to roll this out.

**Comment by tweirtx** [comment]
I'm planning on doing this off-season. I think it will break compatibility with GCM so the Android app will need to be updated at the same time.

**Comment by gregmarra** [comment]
We have very high upgrade rates so if we change after this season we will
have almost everyone on the latest version.

**Comment by fangeugene** [comment]
It helps that we have a way to show/force latest update.

**Comment by tweirtx** [comment]
Turns out the migration will not break compatibility with the current app version, after doing further research. I've opened a PR to make the server side changes.

**Comment by phil-lopreiato** [comment]
Done in https://github.com/the-blue-alliance/the-blue-alliance/pull/2276, minor fix in 3c72a6d1d90510192b3bfa68d8678691f776ebb7
