### ISSUE TITLE
API to submit videos?

### ISSUE THREAD

**Issue by rjbell4** [the-blue-alliance/the-blue-alliance#2273]
I have taken a lot of match videos. Is there an API to submit videos? Also, is there any way to expedite their acceptance?

**Comment by fangeugene** [comment]
How many videos are you talking about? You can submit videos in batch using YouTube playlists and by clicking the "Add Match Videos" button on event pages.

**Comment by rjbell4** [comment]
I have videos for all off the Darwin event at the Championship.  They are all in a playlist, so that makes it easy.  It would be easier yet if I followed a naming convention that allows the matches to be automatically identified.

Oh... but I'm not supposed to submit videos from the FIRST-provided Twitch stream?

**Comment by bdaroz** [comment]
No videos from any official FIRST channels, including the Champs stream, or any of the Webcast Unit streams. FIRST HQ will post those themselves and will link them to the matches automatically.
