### ISSUE TITLE
Events Pages for years prior to 2009 are messed up

### ISSUE THREAD

**Issue by inkling16** [the-blue-alliance/the-blue-alliance#2285]
When selecting years prior to 2009 on the Events page, the page formatting gets severely messed up, with the title and navigation bar overlapping the event data. 

## Current Behavior

![capture](https://user-images.githubusercontent.com/5760180/40066622-2ca77fea-582a-11e8-81a4-300fc2bb4d1f.PNG)

## Steps to Reproduce (for bugs)

1. Go to Events page
2. Select a year prior to 2009
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by fangeugene** [comment]
https://github.com/the-blue-alliance/the-blue-alliance/commit/1290f4d8e94e05c820a1a17c3ce2e926a5e37ee0#diff-e2b5c0b12100ad37117605d8427c1225R48

Closing dif needs to be after `endif`.
