### ISSUE TITLE
Team list incorrect for /event/2018bc

### ISSUE THREAD

**Issue by jcorcoran** [the-blue-alliance/the-blue-alliance#2294]
I'm not sure if an issue against this repo is the right place to report this problem... not sure where else it should be reported.

It looks like the Team List page for the 2018bc event (https://www.thebluealliance.com/event/2018bc#teams) is incorrect. Maybe this list reflected a preliminary list of teams at some point? It doesn't seem to match up with who actually played in matches at this event. 

I believe this discrepancy is leading to the 2018bc not showing up on team pages for the 2018 season, as well as having it show up for teams who were not in attendance.

## Expected Behavior
Teams List should reflect teams who were at the event.

## Current Behavior
Team List includes teams who didn't play in a match at the event (4564, 4796, 4908, 5030, 5686).
Team List is missing teams who played in matches at the event (2168, 4987, 5494, 5943).

**Comment by ZachOrr** [comment]
The team list looks right, based on the issue details.
