### ISSUE TITLE
HTTP Redirect doesn't map URL correctly

### ISSUE THREAD

**Issue by bdaroz** [the-blue-alliance/the-blue-alliance#2298]
Going to `https://thebluealliance.com/` correctly results in a HTTP 301 redirect to `https://www.thebluealliance.com/`.

However, `https://thebluealliance.com/somevalidpage` incorrectly gives an HTTP 301 redirect to `https://www.thebluealliance.com/`, as opposed to `https://www.thebluealliance.com/somevalidpage`.

**Comment by fangeugene** [comment]
This should be fixed now?

**Comment by bdaroz** [comment]
LGTM, Closing.
