### ISSUE TITLE
2019 Championship N/S Assignments Unfilled

### ISSUE THREAD

**Issue by MC42** [the-blue-alliance/the-blue-alliance#2303]
## Expected Behavior
2019 team country / state locations should probably be loaded at some point such that Team pages don't break when set for 2019.

## Current Behavior
Date range is only set for 2017 / 2018.

## Possible Solution

Build map for 2019 using maps published by FIRST.
https://www.firstinspires.org/robotics/frc/blog/2019-cmp-maps-control-system-poster
File in reference is at `/helpers/champ_split_helper.py`

## Context

This issue hasn't effected me yet, but it is a change that will have to be made eventually.

**Comment by ZachOrr** [comment]
Fixed via https://github.com/the-blue-alliance/the-blue-alliance/pull/2660
