### ISSUE TITLE
Texas district event listings are 404'ing

### ISSUE THREAD

**Issue by dracco1993** [the-blue-alliance/the-blue-alliance#2310]
## Expected Behavior
https://www.thebluealliance.com/events/tx/2019 should show the listing of Texas district events.

## Current Behavior
![](https://i.imgur.com/vsz2jOF.png)

## Possible Solution
Honestly, not sure exactly.

## Steps to Reproduce (for bugs)
1. https://www.thebluealliance.com/events/tx/2019
2. ???
3. 😭 

## Context
TBA ❤️ Texas

## Your Environment
N/A

**Comment by dracco1993** [comment]
I'm starting to look into a fix now.

**Comment by dracco1993** [comment]
So, it appears to me that it's a data issue, not a code issue:
I ran the [2019 event import](http://localhost:8080/backend-tasks/get/event_list/2018) locally, and everything is working fine:

![](https://i.imgur.com/uXvCumS.png)

So maybe we just need to run the [`prod` 2019 event task](http://thebluealliance.com/backend-tasks/get/event_list/2019) again?

**Comment by fangeugene** [comment]
It's a combo of both.
