### ISSUE TITLE
schema.org event markup errors - 

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#2313]
## Errors reported by Google in Search Console
http://www.thebluealliance.com/event/2015onffj | Fall Fiesta (Junior) 2015 | 6/29/18
http://www.thebluealliance.com/event/2016txrrr | Rattlin' Robot Rodeo 2016 | 6/29/18

**Comment by gregmarra** [comment]
Interesting these were on the non-https urls, so idk

**Comment by bdaroz** [comment]
Some of the HTTPS redirect was a bit funky back in June, I wonder if that's the reason....

**Comment by bdaroz** [comment]
Spoke too soon:

https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.thebluealliance.com%2Fevent%2F2016txrrr

No location for property in the schema for either event.

**Comment by ZachOrr** [comment]
I can own this one - we need to do some work on the markup for [Spotlight search on iOS](https://github.com/the-blue-alliance/the-blue-alliance-ios/wiki/Search), I can take a look at fixing this while I'm working on that.
