### ISSUE TITLE
Some team's* current event does not show up on their page

### ISSUE THREAD

**Issue by JonathanLindsey** [the-blue-alliance/the-blue-alliance#2324]
## Expected Behavior
Going to thebluealliance.com and putting any team number in the search box in the upper right corner should list all in-season and off-season events the team is in for the current season including the event they are currently competing in (of course only the events that are in the system).

## Current Behavior
**This appears to have only been an issue during the event.**
I only saw this issue for 1 team but they may have been more. On team [1094's page](https://www.thebluealliance.com/team/1094) (by putting the number in the search box, the Cow Town ThrowDown shows up. However, team 1986 is playing at the Cow Town ThrowDown but the event does not show up on [their page](https://www.thebluealliance.com/team/1986) which I got to the same way. But once on that page if I selected 2018 Season from the dropdown in the upper left I get sent to [a different url](https://www.thebluealliance.com/team/1986/2018) that has the Cow Town ThrowDown. 1986's number appeared as it should on the event's page and clicking 1986's number from the event would take me to the working url.

## Context and Environment
I saw this issue on 10/27/2018 throughout the Cow Town ThrowDown event but now that the event has ended both pages work correctly.
I saw this on thebluealliance.com public website.

## Your Environment

* Version used: I don't know how to find this but it was on 10/27/2018.
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox
* Operating System and version (desktop or mobile): Desktop, Windows 10

**Comment by bdaroz** [comment]
This is a result of the caching TBA uses. (You can read more about it here: https://blog.thebluealliance.com/2017/06/01/tech-talk-how-tba-scales-to-handle-competition-season-load/).

All three pages you linked now have the Cow Town ThrowDown listed.

**Comment by phil-lopreiato** [comment]
Yeah, this is an artifact as the way TBA does caching. There are ways around this, mostly in the $$$ or PWA spaces
