### ISSUE TITLE
Fix `null` API returns for endpoints returning objects without data

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance#2333]
The API returns `null` when it should be returning empty objects for endpoints where data doesn't exist. We see this in a handful of endpoints - for this ticket, I'll use rankings as an example.

## Expected Behavior
An API endpoint, ex `/event/{event_key}/rankings` should return an empty rankings object when no rankings exist for the event.

## Current Behavior
Sometimes we return an empty rankings object, sometimes we return a `null`

## Steps to Reproduce (for bugs)
1. `curl -H 'X-TBA-Auth-Key: {auth_key}' http://thebluealliance.com/api/v3/event/1992cmp/rankings`
2. Get a `null` back instead of an empty rankings object
3. `curl -H 'X-TBA-Auth-Key: {auth_key}' https://www.thebluealliance.com/api/v3/event/2001gal/rankings`
4. Get an empty rankings object back

## Context
This seems like a broken promise from the API

**Comment by gregmarra** [comment]
A similar issue was reported to us by email about the /api/v3//team/.../event/.../status endpoint, which it feels like /should/ have data for this event.

https://www.thebluealliance.com/api/v3/team/frc5943/event/2018bc/status

![image](https://user-images.githubusercontent.com/57101/49333607-989a5f80-f576-11e8-9a14-ea5b6667ba41.png)
