### ISSUE TITLE
Team colors should be an api field

### ISSUE THREAD

**Issue by inkling16** [the-blue-alliance/the-blue-alliance#2387]
I want to make more pretty charts like this one: https://frcdesigns.files.wordpress.com/2019/01/1st.png?w=680
Without having to manually figure out each team's primary/secondary colors. 

## Expected Behavior

I want to be able to query primary/secondary color fields in the api and get values returned as hex codes. I'd be happy to help collect this data

## Current Behavior

There is nothing like this to query in the api

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I just think it would be cool and would allow for prettier charts in the future. 

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by bdaroz** [comment]
Question: Where would we source that data?

**Comment by inkling16** [comment]
I was thinking some massive spreadsheet that we crowdsource data for. Alternatively maybe have the team media contact set it?

**Comment by fangeugene** [comment]
This is something we've wanted to do for a long time, and the team media
admin makes this more possible than before. Still a huge undertaking
though.

**Comment by inkling16** [comment]
Just saying... I think I've got interest: https://blog.thebluealliance.com/2019/01/23/1114-is-frcs-greatest-dynasty/#comment-3556

**Comment by ZachOrr** [comment]
Hey Caleb - I'm going to close out this ticket, but I wanna explain why quick.

This doesn't feel like a great offering for our platform. We largely focus on serving FIRST data. We've extended beyond that slightly with user curated media, and some of the time series stuff with GDCV, but I wouldn't call those our "core offerings". Ex: If GDCV time series data went away one day, I'm not sure anyone would mind.

Team colors assumes a few things. First, that we have somewhere to draw team colors. We probably wouldn't want to user-curate this (we already do so much curation, and curation requires manpower, and we don't have manpower for the most part), so we'd need... maybe logos? We don't currently have logos, and we don't currently accept logos, so we'd have to start with that.

Then we'd need to work on an algorithm to derive colors from the logos. This is fairly trivial, but not all teams will want their colors to be those colors. Maybe a team uses black as a main color and blue as an accent color in their logo, but all of their branding uses blue. If we were to build this for a reason (ex: using it on a Team page), people would probably ask for it to be changed, and we're back to curating colors.

Additionally, with the limited manpower we have, we have a lot of existing higher priority things to work on. I can't imagine this will rise to the top, especially not until we see how the modtools stuff shakes out. This seems like a neat idea, though! TBA just isn't a great home for it right now.

**Comment by inkling16** [comment]
No worries man, just thought I'd throw it out there. 

Someday I'll get around to contributing to development, and then I can tackle any weird pet projects I have in mind.
