### ISSUE TITLE
Development Environment setup not working out-of-the-box

### ISSUE THREAD

**Issue by Thing342** [the-blue-alliance/the-blue-alliance#2398]
Attempted to set up a development stack this evening using the docker+vagrant configuration in [this article](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/docs/dev-container.md). After following all of the steps (provisioning container, running `vagrant up` again, starting rsync, etc...), I am unable to connect to the main web UI through localhost:8080.

## Expected Behavior

A request made from the browser to `localhost:8080` should load the development instance, or at least return an HTTP response.

## Current Behavior

On host: HTTP request hangs and spins indefinitely
On container: The GAE tmux panel loops the following error:
```
ERROR    2019-02-16 05:39:41,595 instance.py:280] Cannot connect to the instance on localhost:21010
Traceback (most recent call last):
  File "/google_appengine/_python_runtime.py", line 103, in <module>
    _run_file(__file__, globals())
  File "/google_appengine/_python_runtime.py", line 97, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 28, in <module>
    from google.appengine.api import rdbms_mysqldb
  File "/google_appengine/google/appengine/api/rdbms_mysqldb.py", line 74, in <module>
    from MySQLdb import *
AttributeError: 'module' object has no attribute 'NULL'
```
Other notes: All tests run via `paver test` pass, and bootstrapped data appears to load without issue. I can access the GAE interface over `localhost:8000`.
## Possible Solution

It appears MySQL isn't starting. Unsure of the cause otherwise. If there's a step in the documentation I'm missing, please let me know.

## Steps to Reproduce (for bugs)

1. Follow the instructions as listed here: (https://github.com/the-blue-alliance/the-blue-alliance/blob/master/docs/dev-container.md)
2. On the container, run `paver test` to verify that tests pass.
3. Attempt to connect to `localhost:8080` via web broswer.

## Context

Attempting to setup development environment. This project can be intimidating to new developers due to the large number of different components with little documentation as to how they fit together. If the happy path mentioned in the setup doc doesn't work, I suspect most won't bother.

## Your Environment

* Version used: Cloned from master
* Environment name and version:  Docker 18.09.2, Vagrant 2.2.3
* Operating System and version (desktop or mobile): MacOS Mojave

**Comment by ZachOrr** [comment]
I'm unable to replicate this - but someone else might be able to. Can you confirm you don't have a MySQL server running locally already? That would be my guess about why it can't bind to that port.

**Comment by Thing342** [comment]
I don't have MySQL installed. I ran a port scan, and I shouldn't be blocking any ports.

**Comment by ZachOrr** [comment]
I'm running in to this issue as well now - will work to debug and resolve.

**Comment by ZachOrr** [comment]
For anyone else interested - this seems to be happen at startup with any service that's using `dev_appserver.py`

```
Traceback (most recent call last):
  File "/google_appengine/_python_runtime.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/google_appengine/_python_runtime.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 28, in <module>
    from google.appengine.api import rdbms_mysqldb
  File "/google_appengine/google/appengine/api/rdbms_mysqldb.py", line 74, in <module>
    from MySQLdb import *
AttributeError: 'module' object has no attribute 'NULL'
```

It looks like the version of `MySQLdb` we're using is `1.4.2.post1` - which we're getting from [`mysqlclient`](https://github.com/PyMySQL/mysqlclient-python) inside of [`travis_requirements.txt`](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/travis_requirements.txt#L16). Since we don't have that version pinned, my guess is we're using a bork'd version, and we could pin it to an old version and fix the problem. I'll try to figure out which version works best for us.

I'm not entirely sure why we're using `mysqlclient` instead of using [`MySQL-python`](https://pypi.org/project/MySQL-python/), but I'll try to look.

**Comment by ZachOrr** [comment]
@Thing342 Hey Wes - you should be good to go on this one. Follow the steps to [reprovision your container](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/docs/dev-container.md#reprovision-your-container) to make sure you've got a fresh dev env.
