### ISSUE TITLE
Average Win Margin 2019 displays very precise decimal values on the axis

### ISSUE THREAD

**Issue by snydecor000** [the-blue-alliance/the-blue-alliance#2426]
Average Win Margin in the 2019 insights page displays too many decimal places on the axis.  It makes it so you can’t view the actually relevant information.  This happens on every web browser I have tried so far.

## Expected Behavior
A nice axis which only displays 1 decimal place per axis value

## Current Behavior
Axis values currently have a lot of decimal places

## Possible Solution
Truncate after one or two decimal values.  This is probably a floating point error.

## Steps to Reproduce (for bugs)
1. Go to the 2019 insights page on a web browser

## Your Environment
I tested for the bug on a variety of devices and browsers.  Bug occurs in current versions of chrome, safari, firefox, and Microsoft edge.  I was using a Windows 10 laptop and an iPhone SE.

**Comment by dracco1993** [comment]
Confirmed on https://www.thebluealliance.com/insights/2019:
![image](https://user-images.githubusercontent.com/1204591/53689257-d0ed3d80-3d1f-11e9-8a81-34bb4b9cbae9.png)

**Comment by andrewda** [comment]
Hmm... This seems like an issue in [xCharts](https://github.com/the-blue-alliance/the-blue-alliance/tree/master/static/xcharts) which hasn't been touched in 6+ years. If someone wants to mess around with it a bit, it'd probably be good to truncate those y-axis labels to at most 2 decimal places.

**Comment by gregmarra** [comment]
We could also migrate chart libraries to something more maintained, if that
ends up being easier.

**Comment by fangeugene** [comment]
Looks like with new data with a larger range, this has fixed itself. We will definitely use a new chart library when the PWA gets made.

![image](https://user-images.githubusercontent.com/1421884/53697598-e9516c80-3da0-11e9-95fb-e3c5244506e6.png)
