### ISSUE TITLE
Notification bug still exists for me

### ISSUE THREAD

**Issue by YairZiv5951** [the-blue-alliance/the-blue-alliance#2440]
TBA App on my phone still crashes when trying to send MyTBA notifications.

## Expected Behavior
Notification when a team is about to play/score uploaded/etc.
Notification log in Recent Notifications tab

## Current Behavior
Application crashes, no notifications found in the app.

## Steps to Reproduce (for bugs)
1. Add team to my TBA
2. wait

## Your Environment
* Device: Xiaomi Redmi Note 4
* Version used: 5.1.1 
* Environment name and version (e.g. Chrome 39, node.js 5.4): Android 
* Operating System and version (desktop or mobile): 6.0 MRA58K
* MIUI version: 10.2
* Kernel Version 3.18.22+

**Comment by YairZiv5951** [comment]
What I have tried:
Switching google account
Downloading the 5.1.1 version apk from APKMonk
Cache resetting
Uninstall + Reinstall a couple of times
Switching google account and having only one team in favorites/subscribed

**Comment by ZachOrr** [comment]
This should be fixed with https://github.com/the-blue-alliance/the-blue-alliance/pull/2500 and https://github.com/the-blue-alliance/the-blue-alliance-android/pull/917 - update to Android v5.1.5
