### ISSUE TITLE
The play icons don't appear for some matches

### ISSUE THREAD

**Issue by ofekashery** [the-blue-alliance/the-blue-alliance#2445]
We sent the [match playlist](https://www.youtube.com/playlist?list=PLK98d71IHr-Xl8exXKOsE7sEnAkD7r_FS) for [``2019isde2``](https://www.thebluealliance.com/event/2019isde2), it appears to be added to each match, but not all the play buttons appear on the event page.
![image](https://user-images.githubusercontent.com/16443111/54083949-41edb000-4333-11e9-8ef9-a646a8370f64.png)

**Comment by gregmarra** [comment]
The HTML for this page was cached. Clearing the cache has fixed the issue, and play icons appear for all matches.

**Comment by ofekashery** [comment]
Ah okay, make sense. Looks like the cache doesn't clear after a suggestion is approved.
