### ISSUE TITLE
The events are not in their real week

### ISSUE THREAD

**Issue by ofekashery** [the-blue-alliance/the-blue-alliance#2454]
For example
The ISR #1 should be on week 2, not 1
The ISR #3 should be on week 3, not 2
The ISR District Championship  should be on week 6, not 5

**Comment by fangeugene** [comment]
Dupe of #2453. FIRST starts their weeks on Mondays. TBA starts weeks on Thursdays.

**Comment by fangeugene** [comment]
Seems like this has always been a problem. It just wasn't obvious until we started putting week labels on everything.

**Comment by ZachOrr** [comment]
Spot-checking from 2009 forward, this looks like a problem in 2018/2019. We've fixed this for 2020.
