### ISSUE TITLE
Results not showing on main event page, yet results are there

### ISSUE THREAD

**Issue by Nate2019** [the-blue-alliance/the-blue-alliance#2465]
Using the LA North Regional for example, as you can see in the screenshots attached, the results for Quarters 1- M3 were on the site and are able to been seen when you click on the match's page, but the results doesn't show up on the main event page until a few minutes after the results have been posted to the match page. 

<img width="465" alt="Screen Shot 2019-03-17 at 5 21 20 PM" src="https://user-images.githubusercontent.com/7596387/54498807-9071f000-48d9-11e9-9bd5-8124c4107fda.png">
<img width="869" alt="Screen Shot 2019-03-17 at 5 21 24 PM" src="https://user-images.githubusercontent.com/7596387/54498808-9071f000-48d9-11e9-889d-2bfaf4381095.png">

**Comment by ZachOrr** [comment]
Could be a cache thing? They're showing up for me.

**Comment by Nate2019** [comment]
Yeah it's showing for me now as well, but it's weird that results were on the match page, but not the event home page. 

and I wouldn't know if its a cache thing since I don't fully understand cache...
