### ISSUE TITLE
Request for OnShape to be a supported format for CAD

### ISSUE THREAD

**Issue by smitty1707** [the-blue-alliance/the-blue-alliance#2469]
## Expected Behavior

Many teams have been migrating to online only CAD packages for their robot designs. It would be great if TBA supported these new types of online CAD tools as valid entries for the robot CAD field. (OnShape being the most widely used -- to my knowledge)

## Current Behavior

Currently, attempting to add an onshape line to the media field results in an error for an unsupported format.

## Steps to Reproduce (for bugs)

N/A

## Your Environment

N/A

**Comment by jaredhasenklein** [comment]
Also would like to note that there are several FIRST Alumni who work at OnShape and have been working with FRC teams to tailor the platform towards their needs. If contacting these people would be helpful, anyone can feel free to ask me on Slack.

**Comment by bjmboy** [comment]
please

**Comment by phil-lopreiato** [comment]
This is a good place for a new contributor to make some impact - I'd be happy to show anyone how to implement this, if they're interesting in taking a stab at it :)

**Comment by jaredhasenklein** [comment]
Don't currently have the time to try and build this but I've been doing some detective work for anyone who wants to build this.

To get a screenshot/thumbnail:

If your public document links is 

1. `https://cad.onshape.com/documents/58ae7f2f1173be0f8386d6ab/w/1e7ab48f638b05adf8bcdc25/e/4d75d5bfbfafd244bc464f02`, you need to extract the part after `/documents/` and before `/e/.
2. So, you'll get something like **`58ae7f2f1173be0f8386d6ab/w/1e7ab48f638b05adf8bcdc25`**.
3. Then, you need to plug it in to the URL `https://cad.onshape.com/api/thumbnails/d/[document-key]/s/300x300` so you'll get something like **`https://cad.onshape.com/api/thumbnails/d/58ae7f2f1173be0f8386d6ab/w/1e7ab48f638b05adf8bcdc25/s/300x300`** for the example document.
4. The part after `/s/` is the size. Options include `300x300`, `70x40`, `300x170`, and `600x340`.

**Comment by Bo887** [comment]
@phil-lopreiato Hi, I'm interested in working on this (if it hasn't been started/completed already). Could you give me a few starting pointers?

**Comment by phil-lopreiato** [comment]
@Bo887 sorry about the delay here; I'd be happy to give some pointers. This should go something like this:

 - add onshape as a new media type and allow it to be linked to the robot model in `consts/media_type.py`
 - extend the [`MediaParser`](https://github.com/the-blue-alliance/the-blue-alliance/blob/84439f78aebf08e6acb6c55ada8a26115d35aae3/helpers/media_helper.py#L47) class with new url patterns to recognize/categorize onshape urls
 - extend the [`partial_media_dict_from_url`](https://github.com/the-blue-alliance/the-blue-alliance/blob/84439f78aebf08e6acb6c55ada8a26115d35aae3/helpers/media_helper.py#L95) to be able to build a dict representing an onshape media (see the others for an example)
 - teach the [`Media`](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/models/media.py) class how to render grabcad urls for display and make sure the [main template](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/templates_jinja2/media_partials/media_display_partial.html) can handle onshape medias

You can test this by running TBA locally and running through the full flow of submitting a url, moderating in the queue, and looking at it on the team's profile/admin page

**Comment by jaredhasenklein** [comment]
Can we close this @phil-lopreiato or any mod? Support was added in #2547 for OnShape as a media type.
