### ISSUE TITLE
Annoying colon on homepage

### ISSUE THREAD

**Issue by jaredhasenklein** [the-blue-alliance/the-blue-alliance#2470]
Preemptive _sorry for wasting your time_. 

There's a colon which is bothering me on the home page during the season. For example, right now the top of the page says **"Week 4:"**. No other headers of the same style on the site have a similar colon. I can fix this real quick but want to know if anyone has an opinion on this trivial nonsense like I do (for some reason).
## Expected Behavior
Other headers don't have a colon

## Current Behavior
This header does have a colon

## Possible Solution
Remove the colon (if you want)

## Context
The colon is bothersome

## Screenshots
![image](https://user-images.githubusercontent.com/22439365/54649287-cf817c00-4a66-11e9-8c69-b1d35c08f5ae.png)
![image](https://user-images.githubusercontent.com/22439365/54649303-dc05d480-4a66-11e9-974b-173c67bb2e5e.png)
![image](https://user-images.githubusercontent.com/22439365/54649314-eb851d80-4a66-11e9-9970-b5fc30b97e94.png)
![image](https://user-images.githubusercontent.com/22439365/54649339-0788bf00-4a67-11e9-8a2e-76ff82ebcb7a.png)

**Comment by gregmarra** [comment]
I've felt we should remove it as well. Less is more.
