### ISSUE TITLE
Israeli Teams Detroit 2019

### ISSUE THREAD

**Issue by arimb** [the-blue-alliance/the-blue-alliance#2478]
In most cases teams' 2019 home championship will be the same as their 2018 home championship. The exception being Israeli teams, who will be going to Detroit instead of Houston.

Not sure if there are plans to add a value for 2019 home championship for all teams, or what the plan is. As it stands though, if people use the 2018 home championship for 2019 they will be getting the wrong location for Israeli teams.

**Comment by ZachOrr** [comment]
We get this information from the FRC API. Once we start getting data for teams CMP location, it should be correct on the website.

**Comment by ofekashery** [comment]
The teams for Houston+Detroit is already on TBA and it still broken.
In addition, FRC Events have the correct data.

https://frc-events.firstinspires.org/2019/team/1937
https://www.thebluealliance.com/team/1937

**Comment by bdaroz** [comment]
The team is shown as registered for Detroit champs, but yes, their "Home Championship" for this year is not correct. We may not be able to fix this before the end of the season.

We are tracking this is #2303 and #1741 (To pull home champs from the API)
