### ISSUE TITLE
Weird bracket formatting on Chrome Windows

### ISSUE THREAD

**Issue by jaredhasenklein** [the-blue-alliance/the-blue-alliance#2481]
Playoff bracket is formatted incorrectly.
## Expected Behavior
Either all cells should have borders or no cells should have borders.

## Current Behavior
In Chrome (73) on Windows 10 (1809), the formatting for the playoff bracket is a little screwed up. Some cells have full border, some have partial borders, and some have no borders. Not sure if this is happening elsewhere. Only other browsers I have installed are IE and Edge and they both show no borders.
![image](https://user-images.githubusercontent.com/22439365/55100188-7fb23e80-507e-11e9-908f-f331fabb4148.png)

## Possible Solution
I imagine [this is the file](https://github.com/the-blue-alliance/the-blue-alliance/blob/1324e9e5b7c4ab21315bd00a768112991bada108/static/css/less_css/less/tba/tba_bracket_table.less) that needs to be modified. Can't see why the issue is happening but if we want no border, should be able to fix by setting `border` of `brackettable` and `brackettable tr td` to `0px`.

## Steps to Reproduce (for bugs)
Visit any event page (tested with a random sample of regionals from the past few years) and scroll to the playoff bracket.

## Context
Users frequently look at brackets for playoffs at events

## Your Environment
* Chrome Version 73.0.3683.86
* Windows 10 Build 1809

**Comment by andrewda** [comment]
Something similar seems to be happening on the [advanced insights/predictions page](https://www.thebluealliance.com/event/2019orore/insights).

![image](https://user-images.githubusercontent.com/10191084/55101887-657a5f80-5082-11e9-836f-7348171bc218.png)

**Comment by michaelhill** [comment]
I have submitted a PR that fixes the original issue. I suspect the insights page is a result of the similar problem of using position: relative on table cells. Relative positioning of table cells is undefined in the CSS spec, so different browsers may handle things strangely.

**Comment by jaredhasenklein** [comment]
Fixed in #2484.
