### ISSUE TITLE
District Points Rankings not counting awards for some events

### ISSUE THREAD

**Issue by Thing342** [the-blue-alliance/the-blue-alliance#2485]
It looks like awards are not being counted properly for certain events. For example, none of the awards points appear to have been given out at the CHS Portsmouth event: https://www.thebluealliance.com/event/2019vapor#district-points.

It is worth noting that the official FRC rankings show the correct point totals (https://frc-events.firstinspires.org/2019/VAPOR/rankings#district), so it doesn't appear to be an issue with the FRC API.

## Expected Behavior
https://www.thebluealliance.com/event/2019vapor#district-points should show awards points and match this page: https://frc-events.firstinspires.org/2019/VAPOR/rankings#district

## Current Behavior
It currently does not show any awards points.

## Possible Solution
Not sure.

## Steps to Reproduce (for bugs)
TBA rankings: https://www.thebluealliance.com/event/2019vapor#district-points
FRC rankings: https://frc-events.firstinspires.org/2019/VAPOR/rankings#district
These two should match.

## Context
This counting error is also reflected in the overall district rankings, which means some teams' district point totals are shown as less than the official count.

## Your Environment
* Version used: Web
* Environment name and version: Firefox 67.0b6
* Operating System and version: OSX Mojave

**Comment by JamieSinn** [comment]
FRC Events (official) does not show points for awards until the midnight rollover. I saw this happen with ONT North Bay where the teams who won awards did not have their district points updated yet.

**Comment by Thing342** [comment]
This event happened in week 3. Events from subsequent weeks in CHS have had their awards points counted: https://www.thebluealliance.com/event/2019vabla#district-points

**Comment by gregmarra** [comment]
@ZachOrr  wants to look into this.

**Comment by ZachOrr** [comment]
fwiw - I re-scraped 2019vapor for now to get this fixed, but my guess is we have other broken events hanging out

**Comment by ZachOrr** [comment]
It looks like `2019mitry` ran in to this issue, so I'm trying to figure out the timeline there.

`/tasks/get/fmsapi_awards/2019mitry` got called lots of times, the last timestamp being `2019-03-30 22:00:15.676`. That endpoint calls out to a method that calls `AwardManipulator.createOrUpdate`, which has a `postUpdateHook` that calls `/tasks/math/do/district_points_calc/{event_code}`. `AwardManipulator.postUpdateHook` looks for awards that got updated (some values got changed) and uniques event keys. That seems fine. The most recent call for the calculation hook is from `2019-03-30 19:00:28.136`.

All this is to say - I believe events are getting piped properly throughout our system and I don't think anything has changed there.

The suspect bit in `DistrictPointsCalcDo` is the call to `DistrictHelper.calculate_event_points` where we call `event.get_awards_async`. My leading thought is this could be a bug with the database caching where we're never returning the awards, but we're returning the other points (match points) properly. cc @fangeugene

**Comment by ZachOrr** [comment]
The awards themselves look like they got inserted at `2019-03-30-19:00:25.886` - which also seems right.

**Comment by ZachOrr** [comment]
Going to remove myself from this - we saw a lot of weirdness around this time with DB caching, which could've been the problem. I was unable to find the issue tracking through code/logs.

**Comment by ZachOrr** [comment]
Going to close this with the PR above. If this doesn't fix the issue, we can re-open this issue and we can take another look at it. My best guess is this is an issue where our database query caches aren't cleared between fetching the awards and recalculating the district points, so the district points job ends up fetching an empty list of events. Waiting a few minutes after fetching awards/before running the district points job to allow the cache clear job to run should fix this issue.
