### ISSUE TITLE
Return all teams DQ'd during for elim DQs

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance#2507]
## Expected Behavior

We should return that all teams were DQ'd if a team receives a DQ during an elimination/playoff match.

## Current Behavior

Only the alliance captain is DQ'd. Keep in mind - this behavior is true for 2019 but I'm not entirely sure how we should treat other years.

See https://www.thebluealliance.com/match/2019cur_qf4m1

**Comment by phil-lopreiato** [comment]
This behavior is the same as far back in the past as I can remember, although we should verify with past manuals

**Comment by brennonbrimhall** [comment]
> Only the alliance captain is DQ'd. Keep in mind - this behavior is true for 2019 but I'm not entirely sure how we should treat other years.

Actually, it ends up being the middle alliance station, which is not necessarily the alliance captain.  See https://www.thebluealliance.com/match/2019cur_qf4m1, where 20 is the alliance captain, 1684 as first pick, and 1501 as second.
