### ISSUE TITLE
Users report problems accessing BigQuery data

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#2523]
![image (1)](https://user-images.githubusercontent.com/57101/57974974-01dc2680-798f-11e9-9be9-7e27a4a6b44b.png)

**Comment by ZachOrr** [comment]
Leaving some breadcrumbs here to help figure out how to fix this (it's for sure just a public permissions issue)

I get the same error when viewing our BQ from the link on the website (https://bigquery.cloud.google.com/dataset/tbatv-prod-hrd:the_blue_alliance). Using a link to the new BQ UI (https://console.cloud.google.com/bigquery?project=tbatv-prod-hrd&p=tbatv-prod-hrd&d=the_blue_alliance&page=dataset) will bring up the dataset. These are the same sort of links BQ uses in their public dataset section, so updating this link seems fine.

I'm not able to query the dataset however. I get the error `Access Denied: Project tbatv-prod-hrd: The user [email] does not have bigquery.jobs.create permission in project tbatv-prod-hrd.` It looks like auth'd users only have access to view data, not necessarily create queries. If we can give auth'd users `jobUser` role, that seems like it would work? https://cloud.google.com/bigquery/docs/access-control Right now it seems like they have the `dataViewer` role.

**Comment by gregmarra** [comment]
Is the service we are using intended for public data sets the way we are
using it, or more intended to explore your own private datasets?

**Comment by ZachOrr** [comment]
The wording on the website makes it seems like the dataset should be public, yeah?

`If you're looking to run SQL queries over the TBA database, you can use this BigQuery dataset. This contains a full replica of the TBA database, so the possibilities are endless!`

**Comment by ZachOrr** [comment]
Wait - I misunderstood the question. Is BQ designed to expose public datasets? It seems like that's a valid use of BigQuery, yes. BigQuery exposes lots of big public datasets for people already https://console.cloud.google.com/marketplace/browse?filter=solution-type:dataset&_ga=2.157851832.-30864638.1551112592&pli=1

BigQuery is also good for exploring our own private datasets if we'd like, but I don't think we export any data to private tables.
