### ISSUE TITLE
Facebook Comments Don't Work and are Probably Severely Underused Too

### ISSUE THREAD

**Issue by iCodeCoolStuff** [the-blue-alliance/the-blue-alliance#2550]
I'm willing to bet money that 90% of the traffic on the blue alliance is from frc kids. Most people I know, who aren't old, don't use facebook, so I don't think there's much of a demand for using facebook comments on this platform. 

Oh and they also don't work. Just created a fake facebook account to try and post on [finals match 3 in houston](https://www.thebluealliance.com/match/2019cmptx_f1m3) and it didn't show up at all.

## Possible Solution

Either delete them or make our own comment system and authorize people to create comments with their google account.

We could probably also add profile pictures and use something like [gravatar](https://en.gravatar.com/) to manage them for us if we can't host profile pictures ourselves.

**Comment by ZachOrr** [comment]
This feels both unhelpful and inflammatory - going to close.
