### ISSUE TITLE
[FEATURE REQUEST] Event Team List - Downloadable File

### ISSUE THREAD

**Issue by WillPlaceLast** [the-blue-alliance/the-blue-alliance#2614]
Would it be possible to add and program a button that will save a file (.csv, .txt, .xls, etc) that lists team names and numbers? This would make it al lot easier for some of us so we don't have to type them out individually.
(Unless I'm blind and am just not seeing that.)

**Comment by BrennanB** [comment]
This would probably be best to be done via the API

https://www.thebluealliance.com/apidocs/v3

See the output for /teams/{page_num}

**Comment by ZachOrr** [comment]
For fetching teams at an event you'll to use the `/event/{event_key}/teams` endpoint - the API docs should be able to help with how to get started
