### ISSUE TITLE
Add OnShape Support to CAD listing

### ISSUE THREAD

**Issue by mdurrani808** [the-blue-alliance/the-blue-alliance#2623]
At the moment, TBA only accepts GrabCad links. Make it so it allows OnShape Links
## Context

 Hasn't affected me but would be cool to have this support. A lot of people use OnShape and it would be easier for them to just link the CAD.

**Comment by ZachOrr** [comment]
It looks like TBA supports OnShape https://github.com/the-blue-alliance/the-blue-alliance/pull/2547
