### ISSUE TITLE
[master task] Migrate to GAE Python 3 Standard Environment

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#2663]
Python 2 is deprecated. We should stop using it. I think this is a good focus for the next upcoming offseason.

Docs page: https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/

In short, the recommend approach is:

## Overview of the migration process

We recommend the following incremental approach to the migration, in which you maintain a functioning and testable application throughout the process:

 1.  Migrate the App Engine bundled services in your Python 2 app to Google Cloud services, third-party services, or other recommended replacements. Test your app after migrating each service. When you finish this step, your Python 2 app should no longer use any google.appengine APIs.

 2. Upgrade your app to be compatible with both Python 2 and Python 3. Several solutions are available to help with this upgrade. For example, use Python-Future or Python-Modernize. For more information about this step of the migration process, see Porting Python 2 Code to Python 3 on the Python Software Foundation documentation site.

 3. Prepare App Engine configuration files for the Python 3 runtime.

4. Test and deploy your upgraded app in a Python 3 environment. You may need to spend significant time fixing compatibility issues that aren't visible until you run your upgraded app in a Python 3 environment. After all of your tests pass, use traffic splitting to slowly migrate traffic from your app in the Python 2 runtime to the app in the Python 3 runtime.

## Migrating Bundled Services

For us, the first step will be the hardest, as we are big users of bundled GAE services. [This page](https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/migrating-services) has specific suggestions for each service

In short, we'll need to vendor in a separate google-cloud library to the py2 app, migrate/verify that it works properly, and repeat for all bundled services.

I'll go through each bundled service we use with some links, and we can eventually split them out to sub-tasks when we get to working on them.

### memcache

GAEpy3 has no free memcache. We'll need to change and use [Cloud Memorystore](https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/memcache-to-memorystore) instead. We use memcache mainly for:
 - speeding up ndb queries (see section below)
 - [`CacheableHandler`](]https://github.com/the-blue-alliance/the-blue-alliance/blob/master/controllers/base_controller.py#L23) stores rendered pages in memcache and tries to read them
 - a whole bunch of other random stuff

We'll probably want to make a wrapper class that mirrors the old GAE memcache API, but implements them in terms of a redis client pointing at a memorystore instance. This way, we can (in theory) do the migration with a find-replace on imports

### NDB

We can migrate to use the [cloud NDB](https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/migrate-to-cloud-ndb) library. Key bits include:
 - **Cloud NDB doesn't use the App Engine Memcache service to cache data.** Instead, Google recommends to use [Cloud Memorystore for Redis](https://cloud.google.com/memorystore/docs/redis/redis-overview), which [**has no free tier**](https://cloud.google.com/memorystore/pricing)
 - [Full list of differences](https://github.com/googleapis/python-ndb/blob/master/MIGRATION_NOTES.md)
 - We should be able to configure a request middleware that take the runtime context, creates a ndb context, and initializes the redis caching and have things mostly just work after doing `s/from google.appengine.ext import ndb/from google.cloud import ndb`
 - We'll need to be careful about features/properties that are no longer supported, but skimming [though the list](https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/migrate-to-cloud-ndb#updating_code_for_removed_or_changed_ndb_apis) it doesn't look like there's anything major (save for maybe some `tasklet` syntax changes)

Details tracked in https://github.com/the-blue-alliance/the-blue-alliance/issues/2791

### Task Queue

The `taskqueue` module isn't a thing anymore either. We only use push queues, and there's a [guide to migrate these to Cloud Tasks](https://cloud.google.com/appengine/docs/standard/python/taskqueue/push/migrating-push-queues). The free tier for cloud tasks is free for the first 1 million (and then $0.40/million afterwards).

Cloud tasks does not support:
 - Enqueueing tasks in Datastore transactions
 - Using the deferred tasks library instead of a worker service
 - Working with tasks in multi-tenant applications
 - Simulating with the local development server
 - Adding tasks asynchronously

I'm pretty sure we currently rely on most of these things, so this'll be another case where we'll probably need to write our own bit of glue code to deal with GAE routing and local emulator support.

### Auth

The old users API isn't supported anymore. [Migration docs](https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/migrating-services#user_authentication) say:

> For an alternative to the Users API, use any HTTP-based authentication mechanism

We probably want to migrate everything to use Firebase auth, as this is the direction we're taking with the mobile apps.

### Mail

This is totally gone in GAEpy3, they [suggest using a third party provider](https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/migrating-services#mail). Since we really only use emails for some types of suggestions and admin things, we probably fit in the free tier for most of these.

**Comment by brennonbrimhall** [comment]
Thanks for the research and taking the time to document everything together.

**Comment by phil-lopreiato** [comment]
Further discussion in https://github.com/the-blue-alliance/the-blue-alliance/issues/3995 about which builtins we want to continue using in py3
