### ISSUE TITLE
Remove `/record` endpoint

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance#2727]
Right now the [`/record`](https://github.com/the-blue-alliance/the-blue-alliance/blob/a51adb8a1a9f4dd06397547aa02537f873a147b6/main.py#L134) endpoint is looking for [`record.html` in `jinja2_templates`](https://github.com/the-blue-alliance/the-blue-alliance/blob/a51adb8a1a9f4dd06397547aa02537f873a147b6/controllers/main_controller.py#L494), but that file hasn't been migrated yet.

**Comment by fangeugene** [comment]
That page is so out of date we should just kill it.
