### ISSUE TITLE
Hovering Over Red Endgame Results in Detailed Results Causes Description Text to Shift

### ISSUE THREAD

**Issue by inkling16** [the-blue-alliance/the-blue-alliance#2732]
In the match results page for finals 1 of the week 0 event, hovering over a red robot's endgame results causes the second column description text to shift into the third column, replacing the blue endgame results in that row. Screenshot attached. 

## Expected Behavior

The description text should remain in the second column

## Possible Solution

Possible that indices are not shifting correctly when the team number text is displayed. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
Windows 10 OS
Chrome browser version 79.0.3945.130 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/5760180/75099224-2653d780-558d-11ea-84d7-f5a76d573386.png)

**Comment by jaredhasenklein** [comment]
Yeah that's my bad. It's the tooltips. I know a fix and can do it tomorrow most likely
