### ISSUE TITLE
Bug in mobile view 

### ISSUE THREAD

**Issue by katzuv** [the-blue-alliance/the-blue-alliance#2734]
There is no number on the counter until week 1 events start.
Version: Android 10, Google Chrome 80.
![Screenshot_20200224-161158](https://user-images.githubusercontent.com/31829093/75159334-9cd50e80-5720-11ea-948f-6d4418957bae.png)

**Comment by ZachOrr** [comment]
This is just the homepage needing to be changed. Closing.
