### ISSUE TITLE
Zebra Motionworks endpoint doesn't implement Last-Modified header

### ISSUE THREAD

**Issue by PenguinSnail** [the-blue-alliance/the-blue-alliance#2749]
Exactly what the title says: the Zebra Motionworks data endpoint doesn't set the Last-Modified header or react to a If-Modified-Since header in the request.

## Expected Behavior
The Zebra Motionworks endpoint should be consistent with all other endpoints in that a response from it will include the Last-Modified header providing the date that the document was last updated. It should also use the If-Modified-Since header if included in the request.

## Current Behavior
Currently no Last-Modified header is set, and if the If-Modified-Since header is set in the request, it's ignored by the API.

## Steps to Reproduce
1. Make a GET request to a Zebra Motionworks endpoint

## Context
Zebra Motionworks data is quite heavy compared to other endpoints, at around 500KB per match. Implementing the Last-Modified/If-Modified-Since headers would prevent browsers and other programs from needlessly sending such large quantities of data repeatedly. It's also misleading because every API endpoint is advertised as utilizing the Last-Modified/If-Modified-Since headers.

This also directly affects my work because I am developing a scouting app that takes advantage of Motionworks data, and would like to prevent excessive data transfer.

## Your Environment
- NodeJS 13
- cURL
- Firefox 73

**Comment by fangeugene** [comment]
Oops this was an oversight on implementation. Thanks for pointing it out!

**Comment by fangeugene** [comment]
Fixed in 3b052971f69c83ed56ee4b8f509e7abc69ec525e

**Comment by fangeugene** [comment]
@PenguinSnail a reminder, you can also use etags.
