### ISSUE TITLE
"Highest Scoring Match Overalles" on 2020 insights page

### ISSUE THREAD

**Issue by Chris857** [the-blue-alliance/the-blue-alliance#2769]
On https://www.thebluealliance.com/insights/2020, one section is titled "Highest Scoring Match Overalles". On https://www.thebluealliance.com/insights/2019, the same section is titled "Highest Scoring Match Overall".

What is with this weird spelling?

**Comment by lethosor** [comment]
It's just pluralized in the wrong place - it should be "matches overall", since there are two matches tied for the record this year: https://github.com/the-blue-alliance/the-blue-alliance/blob/1324e9e5b7c4ab21315bd00a768112991bada108/templates_jinja2/insights_details.html#L62

**Comment by dracco1993** [comment]
@Chris857 Thanks for reporting this!  I got a fix in, and it will be deploying here shortly!  👍
