### ISSUE TITLE
Incorrect team name

### ISSUE THREAD

**Issue by Chris857** [the-blue-alliance/the-blue-alliance#2923]
https://www.thebluealliance.com/team/47
47 is obviously "Chief Delphi". When you search for "47", the suggestion list shows "47 | Chief Delphi". However, the team page shows the team name as "Bananas Are Outrageous!" for some reason.

**Comment by phil-lopreiato** [comment]
Fixed this in https://github.com/the-blue-alliance/the-blue-alliance/pull/2924
