### ISSUE TITLE
Consider AdSense ads

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#324]
Given TBA is costing $6/wk to host right now, and traffic ought to go up during build, consider adding AdSense blocks to offset hosting cost.

Is there a way to estimate revenue?

2011 -> 2012 growth has been about +25%. Assuming the same rate of growth continues, 2013 would be around:
- 1.25m pageview
- 213k visits
- 96k unique visitors

At a $0.50 CPM, that's around $600 for the year. That would pay for hosting, and maybe some stickers.

Is there a way to get affiliate revenue for our YouTube embeds?

**Comment by gregmarra** [comment]
We've managed to reduce hosting costs, so this is not a problem as it was projected. We may re-evaluate in a few years.

**Comment by synth3tk** [comment]
If this ever becomes a problem again, let me know and I can send a few bucks your way each month to help. I'm sure we could also find members of the community willing to donate.
