### ISSUE TITLE
Team History pages not showing awards after 2016

### ISSUE THREAD

**Issue by dracco1993** [the-blue-alliance/the-blue-alliance#3276]
## Expected Behavior
Team history pages should be showing award information.

## Current Behavior
They aren't.  👀 

## Possible Solution
🤷‍♂️

## Steps to Reproduce (for bugs)
Visit a team history page: https://www.thebluealliance.com/team/118/history

## Context:
This was reported through FB here:
https://www.facebook.com/groups/moardata/permalink/3794899313863669

**Comment by ZachOrr** [comment]
There’s a 500 being thrown related to round robin stuff - might be the cause?

**Comment by phil-lopreiato** [comment]
I fixed that fatal this morning; let me finish one thing and then I'll take a look.

Thanks for forwarding the report!

**Comment by phil-lopreiato** [comment]
Figured it out - I did a dumb thing and we we reading from old stale data we'd last touched in 2016.
