### ISSUE TITLE
2019 FIN event list 404s

### ISSUE THREAD

**Issue by dracco1993** [the-blue-alliance/the-blue-alliance#3316]
## Expected Behavior
It doesn't 404.  👀 

## Current Behavior
It 404s.  👀 

## Possible Solution
From @phil-lopreiato:
> wait, I think those pages are still being served by p2, the dispatch rule for py3 doesn't cover it
it only has www.thebluealliance.com/events
so we should fix that, then fix it on py3

## Steps to Reproduce (for bugs)
https://www.thebluealliance.com/events/fin/2019

**Comment by ZachOrr** [comment]
Should be able to use https://github.com/the-blue-alliance/the-blue-alliance/blob/py3/src/backend/common/consts/renamed_districts.py for this

**Comment by phil-lopreiato** [comment]
Figured this out; we should have bumped the db query cache versions in https://github.com/the-blue-alliance/the-blue-alliance/commit/5a73e405efd2159773b5ff50e2f5c31a00a79a79

```
from database.district_query import DistrictQuery

q = DistrictQuery("2019fin").fetch()
print q  # Returns None

q2 = DistrictQuery("2019in").fetch()
print q2  # Returns 2019in
```
