### ISSUE TITLE
py2 CSS not computing values in stylesheets

### ISSUE THREAD

**Issue by nitays** [the-blue-alliance/the-blue-alliance#3474]
Blue banners as they appear in team season and history pages are cut in the bottom - don't have the "ribbon" ending

current state:
![image](https://user-images.githubusercontent.com/14238902/114526303-87d27c00-9c4f-11eb-85e9-c2f7874315d4.png)

expected:
![image](https://user-images.githubusercontent.com/14238902/114526734-ec8dd680-9c4f-11eb-9d28-4d40dd9554b0.png)

**Comment by ZachOrr** [comment]
This looks like a larger CSS issue with the py2 branch where the stylesheet isn't getting properly compiled. You can see for things like the social icons and the blue banners, there are incorrect values for these margins where math is attempting to be done, but it's not getting computed, so we have invalid CSS elements.

![Screen Shot 2021-04-13 at 11 25 43 AM](https://user-images.githubusercontent.com/516458/114579563-f9103000-9c4b-11eb-97e0-3e829f80b8e7.png)
![Screen Shot 2021-04-13 at 11 27 02 AM](https://user-images.githubusercontent.com/516458/114579571-fb728a00-9c4b-11eb-9e26-0bbc85bff2e9.png)

**Comment by fangeugene** [comment]
Fixed in https://github.com/the-blue-alliance/the-blue-alliance/commit/0b989fc281a45fde52eacf4f8edfd18d83b2a49d
