### ISSUE TITLE
/suggest/review tabs do not link to pages

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance#3487]
When clicking one of the tabs on the `/suggest/review` page, the tab will not link the user to the linked page. This bug was introduced in https://github.com/the-blue-alliance/the-blue-alliance/commit/15f3d26a7d52b6be315727f4ff603a9f3733a18e

**Comment by TechplexEngineer** [comment]
@ZachOrr I believe #5079 fixes this.
