### ISSUE TITLE
"Watch all matches" feature for events, not just teams

### ISSUE THREAD

**Issue by jblay** [the-blue-alliance/the-blue-alliance#3619]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by ZachOrr** [comment]
I believe this got done in https://github.com/the-blue-alliance/the-blue-alliance/pull/3406 - feel free to re-open if this isn't what this issue is talking about
