### ISSUE TITLE
url-based taskqueue enqueue API

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#3685]
We don't have a direct replacement for [`taskqueue.add`](https://cloud.google.com/appengine/docs/standard/python/refdocs/google.appengine.api.taskqueue.taskqueue#google.appengine.api.taskqueue.taskqueue.add)

We should generally prefer people use the callable based `defer` API, I think, because it's simpler, but for cases when we need to do x-module calls, we want to have a totally url based way to do it.

The current `defer` interface requires a callable, but we may just need to expose some of the lower level primitives (url, method, body) and make the request to the other service. This could also be an opportunity to require using flask's `url_for` methods for some better safety and such

This might also be an interesting opportunity to make some good scaffolding for the old app's enqueue/do pattern

**Comment by ZachOrr** [comment]
Notes for later - this is going to be an issue when working with cross-service calls. `defer` allows you to run a Callable on another service, but that's a pretty risky situation, and probably shouldn't be supported. The Callable code isn't guaranteed to work across all services if it uses service-specific code.

We should probably look to re-tool `defer` to support a Callable, a GET, and a POST. I believe that would support all of our use cases.

More investigation is required to figure out if Pub/Sub is too heavy for this sort of thing.

**Comment by ZachOrr** [comment]
Adding notes for myself on this -

This is an issue in the [backup PR](https://github.com/the-blue-alliance/the-blue-alliance/pull/3690). The `tasks-io` tasks need to have checks that they're kicked off by tasks, but we want to have URLs that can kick these tasks off manually (if they're not kicked off by a cron job). Adding a `/backup/enqueue` endpoint to web to kickoff a backup task in tasks-io is a cross-service call that we don't support yet.

**Comment by ZachOrr** [comment]
Closing this - we've moved back to using the bundled App Engine `deferred` and `taskqueue` 🙌
