### ISSUE TITLE
2021 Chezy Champs Doesn't Appear in Search

### ISSUE THREAD

**Issue by neyre** [the-blue-alliance/the-blue-alliance#3797]
In the search dialog after typing "Chezy", the 2021 event doesn't appear. With this behavior along with the autocomplete to the first item in the list, it is very challenging to find the event from search (I can't figure out how to get to a general search page instead of just going to the first autocomplete result)

![image](https://user-images.githubusercontent.com/1348810/131068201-edb08bd3-ec00-4620-bb10-17733d6fa456.png)

**Comment by fangeugene** [comment]
@neyre should be good now

**Comment by neyre** [comment]
Thank you thank you thank you thank you!

----- Original message -----
