### ISSUE TITLE
Webcast status appears as Unknown

### ISSUE THREAD

**Issue by timtim17** [the-blue-alliance/the-blue-alliance#3916]
## Expected Behavior

When an event with a Twitch webcast set is shown on the homepage, the webcast button should show the Online/Offline status of the stream.

## Current Behavior

Streams show with Unknown status

## Possible Solution

Not too familiar with the codebase, but it seems like in a recent commit the `webcast_status` property was commented out?
https://github.com/the-blue-alliance/the-blue-alliance/blob/py3/src/backend/common/models/event.py#L562-L577

## Steps to Reproduce (for bugs)

1. Have an active event with a Twitch stream
2. Open Homepage
3. Observe Blue Webcast button with ❔ Unknown status

## Context

This affects the event browsing experience and being able to find streams that are live.

## Your Environment

* Version used: Live site as of 10/16
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox 93.0
* Operating System and version (desktop or mobile): Desktop

![screenshot](https://i.imgur.com/UVxlYyS.png)

**Comment by fangeugene** [comment]
@timtim17 thanks for closing out this ticket! I forgot to link it.
