### ISSUE TITLE
Twitch “purple screen of death” on Gameday

### ISSUE THREAD

**Issue by ajs256** [the-blue-alliance/the-blue-alliance#3931]
Occasionally when viewing a Twitch stream, I see a screen like this:
![image](https://user-images.githubusercontent.com/67526318/139561692-36a9e284-ddd3-4e6b-94b3-e2f4ce1ec8b9.png)
Is there a workaround?

**Comment by bdaroz** [comment]
Unfortunately this is something that Twitch.tv is popping up on embedded streams. [Some](https://kotaku.com/twitch-embeds-keep-getting-worse-1846173187) [reports](https://www.dexerto.com/entertainment/twitch-accused-of-being-greedy-by-adding-purple-screen-of-death-to-embeds-1504955/) lay this squarely at Twitch's feet, while the message seems to want to blame ad-blockers.

If you're seeing the popup and are not running an ad blocker, the only suggestion I can give is to complain to twitch.
