### ISSUE TITLE
2022 team pages don't load

### ISSUE THREAD

**Issue by jaredhasenklein** [the-blue-alliance/the-blue-alliance#4016]
Team-year pages for 2022 show as a menu option, but don't load.

## Expected Behavior
A page with a team's events for the current year will load (tba/team/<<team>>/<<year>>). 
Working example (for any year <2022): https://www.thebluealliance.com/team/1836/2015

## Current Behavior
404 error (example: https://www.thebluealliance.com/team/1836/2022)
![image](https://user-images.githubusercontent.com/22439365/143501311-00c5f8d5-a877-454f-bf6f-ac7d5e014427.png)

## Steps to Reproduce (for bugs)

1. Navigate to an active team page
2. Click the year dropdown
3. Select 2022
![image](https://user-images.githubusercontent.com/22439365/143501258-b0769fa2-fd21-4617-8c4b-93ed66993db4.png)

## Your Environment
Web.

**Comment by jaredhasenklein** [comment]
It's also worth noting that 2022 events load (e.g. https://www.thebluealliance.com/event/2022caph) while the "2022 Events" page (https://www.thebluealliance.com/events/2022) is still a 404. 

I would assume these issues are related to the same job/switch.

**Comment by ZachOrr** [comment]
I *think* this is related to the API status sitevar being cached and giving us issues. We need to clear the cache and try again. My key isn't working for hitting the upstream Redis box though, and we're working on moving the ndb cache off the of the Redis box.

A lot is in flux here - but I'll keep an eye on it

**Comment by phil-lopreiato** [comment]
Yeah, https://github.com/the-blue-alliance/the-blue-alliance/pull/4018 fixed this because it made the the py3 version of the site read the same memcache data as py2, removing the split brain
