### ISSUE TITLE
API event key validator does not support events ending in three numbers (e.g. 2022dc305)

### ISSUE THREAD

**Issue by eforbes** [the-blue-alliance/the-blue-alliance#4080]
## Expected Behavior
`https://www.thebluealliance.com/api/v3/event/2022dc305/teams` should return the list of teams for [2022dc305](https://www.thebluealliance.com/event/2022dc305)

## Current Behavior
API returns a 404 error:
```
{
  "Errors": [
    {
      "event_id": "2022dc305 is not a valid event id"
    }
  ]
}
```

## Possible Solution
Fix the regex: https://github.com/the-blue-alliance/the-blue-alliance/blob/dab38a2d888c8e50b0b500573e802e2880db04c2/src/backend/common/models/event.py#L644

## Steps to Reproduce (for bugs)
1. Make API request for https://www.thebluealliance.com/api/v3/event/2022dc305/teams

## Context
I can't list teams for any 1-day events via the TBA API :(

## Your Environment
* Version used: v3

**Comment by gregmarra** [comment]
Looks like the regex assumes events end in 2 or fewer numbers, and now some events end in 3 numbers.
