### ISSUE TITLE
short_name API field for single day events omits day number

### ISSUE THREAD

**Issue by eforbes** [the-blue-alliance/the-blue-alliance#4081]
## Expected Behavior
`short_name` for the event [Festival de Robotique Regional Day 1 2022](https://www.thebluealliance.com/event/2022qcmo1) should be something like `Festival de Robotique Day 1`

## Current Behavior
`short_name` is `Festival de Robotique` for all 3 days of this event making each event indistinguishable by `short_name`

## Possible Solution
Update the logic for generating short names:
https://github.com/the-blue-alliance/the-blue-alliance/blob/dab38a2d888c8e50b0b500573e802e2880db04c2/old_py2/helpers/event_helper.py#L109

## Steps to Reproduce (for bugs)
1. Call the API: `https://www.thebluealliance.com/api/v3/events/2022`
2. Observe the short_name values for `qcmo1`,`qcmo2`, & `qcmo3`

## Context
Displaying a list of events using "short name" is not useful if there are different events with identical short names

![festival](https://user-images.githubusercontent.com/2548822/147396899-71fd14a5-3296-40fc-919b-2ddf4ffc3321.PNG)

## Your Environment
* Version used: v3

**Comment by gregmarra** [comment]
I have edited each short name to include "Day N". Thanks for the report!

**Comment by eforbes** [comment]
"Day N" seems to be missing again from these events as of a few days ago

Thanks!

**Comment by gregmarra** [comment]
I edited them all again, I'm not sure what changed them back. 

@fangeugene is it possible the datafeeds are setting Short Names? These used to have to be set by hand, it wasn't a FIRST provided field.

**Comment by fangeugene** [comment]
Short names are generated programmatically. I'll investigate a fix.

**Comment by fangeugene** [comment]
@gregmarra fixed
