### ISSUE TITLE
Give match models a sense of time

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#415]
Will be useful for "live" stuff like GameDay. Also, got an API request to get an event's full schedule including time of each match.

Important note: Match times on FIRST's website are reported in the regional's local time zone and the dates aren't given (important because competitions span multiple days). Do we just ignore the day? Should we do everything in GMT?

**Comment by gregmarra** [comment]
Matches now have `time = ndb.DateTimeProperty()`
