### ISSUE TITLE
Regression of #2150 -- If-Modified-Since header giving Access-Control-Allow-Headers preflight error.

### ISSUE THREAD

**Issue by TechplexEngineer** [the-blue-alliance/the-blue-alliance#4178]
HTTP Requests from browser context which include the "If-Modified-Since" header are rejected as the server is not including the string "If-Modified-Since" in the response header "access-control-allow-headers"

## Expected Behavior
The response header access-control-allow-headers should include "If-Modified-Since" and "x-tba-auth-key"

## Current Behavior
Example Request
<img width="531" alt="Screen Shot 2022-01-16 at 8 36 40 PM" src="https://user-images.githubusercontent.com/175873/149687737-e0d455f0-bc10-454d-8abf-2fb9075402d6.png">

```
fetch("https://www.thebluealliance.com/api/v3/events/2020/simple", {
  "headers": {
    "accept": "application/json",
    "if-modified-since": "undefined",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"96\", \"Google Chrome\";v=\"96\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "x-tba-auth-key": "<Redacted>"
  },
  "referrer": "http://localhost:3000/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "omit"
});
```

**Comment by fangeugene** [comment]
Thanks, will prioritize a fix.
