### ISSUE TITLE
API reponse not returning a 'Last-Modified' header

### ISSUE THREAD

**Issue by LudiWang85454** [the-blue-alliance/the-blue-alliance#4235]
## Expected Behavior
When reading from the TBA API, the response should include a 'Last-Modified' header to indicate when the data was last changed.

## Current Behavior
The 'Last-Modified' header is not included with the request

## Steps to Reproduce (for bugs)
In a browser, go to https://www.thebluealliance.com/api/v3/event/2021cc/rankings?X-TBA-Auth-Key={auth_key} (or any other API url) and go to the 'Headers' tab. 'Last-Modified' is not listed.

In python:

```
import requests

url = 'https://www.thebluealliance.com/api/v3/event/2021cc/teams'
request_headers = {'X-TBA-Auth-Key': api_key}
request = requests.get(url, headers=request_headers)
print(request.headers['Last-Modified'])
```

Results in `KeyError: 'last-modified'`

## Context
We are using the TBA API in our scouting system. The code we use for pulling from TBA has not changed since November of 2021 when we were able to get the 'Last-Modified' header with the requests.

**Comment by inkling16** [comment]
I'm also not seeing the Last-Modified header

**Comment by ZachOrr** [comment]
APIv3 uses ETag not Last-Modified

**Comment by inkling16** [comment]
Can the documentation here be updated to note this: 
https://www.thebluealliance.com/apidocs

**Comment by Rooster13** [comment]
Can we reopen this issue until the documentation has been updated?

**Comment by ZachOrr** [comment]
Yes! I apologize I didn’t realize the docs were bad.

**Comment by ZachOrr** [comment]
This was fixed with https://github.com/the-blue-alliance/the-blue-alliance/pull/4490

Thanks for the report!
