### ISSUE TITLE
cancelled events to be removed

### ISSUE THREAD

**Issue by tmpoles** [the-blue-alliance/the-blue-alliance#4261]
Not sure where the event list pulls are being done from, but the following events have been cancelled and need to be removed from TBA - they are still listed on the events page <https://www.thebluealliance.com/events/ont>

ONT Georgian College Day 1/2 (week 3)
ONT Vic Park Day 1/2 (week 3)
ONT North Bay Day 1 (week 5)
ONT Windsor Day 1 (week 5)
ONT Durham Day 1/2 (week 5)

**Comment by gregmarra** [comment]
Thanks for letting us know. I've deleted these all.
