### ISSUE TITLE
flwp q3 was replayed but the original match score is showing on TBA

### ISSUE THREAD

**Issue by inkling16** [the-blue-alliance/the-blue-alliance#4301]
South Florida q3 was replayed: https://www.chiefdelphi.com/t/undefeated-teams-2022/404910/9 
According to FRC Events: 
![image](https://user-images.githubusercontent.com/5760180/157446270-184d5d3e-0552-46f8-8f45-f4eef4badabe.png)
The second match is the replay, because 179 won and it occurred at a later time. 
However, on TBA, the original match is still showing: https://www.thebluealliance.com/match/2022flwp_qm3

## Expected Behavior

TBA should show the replayed match results, not the original. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by phil-lopreiato** [comment]
frc-events doesn't currently show that reply on https://frc-events.firstinspires.org/2022/FLWP/qualifications

![image](https://user-images.githubusercontent.com/2754863/159385993-ae613be8-2155-4ae8-bf3e-c9e9b2cf3e6a.png)

This may have been some data oddity or something? If you can find FIRST's official results showing the replay, I'd be glad to make sure TBA reflects it

**Comment by inkling16** [comment]
I don't believe I have permissions to re-open issues. 

You can see the replayed match on 179's team page here: https://frc-events.firstinspires.org/2022/team/179
Also, if you click on score details for that match you see this: https://frc-events.firstinspires.org/2022/FLWP/qualifications/3
which shows the replayed score of 44 to 67. You arrive at this page if you click on either the original match or the replayed match from the first link. You also arrive there even if you click on match 3 from the full qualification results page: https://frc-events.firstinspires.org/2022/FLWP/qualifications
![image](https://user-images.githubusercontent.com/5760180/159498172-007858fc-45c8-4d99-9554-38884e7c83e2.png)

There does seem to be some kind of inconsistency on FIRST's side since that match shows 30-32 on the front page but shows 44-67 when you go into the details.

**Comment by gregmarra** [comment]
Re-fetching matches with https://www.thebluealliance.com/tasks/get/fmsapi_matches/2022flwp returns the 30-32 score:
> Alliances: {"red": {"teams": ["frc179", "frc3164", "frc21"], "surrogates": [], "dqs": [], "score": 30}, "blue": {"teams": ["frc6686", "frc2168", "frc7403"], "surrogates": [], "dqs": [], "score": 32}}

Will poke at this more.

**Comment by phil-lopreiato** [comment]
We've been working with HQ on the details here

The legacy hybrid schedule endpoint has a bug around replays, so our recommendation is to just use the v3 matches endpoint (https://github.com/the-blue-alliance/the-blue-alliance/issues/4345)

I'll reopen this issue and leave it as a reminder to refetch this event once we make those changes

**Comment by ZachOrr** [comment]
I'm also seeing this as well for https://www.thebluealliance.com/match/2022miliv_qm13 - the top-line score is 44-44, but the API returns 62-44 in the breakdowns. There's a bug somewhere in the FRC API around the top-line scores being disconnected from the breakdown scores in the case of replays.
