### ISSUE TITLE
2022on306 missing Awards

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#4310]
## Expected Behavior
Awards from https://frc-events.firstinspires.org/2022/ON306/awards show on https://www.thebluealliance.com/event/2022on306

## Current Behavior
No Awards tab shown at all on https://www.thebluealliance.com/event/2022on306

## Possible Solution
Something with the unusual event key (ending in a 3 digit number)?

**Comment by tmpoles** [comment]
This is also the case for on305, common denominator is the 1-day event with a 3-digit event key

**Comment by phil-lopreiato** [comment]
> Keep in mind that single day events don’t publish their awards the day of the event, it can be days later (not sure why, this is just what I was told, they do some sort of “award show” a few days after the event) so some of it could be that too, the award may not yet be there to give points for.

The input to the awards fetch is `events_within_a_day`, so this is probably why they weren't caught. For now, we may just want to manually refresh awards for impacted events?

**Comment by phil-lopreiato** [comment]
Regardless; I manually updated this one and `2022dc305`
