### ISSUE TITLE
2022okok has extra matches

### ISSUE THREAD

**Issue by inkling16** [the-blue-alliance/the-blue-alliance#4314]
2022 Oklahoma changed their schedule and removed matches past qm 72: https://www.chiefdelphi.com/t/2022-oklahoma-regional/404935/19
Matches past qm 72 are now removed from FRC Events: 
https://frc-events.firstinspires.org/2022/OKOK/qualifications
But they still exist on TBA: 
https://www.thebluealliance.com/event/2022okok

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by gregmarra** [comment]
@phil-lopreiato fixed this.
