### ISSUE TITLE
Incorrect Single Day Event District Point Calculations

### ISSUE THREAD

**Issue by PChild** [the-blue-alliance/the-blue-alliance#4330]
## Expected Behavior
District point calculations for single day events in 2022 should handle four alliance events where alliance selection points decrement by two instead of by one. Teams that play back-to-back events (eg. 2022VA305 and 2022VA306) should be assigned a 2 district point bonus. Elimination series wins over fake alliances (comprised of 'Off-Season Demo Team' numbers) should not be counted for district points. 

## Current Behavior
In week 1 FMS didn't support four alliance events, to get around this scorekeepers created alliances 4-8 using 'Off-Season Demo Team' numbers and advanced the real alliances through to semifinals. This is making TBA award series win district points to all of real alliances at the event.[ 2022ON305 for example](https://www.thebluealliance.com/event/2022on305). 

Alliance selection points in both weeks 1 and 2 are also wrong since the formula for eight alliances is used, [2022DC312 is a good example of this](https://www.thebluealliance.com/event/2022dc312#district-points).

The two point bonus for teams attending back-to-back events as their events that count for district points is not at all represented, [6802](https://www.thebluealliance.com/team/6802/2022) is a team that would earn this bonus.

## Possible Solution
* Elimination series wins that include team numbers in the 'Off-Season Demo Team' range should not be counted for district points.
* Alliance selection point assignment should check event type (if there's a way to check for single day?) or check number of alliances made up of real teams to decide how to decrement district points.
* Teams that play back-to-backs should have two points added. Maybe change the 'Age Bonus' field to just a 'Bonus' field?

## Steps to Reproduce (for bugs)
Visit any CHS or ONT event district points page and compare to 2022 FRC manual section 11.8.1.

## Context
There are a LOT of people in the Chesapeake district who are very, very confused about this right now and think TBA / FRC Events are correctly reporting district points when both sources very much are not.

**Comment by phil-lopreiato** [comment]
Thanks so much for the thorough report!

I think I've implemented support for everything we need on this front in https://github.com/the-blue-alliance/the-blue-alliance/pull/4347

**Comment by PChild** [comment]
Looks good to me, thanks Phil!
