### ISSUE TITLE
Some team nicknames have leading / trailing whitespace

### ISSUE THREAD

**Issue by giladwo** [the-blue-alliance/the-blue-alliance#4331]
## Expected Behavior
I believe team nickname (or probably any other text attribute) should be stripped from wrapping whitespace, which is most probably a typo.

## Current Behavior
Some teams return nicknames with wrapping whitespace, i.e. `frc1580`, `frc1937` (see steps to reproduce).

## Possible Solution
I'm not familiar with TBA internals, but
- fixing stored nicknames in the DB, plus
  + adding a constraint to make sure it doesn't happen again; or
- stripping whitespace in the API
should work well if they're applicable here.

## Steps to Reproduce
```bash
$ curl -sSX GET 'https://www.thebluealliance.com/api/v3/team/frc1580' -H 'accept: application/json' -H "X-TBA-Auth-Key: ${TBA_KEY}" | grep nickname
  "nickname": " The Blue Monkeys",
$ curl -sSX GET 'https://www.thebluealliance.com/api/v3/team/frc1937' -H 'accept: application/json' -H "X-TBA-Auth-Key: ${TBA_KEY}" | grep nickname
  "nickname": "Elysium ",
```

## Context
I've been stripping redundant whitespace for some time now on a few different projects, and considering the fact that it's probably a typo, I think it would be useful to everyone to have them stripped automatically.

**Comment by phil-lopreiato** [comment]
Thanks for letting us know!

I updated this in https://github.com/the-blue-alliance/the-blue-alliance/pull/4346
