### ISSUE TITLE
Only one team can win each award at an event, creating Dean's List award problems

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#4333]
> We recently competed at the Regional Monterrey 2022, of which we won the Judges' Award, Team Spirit Award, and both Dean's List Finalists Awards. The issue is that only one appears (Leonardo Diego), while our other nominee won as well (Imelda Gómez González Pico) but doesn't appear. I am attaching a screenshot of the FRC Event Website just in case. I wanted to see if you could help us out adding this as well to our 2022 information, the regional's data, and our team history site.

![image](https://user-images.githubusercontent.com/57101/159130729-15df6958-0aa2-4036-b261-36a85504c277.png)

https://github.com/the-blue-alliance/the-blue-alliance/blob/31fe8afb09173c69ca1f2afb1693af47423b4236/src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_awards_parser.py#L40-L62

**Comment by ZachOrr** [comment]
Commenting so I can link the two tickets - I suspect the proposed fix for this issue will also have implications for https://github.com/the-blue-alliance/the-blue-alliance/issues/3614

We should be able to use the same fix for both (handle duplicate award recipients) but in the Chairman’s case, we’ll need to have some additional code for the name formatting

**Comment by clarkrowley** [comment]
Two more this year - 
https://www.thebluealliance.com/event/2022flwp#awards
https://www.thebluealliance.com/event/2022flta#awards

**Comment by fangeugene** [comment]
Fixed in #5470
I also refetched the events above.
