### ISSUE TITLE
2022dc305 data has been added to FRC Events, but not to TBA

### ISSUE THREAD

**Issue by inkling16** [the-blue-alliance/the-blue-alliance#4334]
Greater DC Event #1 Day 1 took a while to get their data uploaded, but it now exists on FRC Events: 
https://frc-events.firstinspires.org/2022/DC305

This data should be added to TBA

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by gregmarra** [comment]
Refreshed all the data, did not successfully get Awards - something is going on with the 3-number events and Awards, tracked in #4310
