### ISSUE TITLE
Playoff Match Tiebreakers and 2022wasam_qf6

### ISSUE THREAD

**Issue by timtim17** [the-blue-alliance/the-blue-alliance#4337]
## Expected Behavior

Per 2022 Rapid React game manual table 11-3, in the event of a tie in match score during quarterfinals, semifinals, or overtime, a series of tiebreak criteria should be checked to determine a winner.

This situation occurred in 2022wasam quarterfinal 6, in which the score was tied, but the blue alliance won due to hangar points.

![screenshot of final score screen](https://i.imgur.com/puWELcG.png)

On TBA, the blue alliance should be denoted as the winner (should they be? it *was* a tie...). No third tiebreaker match should appear, the alliance should be showing as advancing directly to semifinals.

## Current Behavior

On the event results page, qf6 is shown as a tie, and a third match that was never played is shown.

![screenshot](https://user-images.githubusercontent.com/6354860/159342973-bc40e7bb-efb6-4405-a4d0-78188225c765.png)

https://www.thebluealliance.com/match/2022wasam_qf2m3

## Steps to Reproduce (for bugs)

1. Navigate to https://www.thebluealliance.com/event/2022wasam
2. Observe the third match with no data, as it did not exist

## Context

This issue potentially affects the clarity and accuracy of event data, as a match that does not exist is displayed, and there is confusion on which alliance advanced.

## Your Environment

* Version used: Live site as of 3/21/2022
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox 98.0.1
* Operating System and version (desktop or mobile): Windows 10 21H2 (Build 19044.1586)

**Comment by phil-lopreiato** [comment]
Thanks for the report (and straightforwrad repro).

Implemented in #4339
