### ISSUE TITLE
Event page missing video icon for matches that do have videos

### ISSUE THREAD

**Issue by TechplexEngineer** [the-blue-alliance/the-blue-alliance#4338]
Some results pages (eg. https://www.thebluealliance.com/event/2022ctwat) are missing the video play icon for some matches (example is missing semis matches) but when you click into the match (https://www.thebluealliance.com/match/2022ctwat_sf1m1) a video is listed.

## Expected Behavior
If a video is listed on the match page the video icon should show.

## Current Behavior
Icon is missing for unknown reasons.
Does it have to do with the fact that when I submitted the playlist originally it was missing the semis matches but I have since added them to the playlist?

## Steps to Reproduce (for bugs)
1. See Semis Matches Here: https://www.thebluealliance.com/event/2022ctwat
2. Video is listed on match page https://www.thebluealliance.com/match/2022ctwat_sf1m1

## Your Environment
* Chrome 99.0.4844.51
* Ubuntu Linux 20.04

**Comment by gregmarra** [comment]
This might be a bug caused by caching pages to avoid regenerating them to save costs. If the video icon is still missing 24 hours later, then something else might be going on.

**Comment by phil-lopreiato** [comment]
This seems to have been resolved post-cache

Please let us know if you see this come up again for more than 24 hours!

![image](https://user-images.githubusercontent.com/2754863/159594089-81573a0e-d97a-466f-8075-8629cbe44f16.png)

**Comment by TechplexEngineer** [comment]
Thanks, will do
