### ISSUE TITLE
COVID Site Information Link Doesn't Work on Off-Season Events

### ISSUE THREAD

**Issue by neyre** [the-blue-alliance/the-blue-alliance#4375]
On the Chezy Champs page, the COVID site information link (highlighted in image below) brings to a non-existent page on the FIRST website. This link should probably not be visible for off-season events, or should be something that the event organizer needs to provide.

![image](https://user-images.githubusercontent.com/1348810/160506095-d228197f-d967-4983-bdc3-70f2124f4385.png)

**Comment by neyre** [comment]
This link is also bad and should probably be removed for off-seasons.

![image](https://user-images.githubusercontent.com/1348810/160507589-cd53029a-8d7f-4900-af9b-9bb2b08d2381.png)

**Comment by gregmarra** [comment]
I had incorrectly left this event marked as "Official". I've set that flag to False now - I think the cache will need a day to clear.

**Comment by neyre** [comment]
Thanks, Greg! That explains it.
