### ISSUE TITLE
Issue with Championship shortname

### ISSUE THREAD

**Issue by jaredhasenklein** [the-blue-alliance/the-blue-alliance#4382]
The short name for the championship is incorrectly parsing on team year pages (and likely other locations).

## Expected Behavior
Until teams are split into divisions, the short name should read **Championship (Houston)**. 

Once divisions are posted, the short name should read as the division name (e.g. Carver) with an additional line for teams making it to Einstein reading **Einstein (Houston)**.

## Current Behavior
Currently, the page reads **{} (Houston)**.
![image](https://user-images.githubusercontent.com/22439365/161113740-3ab2a1d4-13fd-44de-9fb8-ead3171c057b.png)

## Possible Solution
[This pages pulls](https://github.com/the-blue-alliance/the-blue-alliance/blob/py3/src/backend/web/templates/team_details.html#L41) the `comp.event.short_name`. [This line of code](https://github.com/the-blue-alliance/the-blue-alliance/blob/py3/src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_event_list_parser.py#L64) is supposed to handle the exceptions for cmptx before Einstein exists. It seems that the curly brackets are now being taken literally -- could be a py3 thing?

## Steps to Reproduce (for bugs)
Visit a team page for any team that has qualified for the Houston CMP.

## Your Environment
Web, desktop. A version of this problem has also occurred on mobile -- haven't yet investigated if it's pulling from the same source.

**Comment by ZachOrr** [comment]
This one is fixed by updating the `cmp_registration_hacks` sitevar. Details have been added to the runbook https://github.com/the-blue-alliance/the-blue-alliance/commit/c12638def225a00b1b9c86b5dd7459f2aa480233
