### ISSUE TITLE
Incorrect tiebreaks for district rankings

### ISSUE THREAD

**Issue by AGPapa** [the-blue-alliance/the-blue-alliance#4396]
## Current Behavior
I believe TBA is incorrectly calculating the 4th tiebreaker for district points.

https://www.thebluealliance.com/events/fma/2022#rankings

Team 5490 should be above 2234 because of the fourth tiebreaker ("most alliance selection points at single event").

Looking at the code it goes right from the third tiebreaker ("most total alliance selection points") to the fifth tiebreaker ("most total qualification points"). It doesn't seem to include the fourth tiebreaker ("most alliance selection points at single event")

## Possible Solution
Right here an additional tiebreaker needs to be added by getting the max alliance selection points (just like it's done for playoff points above). 
https://github.com/the-blue-alliance/the-blue-alliance/blob/fae07c92ce368af6e3161cc1c50ddcbe351b5dd5/src/backend/common/helpers/district_helper.py#L244

## Context
This issue has affected frclocks.com by showing team 2234 as qualified for the district championship instead of 5490.

**Comment by ZachOrr** [comment]
(for myself later) Section 11.8 Advancement Through the District Model of the manual has details on district ranking tiebreakers
<img width="831" alt="Screen Shot 2022-04-06 at 12 42 25 PM" src="https://user-images.githubusercontent.com/516458/162025318-4180775c-8729-46e0-98f9-64ec39f2171d.png">

**Comment by ZachOrr** [comment]
This is fixed! The website will be fixed when the cache clears - but here's the API response for this showing that 5490 is now properly ranked 59th, and 2234 60th
<img width="403" alt="Screen Shot 2022-04-06 at 8 25 47 PM" src="https://user-images.githubusercontent.com/516458/162096420-0a96f07a-2dd1-4563-8610-180c2b630de0.png">
