### ISSUE TITLE
Feature Request | Game Day Chat Remove button

### ISSUE THREAD

**Issue by arnon001** [the-blue-alliance/the-blue-alliance#4442]
Hello!,
Can you please add a disappear button for the Twitch chat in the gameday since its not so possible to watch on full screen with the chat (or make just a full screen button for the view).
Thanks, Arnon

**Comment by bdaroz** [comment]
There is an option to do just that:

Under Configure Layout (in the top right):
<img width="217" alt="image" src="https://user-images.githubusercontent.com/9668896/164919830-78bfa683-7b06-4eb9-aab1-2ca758804b4b.png">

At the bottom, you can disable the chat:
<img width="308" alt="image" src="https://user-images.githubusercontent.com/9668896/164920721-a58f5305-745a-4ac1-bb54-fe4c2e8792c8.png">
