### ISSUE TITLE
Round Robin Advancement Showing Wrong Values

### ISSUE THREAD

**Issue by neyre** [the-blue-alliance/the-blue-alliance#4444]
The hangar points column appears to be showing the total match score, not hangar points.

![image](https://user-images.githubusercontent.com/1348810/164944261-bd93b479-67f9-4a58-a58e-541ba1862b04.png)

**Comment by neyre** [comment]
@phil-lopreiato - possibly related to https://github.com/the-blue-alliance/the-blue-alliance/commit/9f446ebd86262d9adb38b8e0a134b0aaf56ab287

**Comment by noahbuttner** [comment]
Doesn't it have to do with https://github.com/the-blue-alliance/the-blue-alliance/blob/9f446ebd86262d9adb38b8e0a134b0aaf56ab287/src/backend/common/helpers/playoff_advancement_helper.py#L501-L504

Shouldn't be appending match score to tiebreaker 1

**Comment by phil-lopreiato** [comment]
Thanks for filing this originally :)
