### ISSUE TITLE
2017cmpmo event page gives a 500 error

### ISSUE THREAD

**Issue by legoktm** [the-blue-alliance/the-blue-alliance#4448]
## Expected Behavior

I expect to be able to see the event results/info.

## Current Behavior

![Screenshot 2022-04-25 at 01-43-54 The Blue Alliance](https://user-images.githubusercontent.com/81392/165027524-1979c239-dfcc-4993-ae4f-e387238b8bfc.png)

Compare with https://web.archive.org/web/20210121214245/https://www.thebluealliance.com/event/2017cmpmo

## Steps to Reproduce (for bugs)

1. Visit https://www.thebluealliance.com/event/2017cmpmo

## Context

Trying to reply to a Chief Delphi post...

## Your Environment

* Version used: ?
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox 99
* Operating System and version (desktop or mobile): Fedora 34/Qubes

**Comment by phil-lopreiato** [comment]
Thanks for the report; sorry this took so long to fix
