### ISSUE TITLE
2022 CMP should be displayed as "FIRST Championship"

### ISSUE THREAD

**Issue by FletcherS7** [the-blue-alliance/the-blue-alliance#4451]
2022 only had a single CMP for all teams.
Event name on FRC Events is "FIRST Championship" this year not "FIRST Championship - Houston" 

## Expected Behavior
Name of event on [event list page](https://www.thebluealliance.com/events/2022) should be "FIRST Championship"
Name of [2022cmptx](https://www.thebluealliance.com/event/2022cmptx) should be "Einstein Field"

## Current Behavior
Name of event on [event list page](https://www.thebluealliance.com/events/2022) says "FIRST Championship - Houston"
Name of [2022cmptx](https://www.thebluealliance.com/event/2022cmptx) is "Einstein Field (Houston)"

## Possible Solution
Update the event name in the Database

**Comment by fangeugene** [comment]
Fixed

**Comment by FletcherS7** [comment]
@fangeugene Blue banners for Einstein Winners, HoF, and Chairman's finalist still say Houston.
(Woodie Flowers is correct though)
![image](https://user-images.githubusercontent.com/10507571/199172227-d85488f6-d599-4422-847a-8dd49077c851.png)
![image](https://user-images.githubusercontent.com/10507571/199172510-f1a13861-534f-4b8b-9eff-ef36de27056d.png)
![image](https://user-images.githubusercontent.com/10507571/199172262-a1b32053-e2c0-454a-8fab-555869efeb8c.png)

Should Display
"2022 CHAMPIONSHIP"
