### ISSUE TITLE
incorrect teams in 2022cmptx finals

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#4457]
> In the Einstein Finals, team 6672 played in Finals 1 and 2, but TBA shows that 3175 played in them.

https://www.thebluealliance.com/event/2022cmptx
https://www.thebluealliance.com/match/2022cmptx_f1m1

**Comment by fangeugene** [comment]
This is an issue with FRC API v2. We reverted the switch to v3 because of 500's on FIRST's side. @phil-lopreiato knows the context better.

**Comment by fangeugene** [comment]
Fixed by #4466
