### ISSUE TITLE
Can't delete website from Offseason

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#4461]
https://www.thebluealliance.com/admin/event/2022mikk3

Trying to delete website to be null, but "None" just writes the literal string "None". Submitting null field doesn't update value.

**Comment by ZachOrr** [comment]
Closing for now since this event is removed

**Comment by gregmarra** [comment]
Empty string didn't seem to mutate the value.

**Comment by ZachOrr** [comment]
I can't repro Greg. An empty string worked fine for me. If you see this again though - feel free to ping me and I can take a look at what might be going on!
