### ISSUE TITLE
Pending Suggestions page links are unclickable

### ISSUE THREAD

**Issue by bdaroz** [the-blue-alliance/the-blue-alliance#4511]
The pending suggestions page (https://www.thebluealliance.com/suggest/review) has links that aren't clickable regularly. They can be rt-clicked and opened, or shift-clicked, but a regular left click doesn't work.

## Expected Behavior
Left click works.

## Current Behavior
Left click doesn't work.

## Steps to Reproduce (for bugs)
1. Open review page
2. Click

## Context
My shift key is taking unnecessary wear and tear.  😄 

## Your Environment
* 78 percent nitrogen
* 21 percent oxygen
* 0.9 percent argon
* 0.1 percent other gases

**Comment by ZachOrr** [comment]
Root issue (with link to offending commit/code) is here https://github.com/the-blue-alliance/the-blue-alliance/issues/3487

**Comment by bdaroz** [comment]
And you know I spent like 10 minutes trying to find that before I opened this.....

Closing as dupe
