### ISSUE TITLE
Suggestion: Add a way to get cards issued in a match

### ISSUE THREAD

**Issue by LoganAyers3461** [the-blue-alliance/the-blue-alliance#4547]
## Expected Behavior
Feature Suggestion For Ya (Or maybe I just havent found it yet)
Can you return any cards given during a match? maybe in the score breakdown field
in the 'red':{} and 'blue':{} add a field like 'redCards':{'teamkey'}, 'yellowCards':{'teamkey'}

## Current Behavior
I currently have only found a way to return if a team was disqualified but that isnt always because they got a red card that match, it could be carried over or there may have been another reason for it

## Context

Ive been messing around with the TBA API getting familiar with it, I have thought about constructing a scouting app or something similar for my team, I want to be able to compile as much information as I can so that our team members dont have to, we are a very small team and dont have any scouting people who can stay in the stands the whole event

For the record I am still a novice programmer and its entirely possible this already exists and I just havent been able to find it

## Your Environment

* Version used: APIv3, using Python aiotba wrapper https://pypi.org/project/aiotba/

* Environment name and version (e.g. Chrome 39, node.js 5.4):
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
* Operating System and version (desktop or mobile): Ubuntu 20.04.4 LTS 64 Bit
Gnome 3.36.8

**Comment by phil-lopreiato** [comment]
Unfortunately, FIRST's API upstream doesn't provide card info (at least last time I checked), so I don't think this is something TBA has any way of knowing about
