### ISSUE TITLE
Extended match notifications

### ISSUE THREAD

**Issue by synth3tk** [the-blue-alliance/the-blue-alliance#459]
A few things we can do within Gameday to alert the user of added matches to the ticker.

1.  Subtle background change, similar to [this](http://jsfiddle.net/UXfqd/). Doesn't need to be a bold contrast, since we're not trying to detract from the webcasts. Maybe a slightly lighter gray.
2.  Change the page title like Facebook or that Gmail labs feature. Set it to the number of new matches since the page had focus or activity (jQuery mouse tracking?).

Since there's no per-user alerts, though, they'll be receiving a lot of notifications, so number 2 might not be ideal for now.

I also think this should only apply to Gameday, not the rest of the site (once it's implemented there).

**Comment by gregmarra** [comment]
Going to close this for now, since the ticker has evolved significantly.
