### ISSUE TITLE
Change display name of Chairmans Award to Impact Award for 2023+

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance#4612]
https://www.firstinspires.org/robotics/frc/blog/2022-equity-diversity-and-inclusion-edi

**Comment by gregmarra** [comment]
Fixed by https://github.com/the-blue-alliance/the-blue-alliance/pull/5057

Example showing Impact Award and not Chairmans https://www.thebluealliance.com/event/2023bcvi#awards
