### ISSUE TITLE
My TBA seems broken

### ISSUE THREAD

**Issue by Sprink02** [the-blue-alliance/the-blue-alliance#4811]
In the app changing favorites or notification settings do not work

On web it errors
![Screenshot_20221017-093039_Chrome Canary.png](https://user-images.githubusercontent.com/69661817/196232631-493802f0-3042-47af-8480-9e9c76ceec48.png)

**Comment by ZachOrr** [comment]
This is because the `login_required` endpoint no longer exists. However - how we're getting there from this point I'm still unsure.

**Comment by gregmarra** [comment]
This needs to be updated for py3

**Comment by gregmarra** [comment]
Closing this one as old, since it seems to affect the mobile apps which I think are working now? Can reopen if I am wrong.

https://github.com/the-blue-alliance/the-blue-alliance/issues/5092 for modern issues.
