### ISSUE TITLE
2023 districts missing events

### ISSUE THREAD

**Issue by lethosor** [the-blue-alliance/the-blue-alliance#4936]
## Expected Behavior
https://www.thebluealliance.com/events/chs/2023#events and https://www.thebluealliance.com/api/v3/district/2023chs/events should return a non-empty list of events

## Current Behavior
The API endpoint returns `[]` and the web endpoint renders an empty list:
![image](https://user-images.githubusercontent.com/3719547/210924408-e905c181-1049-4d06-bdac-86bdc142dfd6.png)

This is the same for all other 2023 districts, but not 2022.

## Steps to Reproduce (for bugs)
See links above

or:
```sh
curl -H "X-TBA-Auth-Key: $KEY" 'https://www.thebluealliance.com/api/v3/district/2023chs/events'
```

## Context
This started happening within the last 24 hours.

I'm not seeing an obvious cause - the only recent code changes are dependabot updates and https://github.com/the-blue-alliance/the-blue-alliance/pull/4847, none of which appear to affect districts, let alone 2023 only.

## Your Environment
Chrome 108
curl 7.81

**Comment by dracco1993** [comment]
@lethosor This is an issue on FIRST's side.  They are aware of it and working on a fix.  🙂

**Comment by kevinwross** [comment]
Are there any updates on this? Our video recording software uses this data.

**Comment by ZachOrr** [comment]
This got fixed upstream, so it's fixed on the site!
