### ISSUE TITLE
Attempting to add webhook gives 404

### ISSUE THREAD

**Issue by adamsong** [the-blue-alliance/the-blue-alliance#4955]
## Expected Behavior

Clicking the Add Webhook button on the account page should initiate the webhook creation process.

## Current Behavior

The Add Webhook button redirects to a 404

## Possible Solution

Either make `/webhooks/add` work, or fix the link under the button

## Steps to Reproduce (for bugs)

1. Navigate to [account page](https://www.thebluealliance.com/account)
2. Click "Add Webhook"
3. Be taken to a 404

## Context

I cannot make a webhook

## Your Environment

* Version used: Unsure how to gather this, whatever was live as of Jan. 17, 2023 at 6:06 PM EST
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox Version 108.0.2 (64-bit)
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by BrenekH** [comment]
I'm also running into this issue when creating or deleting a webhook. And I don't know if this is related, but I'm not getting events sent to my existing webhook except for the ping event when I trigger it myself.

**Comment by Theinatorinator** [comment]
Same issue!

**Comment by ZachOrr** [comment]
The webhooks routes haven't been ported to py3. I'm unsure why we're not default routing these requests to the py2 instance though...

**Comment by gaborszita** [comment]
Same issue - TBA developers - when is this expected to be fixed?

**Comment by gregmarra** [comment]
This should be fixed by  https://github.com/the-blue-alliance/the-blue-alliance/pull/5094 , how are things looking now?
