### ISSUE TITLE
myTBA Button Redirects to Wrong Link

### ISSUE THREAD

**Issue by spidernh** [the-blue-alliance/the-blue-alliance#5034]
myTBA button redirects to the wrong link

## Expected Behavior
When clicking the "myTBA" button on the top of the window, the user should be redirected to the URL ."https://www.thebluealliance.com/account/mytba"

## Current Behavior
When clicking the "myTBA" button on the top of the window, the user is redirected to the URL "https://www.thebluealliance.com/mytba," which lacks the "/account" before "mytba," resulting in error 500.

## Possible Solution
Change the redirect URL to the correct one.

## Steps to Reproduce (for bugs)
Example: https://youtu.be/EtLW-lFmd1M
1. Open "https://www.thebluealliance.com/"
2. Login
3. Click the "myTBA" button at the top

## Context
I've been trying to get to myTBA and instead had to go to my account page and use the link there.

## Your Environment
Firefox 105.0.3, Windows 10

**Comment by fangeugene** [comment]
the myTBA button is supposed to link to `thebluealliance.com/mytba`. `/account/mytba` is a settings page.

The fact that it's 500ing is an issue though. I will investigate.
