### ISSUE TITLE
Fix social media styling in navbar

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#5039]
#5037 seems to have broken this
cc @AndrewKe 

![image](https://user-images.githubusercontent.com/1421884/221786968-6d448909-899f-4aeb-a5c4-6ba7cb5e74f7.png)

**Comment by AndrewKe** [comment]
shoot not sure how I missed that 🤦‍♂️, feel free to revert

**Comment by fangeugene** [comment]
Minor enough I'm not going to invert. Rather track down the bug. Looks like this is invalid syntax, but not sure why...

![image](https://user-images.githubusercontent.com/1421884/221794903-a014dcfd-c328-4093-abaf-b99309a9dea7.png)
