### ISSUE TITLE
API docs not loading

### ISSUE THREAD

**Issue by dcarr622** [the-blue-alliance/the-blue-alliance#5083]
## Expected Behavior
API docs load https://www.thebluealliance.com/apidocs/v3

## Current Behavior
API docs are blank. There are some errors in the console

![image](https://user-images.githubusercontent.com/7507881/224180101-cfa261b0-fd6d-4738-8df2-7c6966276602.png)

![image](https://user-images.githubusercontent.com/7507881/224180175-c6c8db53-14dc-4599-a1be-d29c6e158c40.png)

## Steps to Reproduce (for bugs)
Visit https://www.thebluealliance.com/apidocs/v3

## Your Environment
Tested from Chrome and Safari.

**Comment by gregmarra** [comment]
This appears to have resolved itself. https://www.thebluealliance.com/apidocs/v3 loads the API docs for me with functional JS.

**Comment by brycematsuda** [comment]
Seems to have broken again as of 3/16/2023 12:40AM EDT.

**Comment by gregmarra** [comment]
https://github.com/the-blue-alliance/the-blue-alliance/pull/5087 appears not to have stuck, as Dependabot bumped the version anyway.

**Comment by ZachOrr** [comment]
This should be fixed now.
