### ISSUE TITLE
Handle new CMP divisions "Milstein" & "Johnson"

### ISSUE THREAD

**Issue by eforbes** [the-blue-alliance/the-blue-alliance#5153]
There are some exceptions for world cmp divisions in TBA and I want to confirm the new divisions are going to be correctly handled:

https://github.com/the-blue-alliance/the-blue-alliance/blob/0a7a338540bd3f523d9bf70b803efbab74a9e6e2/src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_event_list_parser.py#L53

https://github.com/the-blue-alliance/the-blue-alliance/blob/0a7a338540bd3f523d9bf70b803efbab74a9e6e2/src/backend/tasks_io/datafeeds/datafeed_fms_api.py#L67

New division names are in the manual (section 11.9.4) but are not yet on frc.events

**Comment by fangeugene** [comment]
Historically we've done 3 letters except for cars/carv, but my vote here is for `mils` and `john`. @phil-lopreiato @ZachOrr any preferences?

**Comment by ZachOrr** [comment]
I'm good with that! 👍

**Comment by fangeugene** [comment]
Actually it looks like statbotics is using `mil` and `joh`
