### ISSUE TITLE
Improve "real-time-ness"

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#518]
Right now a cron job gets matches from USFIRST every X minutes. This makes GameDay's feedbar not update for a few minutes, and suddenly update with several matches at once, which isn't the best experience. Also, "upcoming matches" on event and team pages may be off by 1 or 2 matches because the cron job simply hasn't run yet.
TLDR: our implementation for displaying real-time information is good; the problem is not getting the matches quickly enough after they are played.

Ideas:
Unfortunately GAE doesn't support long-lived HTTP requests that we can use to consume Twitter's @FRCFMS streaming feed. we could poll Twitter's REST API once every 5 seconds (or slower) without hitting the rate limit, but that might cost us too many front end instance hours.

If we set up an endpoint for pushed data, we could write something that uses Twitter's streaming API that runs on another server to push matches to TBA as they are played. Or run a separate free GAE instance that polls Twitter with the above method and pushes matches to TBA. We could reuse this endpoint if/when FIRST decides to push us data directly.

Thoughts?

**Comment by gregmarra** [comment]
With the new FRC API, I think we'll remain constrained to polling for now.
