### ISSUE TITLE
27 Match Score notifications for one match

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance#5199]
I received this notification from the TBA Android app ~~14~~ 20+ times (so far) over ~~20 minutes~~ 7+ hours:

**Team 2910 GAL Q60 Results**  
4786, 8033, 5586 beat 2910, 2337, 2383 scoring 175-149.

and one of these notifications:

**GAL Q60 Results**  
Galileo Division Qual 60: 4786, 8033, 5586 beat 2910, 2337, 2383 scoring 175-149.

while following only one of those teams.

## Expected Behavior

One Match Score notification per relevant match.

## Current Behavior

This season, match results have been replicated often, typically 4-6 notifications per match. ~~15~~ This is a new high score.

## Possible Solution

The bug could be in TBA'S use of Firebase, but as a workaround, the app could deduplicate its incoming notifications.

## Steps to Reproduce (for bugs)

1. In myTBA, register for Match Scores for a favorite team.
2. Maybe it matters that I'm also registered for Alliance Selections notifications for that team; also for Match Scores, Alliance Selections, and Awards Posted for a second team on a different Championship division.
3. Watch for notifications during qualification matches.

## Context

I'm trying to keep tabs on two favorite teams while doing other things. Excess notifications are excess interruptions.

## Your Environment

* Version used: TBA Android 8.0.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Pixel 6
* Operating System and version (desktop or mobile): Android 13

**Comment by ZachOrr** [comment]
Closing as #5668 duplicates
