### ISSUE TITLE
Firebase Migration

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#5340]
Email subject "[Action Required] Update your apps to the latest Firebase Cloud Messaging APIs and SDKs"

> We’re writing to let you know that starting June 20, 2024 the legacy Firebase Cloud Messaging (FCM) APIs will be discontinued.

> On June 20, 2024, we’re reducing the number of Firebase Cloud Messaging (FCM) legacy register APIs and legacy send APIs that provide similar functionality. This step will allow us to provide you with a more consistent experience and align with Google security standards to improve security, reliability and performance.

**Comment by ZachOrr** [comment]
fwiw I *think* we're good here. This work got done with the big TBANS work, along with Android adopting it as opposed to using the old GCM stuff. Going to close but - if we see any problems, we can re-open
