### ISSUE TITLE
myTBA Team selection not saving

### ISSUE THREAD

**Issue by advay-c** [the-blue-alliance/the-blue-alliance#5450]
When trying to favorite a team on myTBA team there is a bug which doesn't allow your selection to be saved. Once you press save after you made your selection it brings you to a new page stating '405 method not allowed'.

**Comment by Lynzzyr** [comment]
Similar behavior happens for me as well. After selecting a selection of subscriptions for a team, pressing "Confirm" leads to a page stating "Method Not Allowed" with text "The method is not allowed for the requested URL."
