### ISSUE TITLE
2022 North Star Award Missing

### ISSUE THREAD

**Issue by JonStratis** [the-blue-alliance/the-blue-alliance#5468]
## Expected Behavior

Both Dean's List Finalist Award winners should be listed on the event page.

## Current Behavior

Only 1 Dean's List Finalist is listed on the 2022 Minneapolis North Star Regional award page.  Both are shown on frc-events correctly.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by fangeugene** [comment]
FRC events shows one winner twice https://frc-events.firstinspires.org/2022/MNMI2/awards

<img width="673" alt="image" src="https://github.com/the-blue-alliance/the-blue-alliance/assets/1421884/0c829fad-1d0e-4d6a-899e-79100870cde8">

**Comment by JonStratis** [comment]
Those are two separate individuals, Megan and Mairin, from the same team.  Yes, their names are quite similar.

**Comment by fangeugene** [comment]
My bad, it was late. Thanks I'll investigate further.
