### ISSUE TITLE
Eventwizard2 doesn't load, doesn't error

### ISSUE THREAD

**Issue by jaredhasenklein** [the-blue-alliance/the-blue-alliance#5513]
When going to https://www.thebluealliance.com/eventwizard2, the header/footer loads, but content does not.

## Expected Behavior
I can't remember if EW2 was folded in to become the main EW page, or if there is still a separate EW and EW2. If they are separate, the page should load. If they are now one, the page should either provide an error message or redirect to main EW.

## Current Behavior
See screenshot:
![image](https://github.com/the-blue-alliance/the-blue-alliance/assets/22439365/47750b16-4b65-4220-ab90-9ef98dec8893)

## Possible Solution
Maybe wasn't ported over to py3?
Otherwise, if there isn't supposed to be a separate EW and EW2, just set up a redirect

## Steps to Reproduce (for bugs)
1. Visit https://www.thebluealliance.com/eventwizard2

## Context
I was trying to use Event Wizard, and remember that EW2 did a few extra snazzy things.

## Your Environment
Latest Chrome, Windows 11

**Comment by fangeugene** [comment]
This seems to affect non-admin accounts so it's probably some API permissions issue.

**Comment by fangeugene** [comment]
JK it's a devtools thing

**Comment by jaredhasenklein** [comment]
Can confirm that this is fixed by #5528. TBA/eventwizard2 loads for me again. Thanks, Eugene!
