### ISSUE TITLE
Data ingestion: frc8546 ("\n") and 2023brd

### ISSUE THREAD

**Issue by timtim17** [the-blue-alliance/the-blue-alliance#5548]
## Expected Behavior

Team 8546, "\n", should appear as a team on the event page for 2023brd, and the event "Bordie Charged 2023" should appear on the team detail page for frc8546.

## Current Behavior

The team is not listed on the list of teams on the event page, though the team does appear in match results. The event does not show on the team detail page.

## Possible Solution

Perhaps an issue ingesting data? Team shows correctly on FRC-Events.

## Steps to Reproduce (for bugs)

https://www.thebluealliance.com/event/2023brd#teams
https://www.thebluealliance.com/team/8546/2023
https://frc-events.firstinspires.org/2023/WABEL
https://frc-events.firstinspires.org/2023/team/8546
1. Navigate to event page for 2023brd and select "Teams". Observe 8546 is not listed.
2. Navigate to team page for frc8546 for 2023. Observe "Bordie Charged 2023" is not listed.
3. Observe on FRC-Events that the team/off-season event is listed upstream.

<img width="1241" alt="image" src="https://github.com/the-blue-alliance/the-blue-alliance/assets/6354860/160de32a-0470-4b3d-9b66-1b5e92d2b46f">

<img width="1350" alt="image" src="https://github.com/the-blue-alliance/the-blue-alliance/assets/6354860/48b6c759-55d3-4963-96d4-73a87a108b2f">

## Context

Off-season data accuracy

## Your Environment

* Version used: Prod TBA (`This page was generated on Oct. 17, 2023 at 12:06 PM`)
* Environment name and version (e.g. Chrome 39, node.js 5.4): Edge 116.0.1938.81 (Official build) (arm64) 
* Operating System and version (desktop or mobile): macOS Version 13.5.2 (Build 22G91)

**Comment by fangeugene** [comment]
Fixed, though it may take some time for caches to clear on the website.
