### ISSUE TITLE
Satus Endpoint Displays Incorrect Win Information

### ISSUE THREAD

**Issue by J-Barta** [the-blue-alliance/the-blue-alliance#5639]
The `team/{team_key}/events/{year}/statuses` Endpoint occasionally displays that a team won an event that they actually didn't win. 

## Expected Behavior
The endpoint only displays a playoff status of "won" if the team actually won the playoffs.

## Current Behavior
Certain teams at certain events are incorrectly displayed as having "won" playoffs that they lost either in the semifinals or in the fnials.

## Possible Solution
Restructure how a team's status for an event is determined to use the new double-elimination format.

## Steps to Reproduce (for bugs)
Team 51 in 2024 has this issue. It can be viewed for the `2023iri` event, which says that they won the event even though they did not. Here is a link to the endpoint that includes this issue: `https://www.thebluealliance.com/api/v3/team/frc51/events/2023/statuses
`

## Context
Our team (5907), is developing a scouting application, and we want to display the blue banners for events a team has won just like the team pages on the TBA website do. For this, we need to know which events that team won, so an incorrect display doesn't work.

## Your Environment
Running in a React project, but it's a problem with the API endpoint

**Comment by phil-lopreiato** [comment]
I believe this was due to not having proper support for double elim tournaments; this should have been fixed in https://github.com/the-blue-alliance/the-blue-alliance/pull/5689
