### ISSUE TITLE
Internal server error when viewing 2021 game design challenge event

### ISSUE THREAD

**Issue by sciencewhiz** [the-blue-alliance/the-blue-alliance#5666]
the following page for the 2021 game design challenge event produces an internal server error
https://www.thebluealliance.com/event/2021gamce

## Expected Behavior
Displays the page

## Current Behavior
internal server error

## Steps to Reproduce (for bugs)

1. Click on the link above

## Context
researching the 2021 game design winners and finalists since their games were remixed for the 2024 game

**Comment by fangeugene** [comment]
Fixed
