### ISSUE TITLE
Match result notifications often send multiple times

### ISSUE THREAD

**Issue by letsdothisepic** [the-blue-alliance/the-blue-alliance#5668]
**Describe the bug**
I’ve subscribed to match notifications for my teams, but the notifications often send multiple times. An example is included in the screenshots.

**To Reproduce**
As simple as above, in my case I favorited Team 5907, and then turned notifications on for everything except for match video added.

**Expected behavior**
I should only get one notification.

**Screenshots**
![DFFA667C-FE2C-49EC-8727-35C60AD239D6](https://user-images.githubusercontent.com/24259533/233402983-f74354b8-0b16-4f72-99c4-6f24bcb998c0.png)

**Your Environment (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.3.1
 - TBA for iOS Version: v3.3.1 (99)

**Additional context**
—

**Comment by ZachOrr** [comment]
As a note - we've removed all the retry mechanisms from the notification sending, and the push notification queue is set to only try tasks once. This is related to the backend tasks getting kicked off multiple times and sending notifications when data changes.

**Comment by ZachOrr** [comment]
Related - my tracking issue for some of the backend-related tasks can be found here https://github.com/the-blue-alliance/the-blue-alliance/issues/5119

**Comment by ZachOrr** [comment]
https://github.com/the-blue-alliance/the-blue-alliance/pull/5781 was merged to make sure this isn't an issue with tasks failing in the push notification queue and getting retried - something we saw a while back

**Comment by ZachOrr** [comment]
https://github.com/the-blue-alliance/the-blue-alliance/pull/5800 adopts the old GCM system for marking matches as having their push notifications sent. This logic might need to go somewhere further up, but this should help with the duplicate match results notifications (unfortunately won't have an impact on the awards or alliance selections)

**Comment by ZachOrr** [comment]
Both https://github.com/the-blue-alliance/the-blue-alliance/pull/4620 and https://github.com/the-blue-alliance/the-blue-alliance/pull/4621 removed the retry logic from TBANS in order to make sure the internal notification retry logic isn't the bit of code that's getting these notifications stuck in a second loop.

It's likely from tasks retrying, as outlined in https://github.com/the-blue-alliance/the-blue-alliance/issues/5119

**Comment by ZachOrr** [comment]
https://github.com/the-blue-alliance/the-blue-alliance/pull/5805 shuffles around the `push_sent` code which seemed like it was incorrect due to bypassing the model caching when setting that field

**Comment by ZachOrr** [comment]
Going to leave this open throughout the weekend, but this is one step closer to getting resolved (see https://github.com/the-blue-alliance/the-blue-alliance/issues/5119#issuecomment-2013519499). It should be MUCH better than before. The only thing that will send duplicate notifications is for Event subscriptions for users subscribed to an entire year + individual events, which isn't a flow we support for the mobile apps and should only be a problem for our webhook consumers. Webhook consumers: maybe just don't subscribe to individual events + an entire season for now.

**Comment by ZachOrr** [comment]
Marking this one as resolved - but will re-open if the problem continues. The only cases of duplicate notifications that have been reported currently are TestFlight users having multiple mobile clients with the same push token in their account.

**Comment by ofekashery** [comment]
@ZachOrr Thank you for your hard work ❤️
