### ISSUE TITLE
Logging in does not work in iOS Web Clip

### ISSUE THREAD

**Issue by TheGamer1002** [the-blue-alliance/the-blue-alliance#5798]
## Expected Behavior

When logging in, the webpage control bar at the top shows up and the Google or Apple login screen appears.
Here’s an example from a lichess.org web clip.
![IMG_1559](https://github.com/the-blue-alliance/the-blue-alliance/assets/48131223/edc9aad8-40a4-448f-b9fc-c582d41897cc)

## Current Behavior

Pulls up an about:blank page with no login screen.
## Possible Solution

I haven’t the foggiest idea.
## Steps to Reproduce (for bugs)

1. Go to the TBA website
![IMG_1550](https://github.com/the-blue-alliance/the-blue-alliance/assets/48131223/a1e7a021-c985-42ab-9b53-f5e2ac1c1b77)
2. Tap the share menu and press “Add to Home Screen”
![IMG_1551](https://github.com/the-blue-alliance/the-blue-alliance/assets/48131223/02d4cfde-119d-4496-8050-9294d2f87214)
3. Press “Add”
![IMG_1552](https://github.com/the-blue-alliance/the-blue-alliance/assets/48131223/8e7fd536-100f-4a7f-8f3c-d9a809fc39f1)
4. Go to Home Screen and open newly-added Web Clip
![IMG_1553](https://github.com/the-blue-alliance/the-blue-alliance/assets/48131223/bc99948a-7361-4025-8020-ee122155bd28)
5. Go to a page that redirects to the login screen, e.g. myTBA
![IMG_1554](https://github.com/the-blue-alliance/the-blue-alliance/assets/48131223/80288555-aa8c-4e16-9cc9-4b1fff52b1e0)
6. Press either of the Login with Apple or Google buttons and observe
![IMG_1555](https://github.com/the-blue-alliance/the-blue-alliance/assets/48131223/18c3bc17-4f94-48d3-8947-03f942fb70a4)

## Context

This bug completely breaks any feature that involves logging in.

The website definitely has to support Web Clips, as per the HTML meta tags.
![IMG_1556](https://github.com/the-blue-alliance/the-blue-alliance/assets/48131223/baa44698-00be-42ee-9ca4-e2831e7c0dd1)
![IMG_1558](https://github.com/the-blue-alliance/the-blue-alliance/assets/48131223/80924ef1-f965-43ce-85e9-d4d4fdee71df)

Interestingly, [Web Clips support notifications now.](https://developer.apple.com/documentation/usernotifications/sending-web-push-notifications-in-web-apps-and-browsers) That might be smart to implement for things like followed teams.

## Your Environment

* Version used: Webpage generated on Mar. 15, 2024 at 9:35 AM
* Environment name and version (e.g. Chrome 39, node.js 5.4): iOS 17.1.2 (including Safari and WebView)
* Operating System and version (desktop or mobile): mobile, iPad 8th gen

**Comment by ZachOrr** [comment]
Thanks for this! I'm actually unable to repro this (iOS 17.3.1, iPhone 15 Pro, Safari). Might need to dig in a little deeper to see what's happening.

**Comment by ZachOrr** [comment]
Going to close this since I cannot repro. If someone can repro and get some more info - like a console log - feel free to re-open.
