### ISSUE TITLE
Most matches insight is incorrect

### ISSUE THREAD

**Issue by rjbell4** [the-blue-alliance/the-blue-alliance#5829]
The list of "Most Matches Played" is incorrect.

## Expected Behavior
9496 has competed in 41 matches, and should be on the list

## Current Behavior
9496 is missing from the list, as is an entry for anyone with 41 matches (there might not be any more).

## Steps to Reproduce (for bugs)
https://www.thebluealliance.com/insights/2024

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by ZachOrr** [comment]
The most recent insights was computed at Mar. 20, 2024 at 11:53AM UTC - roughly 7am EST. We've been backfilling Week 3 match schedules today as they've become available from the frc-api. It's likely this will resolve once we re-compute insights with the updated data.

**Comment by ZachOrr** [comment]
Marking as resolved - this seems right upstream now
