### ISSUE TITLE
Messed up team list for Finals 2 of 2024onosh

### ISSUE THREAD

**Issue by Chris857** [the-blue-alliance/the-blue-alliance#5833]
Finals 2 of https://www.thebluealliance.com/event/2024onosh shows
"[Finals 2](https://www.thebluealliance.com/match/2024onosh_f1m2) 	[1241](https://www.thebluealliance.com/team/1241/2024) 	[1285](https://www.thebluealliance.com/team/1285/2024) 	[1241](https://www.thebluealliance.com/team/1241/2024) 	[9621](https://www.thebluealliance.com/team/9621/2024) 	[5460](https://www.thebluealliance.com/team/5460/2024) 	[3543](https://www.thebluealliance.com/team/3543/2024) 	[5460](https://www.thebluealliance.com/team/5460/2024) 	[5406](https://www.thebluealliance.com/team/5406/2024) 	65 	51", which is too many teams and duplicates 1241 and 5460.

**Comment by phil-lopreiato** [comment]
Thanks for letting us know!

This is relayed to the sync issues happening with the FIRST API for week 3 events. We've refetched all the events, but the old broken data may still be in cache for a little while longer, so it should be resolved shortly.
