### ISSUE TITLE
Misplaced "1" character?

### ISSUE THREAD

**Issue by TapChap** [the-blue-alliance/the-blue-alliance#5891]
https://github.com/the-blue-alliance/the-blue-alliance/blob/f05b6191cf6d447696db8d3371aba07265d7eb0f/src/backend/web/templates/404.html#L12

in the 404 page, it says `Oh Noes!1!!` is it possible that when written the shift key was accidentally released and a "1" was typed instead of a "!" ?

**Comment by ZachOrr** [comment]
![image](https://github.com/the-blue-alliance/the-blue-alliance/assets/516458/1aff9d18-2386-4874-9b1e-594d866378ab)
