### ISSUE TITLE
Repo is currently uncloneable on Windows

### ISSUE THREAD

**Issue by dracco1993** [the-blue-alliance/the-blue-alliance#6173]
## Expected Behavior
People can clone (and pull) the repo

## Current Behavior
`git` errors on pulling commit 5aeacd839798cb9cac366532ba0ab63a7bdfdcb5 (added in the-blue-alliance/the-blue-alliance#5990)

## Possible Solution
Remove the files?
Rename them?
🤔 

## Steps to Reproduce (for bugs)
Attempt to clone (or pull from an older version) on Windows

## Context
Unable to do anything.  😱 

## Your Environment

* Version used: N/A
* Environment name and version (e.g. Chrome 39, node.js 5.4): N/A
* Operating System and version (desktop or mobile): Windows 11

**Comment by dracco1993** [comment]
I've tried several different fixes from various sources, to no avail so far.

**Comment by bdaroz** [comment]
I'm guessing w/o seeing the error messages it doesn't like the `?` in the file paths?

**Comment by dracco1993** [comment]
@bdaroz At first it was the `:` in file names, which @fangeugene addressed, but now it's the `?`, as you mentioned.
