### ISSUE TITLE
ct state champs data

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#638]
Here is the team list:
155 The Techno-Nuts
173 R.A.G.E.
175 Buzz Robotics
176 Aces High
177 Bobcat Robotics
178 The 2nd Law Enforcers
181 Birds Of Prey
195 Cyber Knights
228 GUS Robotics
230 Gaelhawks
236 Techno-Ticks
237 Black Magic
558 Robo Squad
571 Team Paragon
999 MechaRams
1071 Team Max
1099 Disco Techs
1124 ÜberBots
1699 Robocats
1740 Cyber Colonels
1784 Litchbots
1991 Dragons
2064 The Panther Project
2067 Apple Pi
2168 Aluminum Falcons
2170 Titanium Tomahawks
2836 Team Beta
3104 The Cyber Rams
3146 Granby Grunts
3182 Athena's Warriors
3461 Operation PEACCE Robotics
3464 Sim-City
3525 The Nuts & Bolts of Fury
3555 Aluminati
3634 Hard Botties
3654 Tech Tigers
3718 Junkyard Battalion
3719 STEM Whalers
4055 NRG
4557 Full Metal Falcons
4628 Sintian Robotics
4812 Crosby Robotics Team

Now here is the Eliminations round
#1: 228 195 3104    SF
#2: 2168, 230, 2064 F
#3: 2067 175 155    SF
#4: 4055 1991 178  QF
#5: 558 177 1699    W
#6: 176 2170 3525  QF
#7: 1124, 181, 236  QF
#8: 1784 237 571    QF

Event Info Page: http://www.casciac.org/scripts/shownews.cgi?story=1329

**Comment by synth3tk** [comment]
[Event created](http://www.thebluealliance.com/event/2013ctsc) and teams added. Unsure where to get the match results, though.

**Comment by phil-lopreiato** [comment]
I can check and see if I have it laying around somewhere, but I don't think I was at this one, so no promises.

**Comment by synth3tk** [comment]
@phil-lopreiato I take it you couldn't find this data anywhere?

**Comment by fangeugene** [comment]
Can't do more without match data.
