### ISSUE TITLE
API for Event Realtime

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#67]
API to return teams, scores of last match, teams of next match, teams of match after that, and what matches those were.

**Comment by SUPERCILEX** [comment]
@phil-lopreiato I think this api exists now so this issue can be closed.

**Comment by fangeugene** [comment]
Doesn't technically exist, but between the team@event and team/event/matches endpoints, I don't see a need for this endpoint. Marking this as "won't fix" for now.
