### ISSUE TITLE
Redirect http://www.thebluealliance.net/tbatv/team/ links

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#685]
http://www.thebluealliance.net/tbatv/team/1592 404's, but links of that form are prevelent in existing sig images.

Chris, can you do an easy mod_rewrite rule?

**Comment by SUPERCILEX** [comment]
@phil-lopreiato At this point, I don't think the issue is relevant anymore.

**Comment by fangeugene** [comment]
I don't think we really care about ".net" redirects at this point. @phil-lopreiato @gregmarra ?

**Comment by phil-lopreiato** [comment]
Nope, don't care. Do we even still own .net?

**Comment by fangeugene** [comment]
Yes, for videos. http://videos.thebluealliance.net/

**Comment by phil-lopreiato** [comment]
Oh, right. I don't think anybody really uses the old team page urls anymore so it's not worth to set up redirects (somebody would have complained by now if it was really important)

**Comment by synth3tk** [comment]
Agreed. The scream test would have been failing by now if it were being used at all. I vote close.
