### ISSUE TITLE
Parse Score Breakdown from Twitter

### ISSUE THREAD

**Issue by wolfgang42** [the-blue-alliance/the-blue-alliance#722]
The @frcfms twitter feed [provides a breakdown of the scores](http://www.usfirst.org/sites/default/files/uploadedFiles/Robotics_Programs/FRC/Game_and_Season__Info/2013/2013FMSTwitterFeed_Rev0.pdf) for each match (foul points, auto score, teleop disk points, etc). Is it possible to add this information to the API? I don't have a twitter account, so I can no longer access this information via the Twitter API.

**Comment by gregmarra** [comment]
The FRC API will be the new way we get data, FRCFMS may not exist in the future.

**Comment by fangeugene** [comment]
Does not exist anymore*
