### ISSUE TITLE
thebluealliance.net team links not properly redirecting

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#786]
http://www.thebluealliance.net/tbatv/team/254 redirects to a 404 page instead of http://www.thebluealliance.com/team/254

**Comment by SUPERCILEX** [comment]
@phil-lopreiato This issue is no longer relevant.

**Comment by fangeugene** [comment]
See https://github.com/the-blue-alliance/the-blue-alliance/issues/685#issuecomment-299899909
