### ISSUE TITLE
Google Page Speed suggestions

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#839]
https://developers.google.com/speed/pagespeed/insights/?tab=desktop&url=http%3A%2F%2Fwww.thebluealliance.com%2F

**Comment by bdaroz** [comment]
I looked at this report again. Some CSS that could be optimized or made non-blocking, and the caching, but nothing serious or really worth the effort for a very small gain.

**Comment by fangeugene** [comment]
Good enough for now.
