### ISSUE TITLE
Proper Memcache Expiration

### ISSUE THREAD

**Issue by brandondean** [the-blue-alliance/the-blue-alliance#863]
I just want to get the conversation started with regards to busting old caches in memcache, without having to rely on just expiration times.

I know there has been conversations here and there about it, but nothing really solid (from what I can tell). I think it'll be beneficial if we try to tackle it for year's competition season – especially since edge-caching is in use and it would be unfortunate if an edge cache expired and then got an out of date memcache response.

**Comment by fangeugene** [comment]
Caching has been reworked since then.
