### ISSUE TITLE
Suggest searching when no Team media

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#904]
Link photos to search CD via http://www.chiefdelphi.com/media/photos/tags/frc1234

Link video to search YouTube by searching "frc177"

These don't need to be year specific - better to get something than nothing!

**Comment by jaredhasenklein** [comment]
Obviously this is a very old issue. Is this still something we want to implement? 

The new search syntax would need to be something like:
https://www.chiefdelphi.com/search?q=tag%3Afrc254%20category%3A11

Adding `category:11` to the query will search cd-media only. You could also do something like https://www.chiefdelphi.com/search?q=tag%3Afrc254%20category%3A11%202011 to search for items tagged frc254 with the query of 2011.
