### ISSUE TITLE
Freeze API v2

### ISSUE THREAD

**Issue by brandondean** [the-blue-alliance/the-blue-alliance#915]
Make the final call on the models, and ensure all changes moving forward are backwards compatible.

Once we think we are good here we should announce it on ChiefDelphi and the developer list to try to pressure people to move to the new API. It's faster, more reliable, easier to maintain, and generally better.

Anyone want to poke holes in the current model before we want to proceed?

**Comment by bdaroz** [comment]
With work on v3 progressing, perhaps a cleanup close of this is warranted?

**Comment by SUPERCILEX** [comment]
@phil-lopreiato Agreed with @bdaroz, this issue should be closed now.

**Comment by fangeugene** [comment]
v2 should be deprecated within the year. Time for v3.
