### ISSUE TITLE
Central Illinois matches not updating 

### ISSUE THREAD

**Issue by nightpool** [the-blue-alliance/the-blue-alliance#921]
The Upcoming/Recent matches list on the [Central Illinois](http://www.thebluealliance.com/event/2014ilil) event page aren't updating. The twitter feed is working fine (https://twitter.com/search?q=%23frcilil&f=realtime) and other regionals (such as [Palmetto](http://www.thebluealliance.com/event/2014scmb)) are updating as normal.

**Comment by SUPERCILEX** [comment]
@phil-lopreiato This issue probably isn't relevant anymore.

**Comment by fangeugene** [comment]
No longer relevant.
