### ISSUE TITLE
Someone is making over 10 requests/sec to our API

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#931]
Luckily most of it is cached, but we still pay for bandwidth. What do we do?

**Comment by bdaroz** [comment]
Necro'ing an old issue... With APIv3 in work in #1507 and discussion on using a site-generated (and account-linked) API key, is this moot, or should an admin interface to revoke a key (and perhaps blacklist a user?) be appropriate then?

**Comment by fangeugene** [comment]
Admin interface to revoke key sounds good.

**Comment by fangeugene** [comment]
We can revoke keys with apiv3, though it is not yet implemented.
