### ISSUE TITLE
Increasing amount of blocked streams

### ISSUE THREAD

**Issue by synth3tk** [the-blue-alliance/the-blue-alliance#935]
I don't know what's going on. I'm assuming it's political/business-like, since a lot of them are working on another similarly-named webcast portal. Trying to get in contact with some of the people running the streams now. This is what we're getting on more and more streams this year:

![tba-unavailable](https://f.cloud.github.com/assets/2099988/2365672/418df862-a6d6-11e3-823f-e355b4da8a28.png)

**Comment by gregmarra** [comment]
Nothing we can do here, closing for now.

**Comment by synth3tk** [comment]
Thankfully most regionals either use a different platform this year, or whitelisted us, so it's mostly solved anyway.
