### ISSUE TITLE
Add an Access-Control-Allow-Origin header on to API

### ISSUE THREAD

**Issue by schreiaj** [the-blue-alliance/the-blue-alliance#940]
Adding the proper headers for enabling cross-origin resource sharing would allow easier integration of TBA data into various javascript applications. (d3/angular)

I'm unsure what is required to add this under App Engine.

**Comment by SamMaier** [comment]
Has anyone found a way around this with AngularJS?

**Comment by GiantBlargg** [comment]
The server should return Access-Control-Request-Headers: X-TBA-App-Id. This should fix the problem.

**Comment by terabyte128** [comment]
I have been able to connect to your API via JS in the past, but it's suddenly not working again, giving the lack of an Access-Control-Allow-Origin header. I've run the same command from above and produced:

````
➜  frc_scout_2015 git:(master) curl --verbose -H "X-TBA-App-Id: aschreiber:team_picker:1" http://www.thebluealliance.com/api/v2/events/list
*   Trying 104.27.143.180...
* Connected to www.thebluealliance.com (104.27.143.180) port 80 (#0)
> GET /api/v2/events/list HTTP/1.1
> Host: www.thebluealliance.com
> User-Agent: curl/7.43.0
> Accept: */*
> X-TBA-App-Id: aschreiber:team_picker:1
> 
< HTTP/1.1 301 Moved Permanently
< Date: Fri, 18 Sep 2015 04:26:10 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=dcfd756b100ef4d2fb0853a79372391231442550370; expires=Sat, 17-Sep-16 04:26:10 GMT; path=/; domain=.thebluealliance.com; HttpOnly
< Location: https://www.thebluealliance.com/api/v2/events/list
< Server: cloudflare-nginx
< CF-RAY: 227a4a8a459911d7-SJC
````

**Comment by fangeugene** [comment]
Try using https://www.thebluealliance.com/.... instead of http://...

**Comment by terabyte128** [comment]
@fangeugene That solved it, thank you! I didn't realize TBA's API was even available over SSL.

**Comment by fangeugene** [comment]
@terabyte128 It's a new addition. Sorry for breaking your app.

**Comment by terabyte128** [comment]
No worries, easy fix and better security is always good :)
