### ISSUE TITLE
Allow editing Medias

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#950]
For example, http://www.chiefdelphi.com/media/photos/27358 is on 2175 as a 2008 photo, but is from 2007.

**Comment by SUPERCILEX** [comment]
@phil-lopreiato This issue can be closed as per explanation https://github.com/the-blue-alliance/the-blue-alliance/issues/1186#issuecomment-292220578.

**Comment by fangeugene** [comment]
Refer to #1186
