### ISSUE TITLE
Migrate 2005glr matches to 2005gl

### ISSUE THREAD

**Issue by legoktm** [the-blue-alliance/the-blue-alliance#975]
Match results are under "2005glr": http://www.thebluealliance.com/event/2005glr

Awards are "2005gl": http://www.thebluealliance.com/event/2005gl

Didn't really check if any other events have this issue.

**Comment by fangeugene** [comment]
Fixed in https://github.com/the-blue-alliance/the-blue-alliance/issues/1165
