### ISSUE TITLE
http://www.thebluealliance.net/ is a redirect loop

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#986]
http://www.thebluealliance.net/robots.txt

**Comment by SUPERCILEX** [comment]
@phil-lopreiato This issue can be closed as per explanation https://github.com/the-blue-alliance/the-blue-alliance/issues/1244#issuecomment-292217756.

**Comment by fangeugene** [comment]
Refer to https://github.com/the-blue-alliance/the-blue-alliance/issues/685#issuecomment-299899909

**Comment by fangeugene** [comment]
We don't care about .net anymore.
